export {
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowsRotate,
    faBackward,
    faBackwardFast,
    faCircle,
    faCircleDot,
    faClock,
    faComputerSpeaker,
    faEllipsis,
    faFileMusic,
    faFolderOpen,
    faForward,
    faForwardFast,
    faHouse,
    faKey,
    faLinkSimple,
    faLinkSimpleSlash,
    faList,
    faMagnifyingGlass,
    faMessageLines,
    faMicrophone,
    faMoon,
    faMusic,
    faNetworkWired,
    faPause,
    faPlay,
    faPlugCirclePlus,
    faPlugCircleXmark,
    faPowerOff,
    faRadar,
    faRectangleVerticalHistory,
    faRepeat,
    faRouter,
    faShuffle,
    faSignalStream,
    faStop,
    faSun,
    faTowerBroadcast,
    faTv,
    faUser,
    faUserGroup,
    faVolume,
    faVolumeHigh,
    faVolumeLow,
    faVolumeXmark,
    faWaveSine
} from '@fortawesome/duotone-regular-svg-icons';

export {
    faApple
} from '@fortawesome/free-brands-svg-icons';
