// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file AdjustVolumeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { RequestDetails } from "./RequestDetails_pb";
import { file_RequestDetails } from "./RequestDetails_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AdjustVolumeMessage.proto.
 */
export const file_AdjustVolumeMessage: GenFile = /*@__PURE__*/
  fileDesc("ChlBZGp1c3RWb2x1bWVNZXNzYWdlLnByb3RvIo4CChNBZGp1c3RWb2x1bWVNZXNzYWdlEjMKCmFkanVzdG1lbnQYASABKA4yHy5BZGp1c3RWb2x1bWVNZXNzYWdlLkFkanVzdG1lbnQSFwoPb3V0cHV0RGV2aWNlVUlEGAIgASgJEiAKB2RldGFpbHMYAyABKAsyDy5SZXF1ZXN0RGV0YWlscyKGAQoKQWRqdXN0bWVudBISCg5JbmNyZW1lbnRTbWFsbBABEhMKD0luY3JlbWVudE1lZGl1bRACEhIKDkluY3JlbWVudExhcmdlEAMSEgoORGVjcmVtZW50U21hbGwQBBITCg9EZWNyZW1lbnRNZWRpdW0QBRISCg5EZWNyZW1lbnRMYXJnZRAGOlgKE2FkanVzdFZvbHVtZU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYYSABKAsyFC5BZGp1c3RWb2x1bWVNZXNzYWdlUhNhZGp1c3RWb2x1bWVNZXNzYWdl", [file_ProtocolMessage, file_RequestDetails]);

/**
 * @generated from message AdjustVolumeMessage
 */
export type AdjustVolumeMessage = Message<"AdjustVolumeMessage"> & {
  /**
   * @generated from field: optional AdjustVolumeMessage.Adjustment adjustment = 1;
   */
  adjustment: AdjustVolumeMessage_Adjustment;

  /**
   * @generated from field: optional string outputDeviceUID = 2;
   */
  outputDeviceUID: string;

  /**
   * @generated from field: optional RequestDetails details = 3;
   */
  details?: RequestDetails;
};

/**
 * Describes the message AdjustVolumeMessage.
 * Use `create(AdjustVolumeMessageSchema)` to create a new message.
 */
export const AdjustVolumeMessageSchema: GenMessage<AdjustVolumeMessage> = /*@__PURE__*/
  messageDesc(file_AdjustVolumeMessage, 0);

/**
 * @generated from enum AdjustVolumeMessage.Adjustment
 */
export enum AdjustVolumeMessage_Adjustment {
  /**
   * @generated from enum value: IncrementSmall = 1;
   */
  IncrementSmall = 1,

  /**
   * @generated from enum value: IncrementMedium = 2;
   */
  IncrementMedium = 2,

  /**
   * @generated from enum value: IncrementLarge = 3;
   */
  IncrementLarge = 3,

  /**
   * @generated from enum value: DecrementSmall = 4;
   */
  DecrementSmall = 4,

  /**
   * @generated from enum value: DecrementMedium = 5;
   */
  DecrementMedium = 5,

  /**
   * @generated from enum value: DecrementLarge = 6;
   */
  DecrementLarge = 6,
}

/**
 * Describes the enum AdjustVolumeMessage.Adjustment.
 */
export const AdjustVolumeMessage_AdjustmentSchema: GenEnum<AdjustVolumeMessage_Adjustment> = /*@__PURE__*/
  enumDesc(file_AdjustVolumeMessage, 0, 0);

/**
 * @generated from extension: optional AdjustVolumeMessage adjustVolumeMessage = 97;
 */
export const adjustVolumeMessage: GenExtension<ProtocolMessage, AdjustVolumeMessage> = /*@__PURE__*/
  extDesc(file_AdjustVolumeMessage, 0);

