// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file AirPlayLeaderInfo.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import { file_DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AirPlayLeaderInfo.proto.
 */
export const file_AirPlayLeaderInfo: GenFile = /*@__PURE__*/
  fileDesc("ChdBaXJQbGF5TGVhZGVySW5mby5wcm90byI7ChFBaXJQbGF5TGVhZGVySW5mbxImCgpkZXZpY2VJbmZvGAEgASgLMhIuRGV2aWNlSW5mb01lc3NhZ2U", [file_DeviceInfoMessage]);

/**
 * @generated from message AirPlayLeaderInfo
 */
export type AirPlayLeaderInfo = Message<"AirPlayLeaderInfo"> & {
  /**
   * @generated from field: optional DeviceInfoMessage deviceInfo = 1;
   */
  deviceInfo?: DeviceInfoMessage;
};

/**
 * Describes the message AirPlayLeaderInfo.
 * Use `create(AirPlayLeaderInfoSchema)` to create a new message.
 */
export const AirPlayLeaderInfoSchema: GenMessage<AirPlayLeaderInfo> = /*@__PURE__*/
  messageDesc(file_AirPlayLeaderInfo, 0);

