// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ApplicationConnection.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import { file_DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ApplicationConnection.proto.
 */
export const file_ApplicationConnection: GenFile = /*@__PURE__*/
  fileDesc("ChtBcHBsaWNhdGlvbkNvbm5lY3Rpb24ucHJvdG8icwocQXBwbGljYXRpb25Db25uZWN0aW9uQ29udGV4dBISCgppZGVudGlmaWVyGAEgASgJEhMKC3NlcnZpY2VOYW1lGAIgASgJEioKFWRlc3RpbmF0aW9uUGxheWVyUGF0aBgDIAEoCzILLlBsYXllclBhdGgiWgogQXBwbGljYXRpb25Db25uZWN0aW9uUmVxdWVzdEluZm8SDgoGY2xpZW50GAEgASgJEiYKCmRldmljZUluZm8YAiABKAsyEi5EZXZpY2VJbmZvTWVzc2FnZSJGCiJBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdlSGVhZGVyEgwKBHR5cGUYASABKAUSEgoKaWRlbnRpZmllchgCIAEoBSJuChxBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdlEjMKBmhlYWRlchgBIAEoCzIjLkFwcGxpY2F0aW9uQ29ubmVjdGlvbk1lc3NhZ2VIZWFkZXISGQoRdW5kZXJseWluZ01lc3NhZ2UYAiABKAw", [file_DeviceInfoMessage, file_PlayerPath]);

/**
 * @generated from message ApplicationConnectionContext
 */
export type ApplicationConnectionContext = Message<"ApplicationConnectionContext"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional string serviceName = 2;
   */
  serviceName: string;

  /**
   * @generated from field: optional PlayerPath destinationPlayerPath = 3;
   */
  destinationPlayerPath?: PlayerPath;
};

/**
 * Describes the message ApplicationConnectionContext.
 * Use `create(ApplicationConnectionContextSchema)` to create a new message.
 */
export const ApplicationConnectionContextSchema: GenMessage<ApplicationConnectionContext> = /*@__PURE__*/
  messageDesc(file_ApplicationConnection, 0);

/**
 * @generated from message ApplicationConnectionRequestInfo
 */
export type ApplicationConnectionRequestInfo = Message<"ApplicationConnectionRequestInfo"> & {
  /**
   * @generated from field: optional string client = 1;
   */
  client: string;

  /**
   * @generated from field: optional DeviceInfoMessage deviceInfo = 2;
   */
  deviceInfo?: DeviceInfoMessage;
};

/**
 * Describes the message ApplicationConnectionRequestInfo.
 * Use `create(ApplicationConnectionRequestInfoSchema)` to create a new message.
 */
export const ApplicationConnectionRequestInfoSchema: GenMessage<ApplicationConnectionRequestInfo> = /*@__PURE__*/
  messageDesc(file_ApplicationConnection, 1);

/**
 * @generated from message ApplicationConnectionMessageHeader
 */
export type ApplicationConnectionMessageHeader = Message<"ApplicationConnectionMessageHeader"> & {
  /**
   * @generated from field: optional int32 type = 1;
   */
  type: number;

  /**
   * @generated from field: optional int32 identifier = 2;
   */
  identifier: number;
};

/**
 * Describes the message ApplicationConnectionMessageHeader.
 * Use `create(ApplicationConnectionMessageHeaderSchema)` to create a new message.
 */
export const ApplicationConnectionMessageHeaderSchema: GenMessage<ApplicationConnectionMessageHeader> = /*@__PURE__*/
  messageDesc(file_ApplicationConnection, 2);

/**
 * @generated from message ApplicationConnectionMessage
 */
export type ApplicationConnectionMessage = Message<"ApplicationConnectionMessage"> & {
  /**
   * @generated from field: optional ApplicationConnectionMessageHeader header = 1;
   */
  header?: ApplicationConnectionMessageHeader;

  /**
   * @generated from field: optional bytes underlyingMessage = 2;
   */
  underlyingMessage: Uint8Array;
};

/**
 * Describes the message ApplicationConnectionMessage.
 * Use `create(ApplicationConnectionMessageSchema)` to create a new message.
 */
export const ApplicationConnectionMessageSchema: GenMessage<ApplicationConnectionMessage> = /*@__PURE__*/
  messageDesc(file_ApplicationConnection, 3);

