// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file Artwork.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Artwork.proto.
 */
export const file_Artwork: GenFile = /*@__PURE__*/
  fileDesc("Cg1BcnR3b3JrLnByb3RvIjkKD0FuaW1hdGVkQXJ0d29yaxIMCgR0eXBlGAEgASgJEhgKEGFzc2V0RmlsZVVSTERhdGEYAiABKAwiLgoLRGF0YUFydHdvcmsSDAoEdHlwZRgBIAEoCRIRCglpbWFnZURhdGEYAiABKAwiVwoNUmVtb3RlQXJ0d29yaxIMCgR0eXBlGAEgASgJEhgKEGFydHdvcmtVUkxTdHJpbmcYAiABKAkSHgoWYXJ0d29ya1VSTFRlbXBsYXRlRGF0YRgDIAEoDA");

/**
 * @generated from message AnimatedArtwork
 */
export type AnimatedArtwork = Message<"AnimatedArtwork"> & {
  /**
   * @generated from field: optional string type = 1;
   */
  type: string;

  /**
   * @generated from field: optional bytes assetFileURLData = 2;
   */
  assetFileURLData: Uint8Array;
};

/**
 * Describes the message AnimatedArtwork.
 * Use `create(AnimatedArtworkSchema)` to create a new message.
 */
export const AnimatedArtworkSchema: GenMessage<AnimatedArtwork> = /*@__PURE__*/
  messageDesc(file_Artwork, 0);

/**
 * @generated from message DataArtwork
 */
export type DataArtwork = Message<"DataArtwork"> & {
  /**
   * @generated from field: optional string type = 1;
   */
  type: string;

  /**
   * @generated from field: optional bytes imageData = 2;
   */
  imageData: Uint8Array;
};

/**
 * Describes the message DataArtwork.
 * Use `create(DataArtworkSchema)` to create a new message.
 */
export const DataArtworkSchema: GenMessage<DataArtwork> = /*@__PURE__*/
  messageDesc(file_Artwork, 1);

/**
 * @generated from message RemoteArtwork
 */
export type RemoteArtwork = Message<"RemoteArtwork"> & {
  /**
   * @generated from field: optional string type = 1;
   */
  type: string;

  /**
   * @generated from field: optional string artworkURLString = 2;
   */
  artworkURLString: string;

  /**
   * @generated from field: optional bytes artworkURLTemplateData = 3;
   */
  artworkURLTemplateData: Uint8Array;
};

/**
 * Describes the message RemoteArtwork.
 * Use `create(RemoteArtworkSchema)` to create a new message.
 */
export const RemoteArtworkSchema: GenMessage<RemoteArtwork> = /*@__PURE__*/
  messageDesc(file_Artwork, 2);

