// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file AudioFadeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AudioFadeMessage.proto.
 */
export const file_AudioFadeMessage: GenFile = /*@__PURE__*/
  fileDesc("ChZBdWRpb0ZhZGVNZXNzYWdlLnByb3RvIkUKEEF1ZGlvRmFkZU1lc3NhZ2USHwoKcGxheWVyUGF0aBgBIAEoCzILLlBsYXllclBhdGgSEAoIZmFkZVR5cGUYAiABKAU6TwoQYXVkaW9GYWRlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhYIAEoCzIRLkF1ZGlvRmFkZU1lc3NhZ2VSEGF1ZGlvRmFkZU1lc3NhZ2U", [file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message AudioFadeMessage
 */
export type AudioFadeMessage = Message<"AudioFadeMessage"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional int32 fadeType = 2;
   */
  fadeType: number;
};

/**
 * Describes the message AudioFadeMessage.
 * Use `create(AudioFadeMessageSchema)` to create a new message.
 */
export const AudioFadeMessageSchema: GenMessage<AudioFadeMessage> = /*@__PURE__*/
  messageDesc(file_AudioFadeMessage, 0);

/**
 * @generated from extension: optional AudioFadeMessage audioFadeMessage = 88;
 */
export const audioFadeMessage: GenExtension<ProtocolMessage, AudioFadeMessage> = /*@__PURE__*/
  extDesc(file_AudioFadeMessage, 0);

