// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file AudioFadeResponseMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AudioFadeResponseMessage.proto.
 */
export const file_AudioFadeResponseMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch5BdWRpb0ZhZGVSZXNwb25zZU1lc3NhZ2UucHJvdG8iMAoYQXVkaW9GYWRlUmVzcG9uc2VNZXNzYWdlEhQKDGZhZGVEdXJhdGlvbhgBIAEoAzpnChhhdWRpb0ZhZGVSZXNwb25zZU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYWSABKAsyGS5BdWRpb0ZhZGVSZXNwb25zZU1lc3NhZ2VSGGF1ZGlvRmFkZVJlc3BvbnNlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message AudioFadeResponseMessage
 */
export type AudioFadeResponseMessage = Message<"AudioFadeResponseMessage"> & {
  /**
   * @generated from field: optional int64 fadeDuration = 1;
   */
  fadeDuration: bigint;
};

/**
 * Describes the message AudioFadeResponseMessage.
 * Use `create(AudioFadeResponseMessageSchema)` to create a new message.
 */
export const AudioFadeResponseMessageSchema: GenMessage<AudioFadeResponseMessage> = /*@__PURE__*/
  messageDesc(file_AudioFadeResponseMessage, 0);

/**
 * @generated from extension: optional AudioFadeResponseMessage audioFadeResponseMessage = 89;
 */
export const audioFadeResponseMessage: GenExtension<ProtocolMessage, AudioFadeResponseMessage> = /*@__PURE__*/
  extDesc(file_AudioFadeResponseMessage, 0);

