// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file AudioFormatSettingsMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AudioFormatSettingsMessage.proto.
 */
export const file_AudioFormatSettingsMessage: GenFile = /*@__PURE__*/
  fileDesc("CiBBdWRpb0Zvcm1hdFNldHRpbmdzTWVzc2FnZS5wcm90byI2ChNBdWRpb0Zvcm1hdFNldHRpbmdzEh8KF2Zvcm1hdFNldHRpbmdzUGxpc3REYXRhGAEgASgM");

/**
 * @generated from message AudioFormatSettings
 */
export type AudioFormatSettings = Message<"AudioFormatSettings"> & {
  /**
   * @generated from field: optional bytes formatSettingsPlistData = 1;
   */
  formatSettingsPlistData: Uint8Array;
};

/**
 * Describes the message AudioFormatSettings.
 * Use `create(AudioFormatSettingsSchema)` to create a new message.
 */
export const AudioFormatSettingsSchema: GenMessage<AudioFormatSettings> = /*@__PURE__*/
  messageDesc(file_AudioFormatSettingsMessage, 0);

