// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file AVAirPlaySecuritySettings.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AVAirPlaySecuritySettings.proto.
 */
export const file_AVAirPlaySecuritySettings: GenFile = /*@__PURE__*/
  fileDesc("Ch9BVkFpclBsYXlTZWN1cml0eVNldHRpbmdzLnByb3RvIkMKGUFWQWlyUGxheVNlY3VyaXR5U2V0dGluZ3MSEAoIcGFzc3dvcmQYASABKAkSFAoMc2VjdXJpdHlUeXBlGAIgASgF");

/**
 * @generated from message AVAirPlaySecuritySettings
 */
export type AVAirPlaySecuritySettings = Message<"AVAirPlaySecuritySettings"> & {
  /**
   * @generated from field: optional string password = 1;
   */
  password: string;

  /**
   * @generated from field: optional int32 securityType = 2;
   */
  securityType: number;
};

/**
 * Describes the message AVAirPlaySecuritySettings.
 * Use `create(AVAirPlaySecuritySettingsSchema)` to create a new message.
 */
export const AVAirPlaySecuritySettingsSchema: GenMessage<AVAirPlaySecuritySettings> = /*@__PURE__*/
  messageDesc(file_AVAirPlaySecuritySettings, 0);

