// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file AVRouteQuery.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file AVRouteQuery.proto.
 */
export const file_AVRouteQuery: GenFile = /*@__PURE__*/
  fileDesc("ChJBVlJvdXRlUXVlcnkucHJvdG8iIAoMQVZSb3V0ZVF1ZXJ5EhAKCHJvdXRlVUlEGAEgASgJ");

/**
 * @generated from message AVRouteQuery
 */
export type AVRouteQuery = Message<"AVRouteQuery"> & {
  /**
   * @generated from field: optional string routeUID = 1;
   */
  routeUID: string;
};

/**
 * Describes the message AVRouteQuery.
 * Use `create(AVRouteQuerySchema)` to create a new message.
 */
export const AVRouteQuerySchema: GenMessage<AVRouteQuery> = /*@__PURE__*/
  messageDesc(file_AVRouteQuery, 0);

