// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ClientUpdatesConfigMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ClientUpdatesConfigMessage.proto.
 */
export const file_ClientUpdatesConfigMessage: GenFile = /*@__PURE__*/
  fileDesc("CiBDbGllbnRVcGRhdGVzQ29uZmlnTWVzc2FnZS5wcm90byLnAQoaQ2xpZW50VXBkYXRlc0NvbmZpZ01lc3NhZ2USFgoOYXJ0d29ya1VwZGF0ZXMYASABKAgSGQoRbm93UGxheWluZ1VwZGF0ZXMYAiABKAgSFQoNdm9sdW1lVXBkYXRlcxgDIAEoCBIXCg9rZXlib2FyZFVwZGF0ZXMYBCABKAgSGwoTb3V0cHV0RGV2aWNlVXBkYXRlcxgFIAEoCBIdChVzeXN0ZW1FbmRwb2ludFVwZGF0ZXMYBiABKAgSKgoVc3Vic2NyaWJlZFBsYXllclBhdGhzGAcgAygLMgsuUGxheWVyUGF0aDptChpjbGllbnRVcGRhdGVzQ29uZmlnTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgVIAEoCzIbLkNsaWVudFVwZGF0ZXNDb25maWdNZXNzYWdlUhpjbGllbnRVcGRhdGVzQ29uZmlnTWVzc2FnZQ", [file_PlayerPath, file_ProtocolMessage]);

/**
 * @generated from message ClientUpdatesConfigMessage
 */
export type ClientUpdatesConfigMessage = Message<"ClientUpdatesConfigMessage"> & {
  /**
   * @generated from field: optional bool artworkUpdates = 1;
   */
  artworkUpdates: boolean;

  /**
   * @generated from field: optional bool nowPlayingUpdates = 2;
   */
  nowPlayingUpdates: boolean;

  /**
   * @generated from field: optional bool volumeUpdates = 3;
   */
  volumeUpdates: boolean;

  /**
   * @generated from field: optional bool keyboardUpdates = 4;
   */
  keyboardUpdates: boolean;

  /**
   * @generated from field: optional bool outputDeviceUpdates = 5;
   */
  outputDeviceUpdates: boolean;

  /**
   * @generated from field: optional bool systemEndpointUpdates = 6;
   */
  systemEndpointUpdates: boolean;

  /**
   * @generated from field: repeated PlayerPath subscribedPlayerPaths = 7;
   */
  subscribedPlayerPaths: PlayerPath[];
};

/**
 * Describes the message ClientUpdatesConfigMessage.
 * Use `create(ClientUpdatesConfigMessageSchema)` to create a new message.
 */
export const ClientUpdatesConfigMessageSchema: GenMessage<ClientUpdatesConfigMessage> = /*@__PURE__*/
  messageDesc(file_ClientUpdatesConfigMessage, 0);

/**
 * @generated from extension: optional ClientUpdatesConfigMessage clientUpdatesConfigMessage = 21;
 */
export const clientUpdatesConfigMessage: GenExtension<ProtocolMessage, ClientUpdatesConfigMessage> = /*@__PURE__*/
  extDesc(file_ClientUpdatesConfigMessage, 0);

