// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file Common.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Common.proto.
 */
export const file_Common: GenFile = /*@__PURE__*/
  fileDesc("CgxDb21tb24ucHJvdG8iPAoKUmVwZWF0TW9kZSIuCgRFbnVtEgsKB1Vua25vd24QABIHCgNPZmYQARIHCgNPbmUQAhIHCgNBbGwQAyJCCgtTaHVmZmxlTW9kZSIzCgRFbnVtEgsKB1Vua25vd24QABIHCgNPZmYQARIKCgZBbGJ1bXMQAhIJCgVTb25ncxADIokBCgtEZXZpY2VDbGFzcyJ6CgRFbnVtEgsKB0ludmFsaWQQABIKCgZpUGhvbmUQARIICgRpUG9kEAISCAoEaVBhZBADEgsKB0FwcGxlVFYQBBIJCgVpRlBHQRAFEgkKBVdhdGNoEAYSDQoJQWNjZXNzb3J5EAcSCgoGQnJpZGdlEAgSBwoDTWFjEAkiYgoKRGV2aWNlVHlwZSJUCgRFbnVtEgsKB1Vua25vd24QABILCgdBaXJQbGF5EAESDQoJQmx1ZXRvb3RoEAISCwoHQ2FyUGxheRADEgsKB0J1aWx0SW4QBBIJCgVXaXJlZBAFIoACCg1EZXZpY2VTdWJUeXBlIu4BCgRFbnVtEgsKB0RlZmF1bHQQABILCgdTcGVha2VyEAESDgoKSGVhZHBob25lcxACEgsKB0hlYWRzZXQQAxIMCghSZWNlaXZlchAEEgsKB0xpbmVPdXQQBRIHCgNVU0IQBhIPCgtEaXNwbGF5UG9ydBAHEggKBEhETUkQCBINCglMb3dFbmVyZ3kQCRIJCgVTUERJRhAKEgYKAlRWEAsSCwoHSG9tZVBvZBAMEgsKB0FwcGxlVFYQDRILCgdWZWhpY2xlEA4SCwoHQ2x1c3RlchAPEg0KCVNldFRvcEJveBAQEgsKB1RWU3RpY2sQESJoCg1QbGF5YmFja1N0YXRlIlcKBEVudW0SCwoHVW5rbm93bhAAEgsKB1BsYXlpbmcQARIKCgZQYXVzZWQQAhILCgdTdG9wcGVkEAMSDwoLSW50ZXJydXB0ZWQQBBILCgdTZWVraW5nEAU");

/**
 * @generated from message RepeatMode
 */
export type RepeatMode = Message<"RepeatMode"> & {
};

/**
 * Describes the message RepeatMode.
 * Use `create(RepeatModeSchema)` to create a new message.
 */
export const RepeatModeSchema: GenMessage<RepeatMode> = /*@__PURE__*/
  messageDesc(file_Common, 0);

/**
 * @generated from enum RepeatMode.Enum
 */
export enum RepeatMode_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Off = 1;
   */
  Off = 1,

  /**
   * @generated from enum value: One = 2;
   */
  One = 2,

  /**
   * @generated from enum value: All = 3;
   */
  All = 3,
}

/**
 * Describes the enum RepeatMode.Enum.
 */
export const RepeatMode_EnumSchema: GenEnum<RepeatMode_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 0, 0);

/**
 * @generated from message ShuffleMode
 */
export type ShuffleMode = Message<"ShuffleMode"> & {
};

/**
 * Describes the message ShuffleMode.
 * Use `create(ShuffleModeSchema)` to create a new message.
 */
export const ShuffleModeSchema: GenMessage<ShuffleMode> = /*@__PURE__*/
  messageDesc(file_Common, 1);

/**
 * @generated from enum ShuffleMode.Enum
 */
export enum ShuffleMode_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Off = 1;
   */
  Off = 1,

  /**
   * @generated from enum value: Albums = 2;
   */
  Albums = 2,

  /**
   * @generated from enum value: Songs = 3;
   */
  Songs = 3,
}

/**
 * Describes the enum ShuffleMode.Enum.
 */
export const ShuffleMode_EnumSchema: GenEnum<ShuffleMode_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 1, 0);

/**
 * @generated from message DeviceClass
 */
export type DeviceClass = Message<"DeviceClass"> & {
};

/**
 * Describes the message DeviceClass.
 * Use `create(DeviceClassSchema)` to create a new message.
 */
export const DeviceClassSchema: GenMessage<DeviceClass> = /*@__PURE__*/
  messageDesc(file_Common, 2);

/**
 * @generated from enum DeviceClass.Enum
 */
export enum DeviceClass_Enum {
  /**
   * @generated from enum value: Invalid = 0;
   */
  Invalid = 0,

  /**
   * @generated from enum value: iPhone = 1;
   */
  iPhone = 1,

  /**
   * @generated from enum value: iPod = 2;
   */
  iPod = 2,

  /**
   * @generated from enum value: iPad = 3;
   */
  iPad = 3,

  /**
   * @generated from enum value: AppleTV = 4;
   */
  AppleTV = 4,

  /**
   * @generated from enum value: iFPGA = 5;
   */
  iFPGA = 5,

  /**
   * @generated from enum value: Watch = 6;
   */
  Watch = 6,

  /**
   * @generated from enum value: Accessory = 7;
   */
  Accessory = 7,

  /**
   * @generated from enum value: Bridge = 8;
   */
  Bridge = 8,

  /**
   * @generated from enum value: Mac = 9;
   */
  Mac = 9,
}

/**
 * Describes the enum DeviceClass.Enum.
 */
export const DeviceClass_EnumSchema: GenEnum<DeviceClass_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 2, 0);

/**
 * @generated from message DeviceType
 */
export type DeviceType = Message<"DeviceType"> & {
};

/**
 * Describes the message DeviceType.
 * Use `create(DeviceTypeSchema)` to create a new message.
 */
export const DeviceTypeSchema: GenMessage<DeviceType> = /*@__PURE__*/
  messageDesc(file_Common, 3);

/**
 * @generated from enum DeviceType.Enum
 */
export enum DeviceType_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: AirPlay = 1;
   */
  AirPlay = 1,

  /**
   * @generated from enum value: Bluetooth = 2;
   */
  Bluetooth = 2,

  /**
   * @generated from enum value: CarPlay = 3;
   */
  CarPlay = 3,

  /**
   * @generated from enum value: BuiltIn = 4;
   */
  BuiltIn = 4,

  /**
   * @generated from enum value: Wired = 5;
   */
  Wired = 5,
}

/**
 * Describes the enum DeviceType.Enum.
 */
export const DeviceType_EnumSchema: GenEnum<DeviceType_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 3, 0);

/**
 * @generated from message DeviceSubType
 */
export type DeviceSubType = Message<"DeviceSubType"> & {
};

/**
 * Describes the message DeviceSubType.
 * Use `create(DeviceSubTypeSchema)` to create a new message.
 */
export const DeviceSubTypeSchema: GenMessage<DeviceSubType> = /*@__PURE__*/
  messageDesc(file_Common, 4);

/**
 * @generated from enum DeviceSubType.Enum
 */
export enum DeviceSubType_Enum {
  /**
   * @generated from enum value: Default = 0;
   */
  Default = 0,

  /**
   * @generated from enum value: Speaker = 1;
   */
  Speaker = 1,

  /**
   * @generated from enum value: Headphones = 2;
   */
  Headphones = 2,

  /**
   * @generated from enum value: Headset = 3;
   */
  Headset = 3,

  /**
   * @generated from enum value: Receiver = 4;
   */
  Receiver = 4,

  /**
   * @generated from enum value: LineOut = 5;
   */
  LineOut = 5,

  /**
   * @generated from enum value: USB = 6;
   */
  USB = 6,

  /**
   * @generated from enum value: DisplayPort = 7;
   */
  DisplayPort = 7,

  /**
   * @generated from enum value: HDMI = 8;
   */
  HDMI = 8,

  /**
   * @generated from enum value: LowEnergy = 9;
   */
  LowEnergy = 9,

  /**
   * @generated from enum value: SPDIF = 10;
   */
  SPDIF = 10,

  /**
   * @generated from enum value: TV = 11;
   */
  TV = 11,

  /**
   * @generated from enum value: HomePod = 12;
   */
  HomePod = 12,

  /**
   * @generated from enum value: AppleTV = 13;
   */
  AppleTV = 13,

  /**
   * @generated from enum value: Vehicle = 14;
   */
  Vehicle = 14,

  /**
   * @generated from enum value: Cluster = 15;
   */
  Cluster = 15,

  /**
   * @generated from enum value: SetTopBox = 16;
   */
  SetTopBox = 16,

  /**
   * @generated from enum value: TVStick = 17;
   */
  TVStick = 17,
}

/**
 * Describes the enum DeviceSubType.Enum.
 */
export const DeviceSubType_EnumSchema: GenEnum<DeviceSubType_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 4, 0);

/**
 * @generated from message PlaybackState
 */
export type PlaybackState = Message<"PlaybackState"> & {
};

/**
 * Describes the message PlaybackState.
 * Use `create(PlaybackStateSchema)` to create a new message.
 */
export const PlaybackStateSchema: GenMessage<PlaybackState> = /*@__PURE__*/
  messageDesc(file_Common, 5);

/**
 * @generated from enum PlaybackState.Enum
 */
export enum PlaybackState_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Playing = 1;
   */
  Playing = 1,

  /**
   * @generated from enum value: Paused = 2;
   */
  Paused = 2,

  /**
   * @generated from enum value: Stopped = 3;
   */
  Stopped = 3,

  /**
   * @generated from enum value: Interrupted = 4;
   */
  Interrupted = 4,

  /**
   * @generated from enum value: Seeking = 5;
   */
  Seeking = 5,
}

/**
 * Describes the enum PlaybackState.Enum.
 */
export const PlaybackState_EnumSchema: GenEnum<PlaybackState_Enum> = /*@__PURE__*/
  enumDesc(file_Common, 5, 0);

