// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file CommandOptions.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { RepeatMode_Enum, ShuffleMode_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file CommandOptions.proto.
 */
export const file_CommandOptions: GenFile = /*@__PURE__*/
  fileDesc("ChRDb21tYW5kT3B0aW9ucy5wcm90byLhBgoOQ29tbWFuZE9wdGlvbnMSEAoIc291cmNlSWQYAiABKAkSEQoJbWVkaWFUeXBlGAMgASgJEh0KFWV4dGVybmFsUGxheWVyQ29tbWFuZBgEIAEoCBIUCgxza2lwSW50ZXJ2YWwYBSABKAISFAoMcGxheWJhY2tSYXRlGAYgASgCEg4KBnJhdGluZxgHIAEoAhIQCghuZWdhdGl2ZRgIIAEoCBIYChBwbGF5YmFja1Bvc2l0aW9uGAkgASgBEiQKCnJlcGVhdE1vZGUYCiABKA4yEC5SZXBlYXRNb2RlLkVudW0SJgoLc2h1ZmZsZU1vZGUYCyABKA4yES5TaHVmZmxlTW9kZS5FbnVtEg8KB3RyYWNrSUQYDCABKAQSFgoOcmFkaW9TdGF0aW9uSUQYDSABKAMSGAoQcmFkaW9TdGF0aW9uSGFzaBgOIAEoCRIiChpzeXN0ZW1BcHBQbGF5YmFja1F1ZXVlRGF0YRgPIAEoDBIfChdkZXN0aW5hdGlvbkFwcERpc3BsYXlJRBgQIAEoCRITCgtzZW5kT3B0aW9ucxgRIAEoDRIvCidyZXF1ZXN0RGVmZXJtZW50VG9QbGF5YmFja1F1ZXVlUG9zaXRpb24YEiABKAgSEQoJY29udGV4dElEGBMgASgJEioKInNob3VsZE92ZXJyaWRlTWFudWFsbHlDdXJhdGVkUXVldWUYFCABKAgSEgoKc3RhdGlvblVSTBgVIAEoCRIgChhzaG91bGRCZWdpblJhZGlvUGxheWJhY2sYFiABKAgSJgoecGxheWJhY2tRdWV1ZUluc2VydGlvblBvc2l0aW9uGBcgASgFEhUKDWNvbnRlbnRJdGVtSUQYGCABKAkSGwoTcGxheWJhY2tRdWV1ZU9mZnNldBgZIAEoBRImCh5wbGF5YmFja1F1ZXVlRGVzdGluYXRpb25PZmZzZXQYGiABKAUSFgoObGFuZ3VhZ2VPcHRpb24YGyABKAwSHAoUcGxheWJhY2tRdWV1ZUNvbnRleHQYHCABKAwSIAoYaW5zZXJ0QWZ0ZXJDb250ZW50SXRlbUlEGB0gASgJEh8KF25vd1BsYXlpbmdDb250ZW50SXRlbUlEGB4gASgJEhUKDXJlcGxhY2VJbnRlbnQYHyABKAU", [file_Common]);

/**
 * @generated from message CommandOptions
 */
export type CommandOptions = Message<"CommandOptions"> & {
  /**
   * @generated from field: optional string sourceId = 2;
   */
  sourceId: string;

  /**
   * @generated from field: optional string mediaType = 3;
   */
  mediaType: string;

  /**
   * @generated from field: optional bool externalPlayerCommand = 4;
   */
  externalPlayerCommand: boolean;

  /**
   * @generated from field: optional float skipInterval = 5;
   */
  skipInterval: number;

  /**
   * @generated from field: optional float playbackRate = 6;
   */
  playbackRate: number;

  /**
   * @generated from field: optional float rating = 7;
   */
  rating: number;

  /**
   * @generated from field: optional bool negative = 8;
   */
  negative: boolean;

  /**
   * @generated from field: optional double playbackPosition = 9;
   */
  playbackPosition: number;

  /**
   * @generated from field: optional RepeatMode.Enum repeatMode = 10;
   */
  repeatMode: RepeatMode_Enum;

  /**
   * @generated from field: optional ShuffleMode.Enum shuffleMode = 11;
   */
  shuffleMode: ShuffleMode_Enum;

  /**
   * @generated from field: optional uint64 trackID = 12;
   */
  trackID: bigint;

  /**
   * @generated from field: optional int64 radioStationID = 13;
   */
  radioStationID: bigint;

  /**
   * @generated from field: optional string radioStationHash = 14;
   */
  radioStationHash: string;

  /**
   * @generated from field: optional bytes systemAppPlaybackQueueData = 15;
   */
  systemAppPlaybackQueueData: Uint8Array;

  /**
   * @generated from field: optional string destinationAppDisplayID = 16;
   */
  destinationAppDisplayID: string;

  /**
   * @generated from field: optional uint32 sendOptions = 17;
   */
  sendOptions: number;

  /**
   * @generated from field: optional bool requestDefermentToPlaybackQueuePosition = 18;
   */
  requestDefermentToPlaybackQueuePosition: boolean;

  /**
   * @generated from field: optional string contextID = 19;
   */
  contextID: string;

  /**
   * @generated from field: optional bool shouldOverrideManuallyCuratedQueue = 20;
   */
  shouldOverrideManuallyCuratedQueue: boolean;

  /**
   * @generated from field: optional string stationURL = 21;
   */
  stationURL: string;

  /**
   * @generated from field: optional bool shouldBeginRadioPlayback = 22;
   */
  shouldBeginRadioPlayback: boolean;

  /**
   * @generated from field: optional int32 playbackQueueInsertionPosition = 23;
   */
  playbackQueueInsertionPosition: number;

  /**
   * @generated from field: optional string contentItemID = 24;
   */
  contentItemID: string;

  /**
   * @generated from field: optional int32 playbackQueueOffset = 25;
   */
  playbackQueueOffset: number;

  /**
   * @generated from field: optional int32 playbackQueueDestinationOffset = 26;
   */
  playbackQueueDestinationOffset: number;

  /**
   * @generated from field: optional bytes languageOption = 27;
   */
  languageOption: Uint8Array;

  /**
   * @generated from field: optional bytes playbackQueueContext = 28;
   */
  playbackQueueContext: Uint8Array;

  /**
   * @generated from field: optional string insertAfterContentItemID = 29;
   */
  insertAfterContentItemID: string;

  /**
   * @generated from field: optional string nowPlayingContentItemID = 30;
   */
  nowPlayingContentItemID: string;

  /**
   * @generated from field: optional int32 replaceIntent = 31;
   */
  replaceIntent: number;
};

/**
 * Describes the message CommandOptions.
 * Use `create(CommandOptionsSchema)` to create a new message.
 */
export const CommandOptionsSchema: GenMessage<CommandOptions> = /*@__PURE__*/
  messageDesc(file_CommandOptions, 0);

