// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ConfigureConnectionMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ConfigureConnectionMessage.proto.
 */
export const file_ConfigureConnectionMessage: GenFile = /*@__PURE__*/
  fileDesc("CiBDb25maWd1cmVDb25uZWN0aW9uTWVzc2FnZS5wcm90byKlAQoaQ29uZmlndXJlQ29ubmVjdGlvbk1lc3NhZ2USDwoHZ3JvdXBJRBgBIAEoCRITCgtzZXJ2aWNlTmFtZRgCIAEoCRIdChVzb3VyY2VPdXRwdXREZXZpY2VVSUQYAyABKAkSHgoWc291cmNlT3V0cHV0RGV2aWNlTmFtZRgEIAEoCRIiChpkZXN0aW5hdGlvbk91dHB1dERldmljZVVJRBgFIAEoCTptChpjb25maWd1cmVDb25uZWN0aW9uTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRheIAEoCzIbLkNvbmZpZ3VyZUNvbm5lY3Rpb25NZXNzYWdlUhpjb25maWd1cmVDb25uZWN0aW9uTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message ConfigureConnectionMessage
 */
export type ConfigureConnectionMessage = Message<"ConfigureConnectionMessage"> & {
  /**
   * @generated from field: optional string groupID = 1;
   */
  groupID: string;

  /**
   * @generated from field: optional string serviceName = 2;
   */
  serviceName: string;

  /**
   * @generated from field: optional string sourceOutputDeviceUID = 3;
   */
  sourceOutputDeviceUID: string;

  /**
   * @generated from field: optional string sourceOutputDeviceName = 4;
   */
  sourceOutputDeviceName: string;

  /**
   * @generated from field: optional string destinationOutputDeviceUID = 5;
   */
  destinationOutputDeviceUID: string;
};

/**
 * Describes the message ConfigureConnectionMessage.
 * Use `create(ConfigureConnectionMessageSchema)` to create a new message.
 */
export const ConfigureConnectionMessageSchema: GenMessage<ConfigureConnectionMessage> = /*@__PURE__*/
  messageDesc(file_ConfigureConnectionMessage, 0);

/**
 * @generated from extension: optional ConfigureConnectionMessage configureConnectionMessage = 94;
 */
export const configureConnectionMessage: GenExtension<ProtocolMessage, ConfigureConnectionMessage> = /*@__PURE__*/
  extDesc(file_ConfigureConnectionMessage, 0);

