// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file ContentItem.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ContentItemMetadata } from "./ContentItemMetadata_pb";
import { file_ContentItemMetadata } from "./ContentItemMetadata_pb";
import type { LanguageOption } from "./LanguageOption_pb";
import { file_LanguageOption } from "./LanguageOption_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ContentItem.proto.
 */
export const file_ContentItem: GenFile = /*@__PURE__*/
  fileDesc("ChFDb250ZW50SXRlbS5wcm90byKMAQoTTGFuZ3VhZ2VPcHRpb25Hcm91cBIbChNhbGxvd0VtcHR5U2VsZWN0aW9uGAEgASgIEi4KFWRlZmF1bHRMYW5ndWFnZU9wdGlvbhgCIAEoCzIPLkxhbmd1YWdlT3B0aW9uEigKD2xhbmd1YWdlT3B0aW9ucxgDIAMoCzIPLkxhbmd1YWdlT3B0aW9uIvQCCgtDb250ZW50SXRlbRISCgppZGVudGlmaWVyGAEgASgJEiYKCG1ldGFkYXRhGAIgASgLMhQuQ29udGVudEl0ZW1NZXRhZGF0YRITCgthcnR3b3JrRGF0YRgDIAEoDBIMCgRpbmZvGAQgASgJEjYKGGF2YWlsYWJsZUxhbmd1YWdlT3B0aW9ucxgFIAMoCzIULkxhbmd1YWdlT3B0aW9uR3JvdXASLwoWY3VycmVudExhbmd1YWdlT3B0aW9ucxgGIAMoCzIPLkxhbmd1YWdlT3B0aW9uEhgKEHBhcmVudElkZW50aWZpZXIYCSABKAkSGgoSYW5jZXN0b3JJZGVudGlmaWVyGAogASgJEhcKD3F1ZXVlSWRlbnRpZmllchgLIAEoCRIZChFyZXF1ZXN0SWRlbnRpZmllchgMIAEoCRIYChBhcnR3b3JrRGF0YVdpZHRoGA0gASgFEhkKEWFydHdvcmtEYXRhSGVpZ2h0GA4gASgF", [file_ContentItemMetadata, file_LanguageOption]);

/**
 * @generated from message LanguageOptionGroup
 */
export type LanguageOptionGroup = Message<"LanguageOptionGroup"> & {
  /**
   * @generated from field: optional bool allowEmptySelection = 1;
   */
  allowEmptySelection: boolean;

  /**
   * @generated from field: optional LanguageOption defaultLanguageOption = 2;
   */
  defaultLanguageOption?: LanguageOption;

  /**
   * @generated from field: repeated LanguageOption languageOptions = 3;
   */
  languageOptions: LanguageOption[];
};

/**
 * Describes the message LanguageOptionGroup.
 * Use `create(LanguageOptionGroupSchema)` to create a new message.
 */
export const LanguageOptionGroupSchema: GenMessage<LanguageOptionGroup> = /*@__PURE__*/
  messageDesc(file_ContentItem, 0);

/**
 * @generated from message ContentItem
 */
export type ContentItem = Message<"ContentItem"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional ContentItemMetadata metadata = 2;
   */
  metadata?: ContentItemMetadata;

  /**
   * @generated from field: optional bytes artworkData = 3;
   */
  artworkData: Uint8Array;

  /**
   * @generated from field: optional string info = 4;
   */
  info: string;

  /**
   * @generated from field: repeated LanguageOptionGroup availableLanguageOptions = 5;
   */
  availableLanguageOptions: LanguageOptionGroup[];

  /**
   * @generated from field: repeated LanguageOption currentLanguageOptions = 6;
   */
  currentLanguageOptions: LanguageOption[];

  /**
   *  optional Lyrics lyrics = 7;
   *  repeated Sections sections = 8;
   *
   * @generated from field: optional string parentIdentifier = 9;
   */
  parentIdentifier: string;

  /**
   * @generated from field: optional string ancestorIdentifier = 10;
   */
  ancestorIdentifier: string;

  /**
   * @generated from field: optional string queueIdentifier = 11;
   */
  queueIdentifier: string;

  /**
   * @generated from field: optional string requestIdentifier = 12;
   */
  requestIdentifier: string;

  /**
   * @generated from field: optional int32 artworkDataWidth = 13;
   */
  artworkDataWidth: number;

  /**
   * @generated from field: optional int32 artworkDataHeight = 14;
   */
  artworkDataHeight: number;
};

/**
 * Describes the message ContentItem.
 * Use `create(ContentItemSchema)` to create a new message.
 */
export const ContentItemSchema: GenMessage<ContentItem> = /*@__PURE__*/
  messageDesc(file_ContentItem, 1);

