// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ContentItem.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AnimatedArtwork, DataArtwork, RemoteArtwork } from "./Artwork_pb";
import { file_Artwork } from "./Artwork_pb";
import type { ContentItemMetadata } from "./ContentItemMetadata_pb";
import { file_ContentItemMetadata } from "./ContentItemMetadata_pb";
import type { LanguageOption } from "./LanguageOption_pb";
import { file_LanguageOption } from "./LanguageOption_pb";
import type { LyricsItem } from "./LyricsItem_pb";
import { file_LyricsItem } from "./LyricsItem_pb";
import type { TranscriptAlignment } from "./Transcript_pb";
import { file_Transcript } from "./Transcript_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ContentItem.proto.
 */
export const file_ContentItem: GenFile = /*@__PURE__*/
  fileDesc("ChFDb250ZW50SXRlbS5wcm90byKMAQoTTGFuZ3VhZ2VPcHRpb25Hcm91cBIbChNhbGxvd0VtcHR5U2VsZWN0aW9uGAEgASgIEi4KFWRlZmF1bHRMYW5ndWFnZU9wdGlvbhgCIAEoCzIPLkxhbmd1YWdlT3B0aW9uEigKD2xhbmd1YWdlT3B0aW9ucxgDIAMoCzIPLkxhbmd1YWdlT3B0aW9uIqsGCgtDb250ZW50SXRlbRISCgppZGVudGlmaWVyGAEgASgJEiYKCG1ldGFkYXRhGAIgASgLMhQuQ29udGVudEl0ZW1NZXRhZGF0YRITCgthcnR3b3JrRGF0YRgDIAEoDBIMCgRpbmZvGAQgASgJEjYKGGF2YWlsYWJsZUxhbmd1YWdlT3B0aW9ucxgFIAMoCzIULkxhbmd1YWdlT3B0aW9uR3JvdXASLwoWY3VycmVudExhbmd1YWdlT3B0aW9ucxgGIAMoCzIPLkxhbmd1YWdlT3B0aW9uEhsKBmx5cmljcxgHIAEoCzILLkx5cmljc0l0ZW0SHgoIc2VjdGlvbnMYCCADKAsyDC5Db250ZW50SXRlbRIYChBwYXJlbnRJZGVudGlmaWVyGAkgASgJEhoKEmFuY2VzdG9ySWRlbnRpZmllchgKIAEoCRIXCg9xdWV1ZUlkZW50aWZpZXIYCyABKAkSGQoRcmVxdWVzdElkZW50aWZpZXIYDCABKAkSGAoQYXJ0d29ya0RhdGFXaWR0aBgNIAEoBRIZChFhcnR3b3JrRGF0YUhlaWdodBgOIAEoBRInCh9hc3NvY2lhdGVkUGFydGljaXBhbnRJZGVudGlmaWVyGA8gASgJEh8KF2F2YWlsYWJsZUFydHdvcmtGb3JtYXRzGBAgAygJEiUKHWF2YWlsYWJsZVJlbW90ZUFydHdvcmtGb3JtYXRzGBEgAygJEiIKDGRhdGFBcnR3b3JrcxgSIAMoCzIMLkRhdGFBcnR3b3JrEiYKDnJlbW90ZUFydHdvcmtzGBMgAygLMg4uUmVtb3RlQXJ0d29yaxIyChR0cmFuc2NyaXB0QWxpZ25tZW50cxgUIAMoCzIULlRyYW5zY3JpcHRBbGlnbm1lbnQSJwofYXZhaWxhYmxlQW5pbWF0ZWRBcnR3b3JrRm9ybWF0cxgVIAMoCRIyChxhbmltYXRlZEFydHdvcmtQcmV2aWV3RnJhbWVzGBYgAygLMgwuRGF0YUFydHdvcmsSKgoQYW5pbWF0ZWRBcnR3b3JrcxgXIAMoCzIQLkFuaW1hdGVkQXJ0d29yaw", [file_Artwork, file_ContentItemMetadata, file_LanguageOption, file_LyricsItem, file_Transcript]);

/**
 * @generated from message LanguageOptionGroup
 */
export type LanguageOptionGroup = Message<"LanguageOptionGroup"> & {
  /**
   * @generated from field: optional bool allowEmptySelection = 1;
   */
  allowEmptySelection: boolean;

  /**
   * @generated from field: optional LanguageOption defaultLanguageOption = 2;
   */
  defaultLanguageOption?: LanguageOption;

  /**
   * @generated from field: repeated LanguageOption languageOptions = 3;
   */
  languageOptions: LanguageOption[];
};

/**
 * Describes the message LanguageOptionGroup.
 * Use `create(LanguageOptionGroupSchema)` to create a new message.
 */
export const LanguageOptionGroupSchema: GenMessage<LanguageOptionGroup> = /*@__PURE__*/
  messageDesc(file_ContentItem, 0);

/**
 * @generated from message ContentItem
 */
export type ContentItem = Message<"ContentItem"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional ContentItemMetadata metadata = 2;
   */
  metadata?: ContentItemMetadata;

  /**
   * @generated from field: optional bytes artworkData = 3;
   */
  artworkData: Uint8Array;

  /**
   * @generated from field: optional string info = 4;
   */
  info: string;

  /**
   * @generated from field: repeated LanguageOptionGroup availableLanguageOptions = 5;
   */
  availableLanguageOptions: LanguageOptionGroup[];

  /**
   * @generated from field: repeated LanguageOption currentLanguageOptions = 6;
   */
  currentLanguageOptions: LanguageOption[];

  /**
   * @generated from field: optional LyricsItem lyrics = 7;
   */
  lyrics?: LyricsItem;

  /**
   * @generated from field: repeated ContentItem sections = 8;
   */
  sections: ContentItem[];

  /**
   * @generated from field: optional string parentIdentifier = 9;
   */
  parentIdentifier: string;

  /**
   * @generated from field: optional string ancestorIdentifier = 10;
   */
  ancestorIdentifier: string;

  /**
   * @generated from field: optional string queueIdentifier = 11;
   */
  queueIdentifier: string;

  /**
   * @generated from field: optional string requestIdentifier = 12;
   */
  requestIdentifier: string;

  /**
   * @generated from field: optional int32 artworkDataWidth = 13;
   */
  artworkDataWidth: number;

  /**
   * @generated from field: optional int32 artworkDataHeight = 14;
   */
  artworkDataHeight: number;

  /**
   * @generated from field: optional string associatedParticipantIdentifier = 15;
   */
  associatedParticipantIdentifier: string;

  /**
   * @generated from field: repeated string availableArtworkFormats = 16;
   */
  availableArtworkFormats: string[];

  /**
   * @generated from field: repeated string availableRemoteArtworkFormats = 17;
   */
  availableRemoteArtworkFormats: string[];

  /**
   * @generated from field: repeated DataArtwork dataArtworks = 18;
   */
  dataArtworks: DataArtwork[];

  /**
   * @generated from field: repeated RemoteArtwork remoteArtworks = 19;
   */
  remoteArtworks: RemoteArtwork[];

  /**
   * @generated from field: repeated TranscriptAlignment transcriptAlignments = 20;
   */
  transcriptAlignments: TranscriptAlignment[];

  /**
   * @generated from field: repeated string availableAnimatedArtworkFormats = 21;
   */
  availableAnimatedArtworkFormats: string[];

  /**
   * @generated from field: repeated DataArtwork animatedArtworkPreviewFrames = 22;
   */
  animatedArtworkPreviewFrames: DataArtwork[];

  /**
   * @generated from field: repeated AnimatedArtwork animatedArtworks = 23;
   */
  animatedArtworks: AnimatedArtwork[];
};

/**
 * Describes the message ContentItem.
 * Use `create(ContentItemSchema)` to create a new message.
 */
export const ContentItemSchema: GenMessage<ContentItem> = /*@__PURE__*/
  messageDesc(file_ContentItem, 1);

