// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file CreateApplicationConnectionMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ApplicationConnectionContext, ApplicationConnectionRequestInfo } from "./ApplicationConnection_pb";
import { file_ApplicationConnection } from "./ApplicationConnection_pb";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file CreateApplicationConnectionMessage.proto.
 */
export const file_CreateApplicationConnectionMessage: GenFile = /*@__PURE__*/
  fileDesc("CihDcmVhdGVBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdlLnByb3RvIowBCiJDcmVhdGVBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdlEi4KB2NvbnRleHQYASABKAsyHS5BcHBsaWNhdGlvbkNvbm5lY3Rpb25Db250ZXh0EjYKC3JlcXVlc3RJbmZvGAIgASgLMiEuQXBwbGljYXRpb25Db25uZWN0aW9uUmVxdWVzdEluZm86hQEKImNyZWF0ZUFwcGxpY2F0aW9uQ29ubmVjdGlvbk1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYXyABKAsyIy5DcmVhdGVBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdlUiJjcmVhdGVBcHBsaWNhdGlvbkNvbm5lY3Rpb25NZXNzYWdl", [file_ApplicationConnection, file_ProtocolMessage]);

/**
 * @generated from message CreateApplicationConnectionMessage
 */
export type CreateApplicationConnectionMessage = Message<"CreateApplicationConnectionMessage"> & {
  /**
   * @generated from field: optional ApplicationConnectionContext context = 1;
   */
  context?: ApplicationConnectionContext;

  /**
   * @generated from field: optional ApplicationConnectionRequestInfo requestInfo = 2;
   */
  requestInfo?: ApplicationConnectionRequestInfo;
};

/**
 * Describes the message CreateApplicationConnectionMessage.
 * Use `create(CreateApplicationConnectionMessageSchema)` to create a new message.
 */
export const CreateApplicationConnectionMessageSchema: GenMessage<CreateApplicationConnectionMessage> = /*@__PURE__*/
  messageDesc(file_CreateApplicationConnectionMessage, 0);

/**
 * @generated from extension: optional CreateApplicationConnectionMessage createApplicationConnectionMessage = 95;
 */
export const createApplicationConnectionMessage: GenExtension<ProtocolMessage, CreateApplicationConnectionMessage> = /*@__PURE__*/
  extDesc(file_CreateApplicationConnectionMessage, 0);

