// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file CryptoPairingMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file CryptoPairingMessage.proto.
 */
export const file_CryptoPairingMessage: GenFile = /*@__PURE__*/
  fileDesc("ChpDcnlwdG9QYWlyaW5nTWVzc2FnZS5wcm90byJ8ChRDcnlwdG9QYWlyaW5nTWVzc2FnZRITCgtwYWlyaW5nRGF0YRgBIAEoDBIOCgZzdGF0dXMYAiABKAUSEgoKaXNSZXRyeWluZxgDIAEoCBIcChRpc1VzaW5nU3lzdGVtUGFpcmluZxgEIAEoCBINCgVzdGF0ZRgFIAEoBTpbChRjcnlwdG9QYWlyaW5nTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgnIAEoCzIVLkNyeXB0b1BhaXJpbmdNZXNzYWdlUhRjcnlwdG9QYWlyaW5nTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message CryptoPairingMessage
 */
export type CryptoPairingMessage = Message<"CryptoPairingMessage"> & {
  /**
   * Example: <00010006 0101>
   *
   * @generated from field: optional bytes pairingData = 1;
   */
  pairingData: Uint8Array;

  /**
   * Example: 0
   *
   * @generated from field: optional int32 status = 2;
   */
  status: number;

  /**
   * @generated from field: optional bool isRetrying = 3;
   */
  isRetrying: boolean;

  /**
   * @generated from field: optional bool isUsingSystemPairing = 4;
   */
  isUsingSystemPairing: boolean;

  /**
   * @generated from field: optional int32 state = 5;
   */
  state: number;
};

/**
 * Describes the message CryptoPairingMessage.
 * Use `create(CryptoPairingMessageSchema)` to create a new message.
 */
export const CryptoPairingMessageSchema: GenMessage<CryptoPairingMessage> = /*@__PURE__*/
  messageDesc(file_CryptoPairingMessage, 0);

/**
 * @generated from extension: optional CryptoPairingMessage cryptoPairingMessage = 39;
 */
export const cryptoPairingMessage: GenExtension<ProtocolMessage, CryptoPairingMessage> = /*@__PURE__*/
  extDesc(file_CryptoPairingMessage, 0);

