// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file DelegationServiceMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file DelegationServiceMessage.proto.
 */
export const file_DelegationServiceMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch5EZWxlZ2F0aW9uU2VydmljZU1lc3NhZ2UucHJvdG8ihgIKGERlbGVnYXRpb25TZXJ2aWNlTWVzc2FnZRI3ChZzdGFydERlbGVnYXRpb25SZXF1ZXN0GAEgASgLMhcuU3RhcnREZWxlZ2F0aW9uUmVxdWVzdBI5ChdzdGFydERlbGVnYXRpb25SZXNwb25zZRgCIAEoCzIYLlN0YXJ0RGVsZWdhdGlvblJlc3BvbnNlEjkKF2ZpbmlzaERlbGVnYXRpb25SZXF1ZXN0GAMgASgLMhguRmluaXNoRGVsZWdhdGlvblJlcXVlc3QSOwoYZmluaXNoRGVsZWdhdGlvblJlc3BvbnNlGAQgASgLMhkuRmluaXNoRGVsZWdhdGlvblJlc3BvbnNlIkMKFlN0YXJ0RGVsZWdhdGlvblJlcXVlc3QSEQoJc2VydmljZUlEGAEgASgNEhYKDmRlbGVnYXRpb25VVUlEGAIgASgJIkIKF1N0YXJ0RGVsZWdhdGlvblJlc3BvbnNlEhEKCXNlcnZpY2VJRBgBIAEoDRIUCgxyZXNwb25zZURhdGEYAiABKAwiQQoXRmluaXNoRGVsZWdhdGlvblJlcXVlc3QSEQoJc2VydmljZUlEGAEgASgNEhMKC3JlcXVlc3REYXRhGAIgASgMIj4KGEZpbmlzaERlbGVnYXRpb25SZXNwb25zZRIRCglzZXJ2aWNlSUQYASABKA0SDwoHc3VjY2VzcxgCIAEoCCIrChZQbGF5ZXJJbmZvQ29udGV4dFRva2VuEhEKCXRva2VuRGF0YRgBIAEoCSI/ChdQbGF5ZXJEZWxlZ2F0ZUluZm9Ub2tlbhIRCgl0b2tlbkRhdGEYASABKAkSEQoJc2VydmljZUlEGAIgASgNIkUKHVBsYXllckluZm9Db250ZXh0UmVxdWVzdFRva2VuEhEKCXRva2VuRGF0YRgBIAEoCRIRCglzZXJ2aWNlSUQYAiABKA0", [file_ProtocolMessage]);

/**
 * @generated from message DelegationServiceMessage
 */
export type DelegationServiceMessage = Message<"DelegationServiceMessage"> & {
  /**
   * @generated from field: optional StartDelegationRequest startDelegationRequest = 1;
   */
  startDelegationRequest?: StartDelegationRequest;

  /**
   * @generated from field: optional StartDelegationResponse startDelegationResponse = 2;
   */
  startDelegationResponse?: StartDelegationResponse;

  /**
   * @generated from field: optional FinishDelegationRequest finishDelegationRequest = 3;
   */
  finishDelegationRequest?: FinishDelegationRequest;

  /**
   * @generated from field: optional FinishDelegationResponse finishDelegationResponse = 4;
   */
  finishDelegationResponse?: FinishDelegationResponse;
};

/**
 * Describes the message DelegationServiceMessage.
 * Use `create(DelegationServiceMessageSchema)` to create a new message.
 */
export const DelegationServiceMessageSchema: GenMessage<DelegationServiceMessage> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 0);

/**
 * @generated from message StartDelegationRequest
 */
export type StartDelegationRequest = Message<"StartDelegationRequest"> & {
  /**
   * @generated from field: optional uint32 serviceID = 1;
   */
  serviceID: number;

  /**
   * @generated from field: optional string delegationUUID = 2;
   */
  delegationUUID: string;
};

/**
 * Describes the message StartDelegationRequest.
 * Use `create(StartDelegationRequestSchema)` to create a new message.
 */
export const StartDelegationRequestSchema: GenMessage<StartDelegationRequest> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 1);

/**
 * @generated from message StartDelegationResponse
 */
export type StartDelegationResponse = Message<"StartDelegationResponse"> & {
  /**
   * @generated from field: optional uint32 serviceID = 1;
   */
  serviceID: number;

  /**
   * @generated from field: optional bytes responseData = 2;
   */
  responseData: Uint8Array;
};

/**
 * Describes the message StartDelegationResponse.
 * Use `create(StartDelegationResponseSchema)` to create a new message.
 */
export const StartDelegationResponseSchema: GenMessage<StartDelegationResponse> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 2);

/**
 * @generated from message FinishDelegationRequest
 */
export type FinishDelegationRequest = Message<"FinishDelegationRequest"> & {
  /**
   * @generated from field: optional uint32 serviceID = 1;
   */
  serviceID: number;

  /**
   * @generated from field: optional bytes requestData = 2;
   */
  requestData: Uint8Array;
};

/**
 * Describes the message FinishDelegationRequest.
 * Use `create(FinishDelegationRequestSchema)` to create a new message.
 */
export const FinishDelegationRequestSchema: GenMessage<FinishDelegationRequest> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 3);

/**
 * @generated from message FinishDelegationResponse
 */
export type FinishDelegationResponse = Message<"FinishDelegationResponse"> & {
  /**
   * @generated from field: optional uint32 serviceID = 1;
   */
  serviceID: number;

  /**
   * @generated from field: optional bool success = 2;
   */
  success: boolean;
};

/**
 * Describes the message FinishDelegationResponse.
 * Use `create(FinishDelegationResponseSchema)` to create a new message.
 */
export const FinishDelegationResponseSchema: GenMessage<FinishDelegationResponse> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 4);

/**
 * @generated from message PlayerInfoContextToken
 */
export type PlayerInfoContextToken = Message<"PlayerInfoContextToken"> & {
  /**
   * @generated from field: optional string tokenData = 1;
   */
  tokenData: string;
};

/**
 * Describes the message PlayerInfoContextToken.
 * Use `create(PlayerInfoContextTokenSchema)` to create a new message.
 */
export const PlayerInfoContextTokenSchema: GenMessage<PlayerInfoContextToken> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 5);

/**
 * @generated from message PlayerDelegateInfoToken
 */
export type PlayerDelegateInfoToken = Message<"PlayerDelegateInfoToken"> & {
  /**
   * @generated from field: optional string tokenData = 1;
   */
  tokenData: string;

  /**
   * @generated from field: optional uint32 serviceID = 2;
   */
  serviceID: number;
};

/**
 * Describes the message PlayerDelegateInfoToken.
 * Use `create(PlayerDelegateInfoTokenSchema)` to create a new message.
 */
export const PlayerDelegateInfoTokenSchema: GenMessage<PlayerDelegateInfoToken> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 6);

/**
 * @generated from message PlayerInfoContextRequestToken
 */
export type PlayerInfoContextRequestToken = Message<"PlayerInfoContextRequestToken"> & {
  /**
   * @generated from field: optional string tokenData = 1;
   */
  tokenData: string;

  /**
   * @generated from field: optional uint32 serviceID = 2;
   */
  serviceID: number;
};

/**
 * Describes the message PlayerInfoContextRequestToken.
 * Use `create(PlayerInfoContextRequestTokenSchema)` to create a new message.
 */
export const PlayerInfoContextRequestTokenSchema: GenMessage<PlayerInfoContextRequestToken> = /*@__PURE__*/
  messageDesc(file_DelegationServiceMessage, 7);

