// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file Destination.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Destination.proto.
 */
export const file_Destination: GenFile = /*@__PURE__*/
  fileDesc("ChFEZXN0aW5hdGlvbi5wcm90byJzCgtEZXN0aW5hdGlvbhIfCgpwbGF5ZXJQYXRoGAEgASgLMgsuUGxheWVyUGF0aBIYChBvdXRwdXRDb250ZXh0VUlEGAIgASgJEhcKD291dHB1dERldmljZVVJRBgDIAEoCRIQCghlbmRwb2ludBgEIAEoCQ", [file_PlayerPath]);

/**
 * @generated from message Destination
 */
export type Destination = Message<"Destination"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional string outputContextUID = 2;
   */
  outputContextUID: string;

  /**
   * @generated from field: optional string outputDeviceUID = 3;
   */
  outputDeviceUID: string;

  /**
   * @generated from field: optional string endpoint = 4;
   */
  endpoint: string;
};

/**
 * Describes the message Destination.
 * Use `create(DestinationSchema)` to create a new message.
 */
export const DestinationSchema: GenMessage<Destination> = /*@__PURE__*/
  messageDesc(file_Destination, 0);

