// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file Dictionary.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Dictionary.proto.
 */
export const file_Dictionary: GenFile = /*@__PURE__*/
  fileDesc("ChBEaWN0aW9uYXJ5LnByb3RvIioKCkRpY3Rpb25hcnkSHAoFcGFpcnMYASADKAsyDS5LZXlWYWx1ZVBhaXIiMgoMS2V5VmFsdWVQYWlyEgsKA2tleRgBIAEoCRIVCgV2YWx1ZRgCIAEoCzIGLlZhbHVlItQBCgVWYWx1ZRITCgtzdHJpbmdWYWx1ZRgBIAEoCRISCgppbnQ2NFZhbHVlGAIgASgDEhIKCmZsb2F0VmFsdWUYAyABKAISEwoLZG91YmxlVmFsdWUYBCABKAESEQoJZGF0YVZhbHVlGAUgASgMEhEKCWJvb2xWYWx1ZRgGIAEoCBIRCglkYXRlVmFsdWUYByABKAkSGgoKYXJyYXlWYWx1ZRgIIAMoCzIGLlZhbHVlEiQKD2RpY3Rpb25hcnlWYWx1ZRgJIAEoCzILLkRpY3Rpb25hcnk");

/**
 * @generated from message Dictionary
 */
export type Dictionary = Message<"Dictionary"> & {
  /**
   * @generated from field: repeated KeyValuePair pairs = 1;
   */
  pairs: KeyValuePair[];
};

/**
 * Describes the message Dictionary.
 * Use `create(DictionarySchema)` to create a new message.
 */
export const DictionarySchema: GenMessage<Dictionary> = /*@__PURE__*/
  messageDesc(file_Dictionary, 0);

/**
 * @generated from message KeyValuePair
 */
export type KeyValuePair = Message<"KeyValuePair"> & {
  /**
   * @generated from field: optional string key = 1;
   */
  key: string;

  /**
   * @generated from field: optional Value value = 2;
   */
  value?: Value;
};

/**
 * Describes the message KeyValuePair.
 * Use `create(KeyValuePairSchema)` to create a new message.
 */
export const KeyValuePairSchema: GenMessage<KeyValuePair> = /*@__PURE__*/
  messageDesc(file_Dictionary, 1);

/**
 * @generated from message Value
 */
export type Value = Message<"Value"> & {
  /**
   * @generated from field: optional string stringValue = 1;
   */
  stringValue: string;

  /**
   * @generated from field: optional int64 int64Value = 2;
   */
  int64Value: bigint;

  /**
   * @generated from field: optional float floatValue = 3;
   */
  floatValue: number;

  /**
   * @generated from field: optional double doubleValue = 4;
   */
  doubleValue: number;

  /**
   * @generated from field: optional bytes dataValue = 5;
   */
  dataValue: Uint8Array;

  /**
   * @generated from field: optional bool boolValue = 6;
   */
  boolValue: boolean;

  /**
   * @generated from field: optional string dateValue = 7;
   */
  dateValue: string;

  /**
   * @generated from field: repeated Value arrayValue = 8;
   */
  arrayValue: Value[];

  /**
   * @generated from field: optional Dictionary dictionaryValue = 9;
   */
  dictionaryValue?: Dictionary;
};

/**
 * Describes the message Value.
 * Use `create(ValueSchema)` to create a new message.
 */
export const ValueSchema: GenMessage<Value> = /*@__PURE__*/
  messageDesc(file_Dictionary, 2);

