// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file DiscoverySessionConfiguration.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file DiscoverySessionConfiguration.proto.
 */
export const file_DiscoverySessionConfiguration: GenFile = /*@__PURE__*/
  fileDesc("CiNEaXNjb3ZlcnlTZXNzaW9uQ29uZmlndXJhdGlvbi5wcm90byL1AQodRGlzY292ZXJ5U2Vzc2lvbkNvbmZpZ3VyYXRpb24SEAoIZmVhdHVyZXMYASABKAMSFwoPb3V0cHV0RGV2aWNlVUlEGAIgASgJEhkKEXJvdXRpbmdDb250ZXh0VUlEGAMgASgJEhcKD3RhcmdldFNlc3Npb25JRBgEIAEoAxIaChJhbHdheXNBbGxvd1VwZGF0ZXMYBSABKAgSHgoWY2FjaGVkRGlzY292ZXJ5RW5hYmxlZBgGIAEoCBIYChBlbmFibGVUaHJvdHRsaW5nGAcgASgIEh8KF3BvcHVsYXRlc0V4dGVybmFsRGV2aWNlGAggASgI");

/**
 * @generated from message DiscoverySessionConfiguration
 */
export type DiscoverySessionConfiguration = Message<"DiscoverySessionConfiguration"> & {
  /**
   * @generated from field: optional int64 features = 1;
   */
  features: bigint;

  /**
   * @generated from field: optional string outputDeviceUID = 2;
   */
  outputDeviceUID: string;

  /**
   * @generated from field: optional string routingContextUID = 3;
   */
  routingContextUID: string;

  /**
   * @generated from field: optional int64 targetSessionID = 4;
   */
  targetSessionID: bigint;

  /**
   * @generated from field: optional bool alwaysAllowUpdates = 5;
   */
  alwaysAllowUpdates: boolean;

  /**
   * @generated from field: optional bool cachedDiscoveryEnabled = 6;
   */
  cachedDiscoveryEnabled: boolean;

  /**
   * @generated from field: optional bool enableThrottling = 7;
   */
  enableThrottling: boolean;

  /**
   * @generated from field: optional bool populatesExternalDevice = 8;
   */
  populatesExternalDevice: boolean;
};

/**
 * Describes the message DiscoverySessionConfiguration.
 * Use `create(DiscoverySessionConfigurationSchema)` to create a new message.
 */
export const DiscoverySessionConfigurationSchema: GenMessage<DiscoverySessionConfiguration> = /*@__PURE__*/
  messageDesc(file_DiscoverySessionConfiguration, 0);

