// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file Error.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Dictionary } from "./Dictionary_pb";
import { file_Dictionary } from "./Dictionary_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Error.proto.
 */
export const file_Error: GenFile = /*@__PURE__*/
  fileDesc("CgtFcnJvci5wcm90byK6AQoFRXJyb3ISDgoGZG9tYWluGAEgASgJEgwKBGNvZGUYAiABKAUSHAoUbG9jYWxpemVkRGVzY3JpcHRpb24YAyABKAkSHgoWbG9jYWxpemVkRmFpbHVyZVJlYXNvbhgEIAEoCRIgChB1bmRlcmx5aW5nRXJyb3JzGAUgAygLMgYuRXJyb3ISFAoMZGVidWdNZXNzYWdlGAYgASgJEh0KCHVzZXJJbmZvGGQgASgLMgsuRGljdGlvbmFyeQ", [file_Dictionary]);

/**
 * @generated from message Error
 */
export type Error = Message<"Error"> & {
  /**
   * @generated from field: optional string domain = 1;
   */
  domain: string;

  /**
   * @generated from field: optional int32 code = 2;
   */
  code: number;

  /**
   * @generated from field: optional string localizedDescription = 3;
   */
  localizedDescription: string;

  /**
   * @generated from field: optional string localizedFailureReason = 4;
   */
  localizedFailureReason: string;

  /**
   * @generated from field: repeated Error underlyingErrors = 5;
   */
  underlyingErrors: Error[];

  /**
   * @generated from field: optional string debugMessage = 6;
   */
  debugMessage: string;

  /**
   * @generated from field: optional Dictionary userInfo = 100;
   */
  userInfo?: Dictionary;
};

/**
 * Describes the message Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_Error, 0);

