// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GameControllerDigitizer.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GameControllerDigitizer.proto.
 */
export const file_GameControllerDigitizer: GenFile = /*@__PURE__*/
  fileDesc("Ch1HYW1lQ29udHJvbGxlckRpZ2l0aXplci5wcm90byJVChdHYW1lQ29udHJvbGxlckRpZ2l0aXplchIJCgF4GAEgASgBEgkKAXkYAiABKAESEQoJdG91Y2hEb3duGAMgASgIEhEKCXRpbWVzdGFtcBgEIAEoBA");

/**
 * @generated from message GameControllerDigitizer
 */
export type GameControllerDigitizer = Message<"GameControllerDigitizer"> & {
  /**
   * @generated from field: optional double x = 1;
   */
  x: number;

  /**
   * @generated from field: optional double y = 2;
   */
  y: number;

  /**
   * @generated from field: optional bool touchDown = 3;
   */
  touchDown: boolean;

  /**
   * @generated from field: optional uint64 timestamp = 4;
   */
  timestamp: bigint;
};

/**
 * Describes the message GameControllerDigitizer.
 * Use `create(GameControllerDigitizerSchema)` to create a new message.
 */
export const GameControllerDigitizerSchema: GenMessage<GameControllerDigitizer> = /*@__PURE__*/
  messageDesc(file_GameControllerDigitizer, 0);

