// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GameControllerButtons.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GameControllerButtons.proto.
 */
export const file_GameControllerButtons: GenFile = /*@__PURE__*/
  fileDesc("ChtHYW1lQ29udHJvbGxlckJ1dHRvbnMucHJvdG8irgIKFUdhbWVDb250cm9sbGVyQnV0dG9ucxINCgVkUGFkWBgBIAEoAhINCgVkUGFkWRgCIAEoAhIJCgFhGAMgASgCEgkKAWIYBCABKAISCQoBeBgFIAEoAhIJCgF5GAYgASgCEhQKDGxlZnRTaG91bGRlchgHIAEoAhIVCg1yaWdodFNob3VsZGVyGAggASgCEhcKD2xlZnRUaHVtYnN0aWNrWBgJIAEoAhIXCg9sZWZ0VGh1bWJzdGlja1kYCiABKAISGAoQcmlnaHRUaHVtYnN0aWNrWBgLIAEoAhIYChByaWdodFRodW1ic3RpY2tZGAwgASgCEhMKC2xlZnRUcmlnZ2VyGA0gASgCEhQKDHJpZ2h0VHJpZ2dlchgOIAEoAhINCgVwYXVzZRgPIAEoAg");

/**
 * @generated from message GameControllerButtons
 */
export type GameControllerButtons = Message<"GameControllerButtons"> & {
  /**
   * @generated from field: optional float dPadX = 1;
   */
  dPadX: number;

  /**
   * @generated from field: optional float dPadY = 2;
   */
  dPadY: number;

  /**
   * @generated from field: optional float a = 3;
   */
  a: number;

  /**
   * @generated from field: optional float b = 4;
   */
  b: number;

  /**
   * @generated from field: optional float x = 5;
   */
  x: number;

  /**
   * @generated from field: optional float y = 6;
   */
  y: number;

  /**
   * @generated from field: optional float leftShoulder = 7;
   */
  leftShoulder: number;

  /**
   * @generated from field: optional float rightShoulder = 8;
   */
  rightShoulder: number;

  /**
   * @generated from field: optional float leftThumbstickX = 9;
   */
  leftThumbstickX: number;

  /**
   * @generated from field: optional float leftThumbstickY = 10;
   */
  leftThumbstickY: number;

  /**
   * @generated from field: optional float rightThumbstickX = 11;
   */
  rightThumbstickX: number;

  /**
   * @generated from field: optional float rightThumbstickY = 12;
   */
  rightThumbstickY: number;

  /**
   * @generated from field: optional float leftTrigger = 13;
   */
  leftTrigger: number;

  /**
   * @generated from field: optional float rightTrigger = 14;
   */
  rightTrigger: number;

  /**
   * @generated from field: optional float pause = 15;
   */
  pause: number;
};

/**
 * Describes the message GameControllerButtons.
 * Use `create(GameControllerButtonsSchema)` to create a new message.
 */
export const GameControllerButtonsSchema: GenMessage<GameControllerButtons> = /*@__PURE__*/
  messageDesc(file_GameControllerButtons, 0);

