// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GameControllerMotion.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GameControllerMotion.proto.
 */
export const file_GameControllerMotion: GenFile = /*@__PURE__*/
  fileDesc("ChpHYW1lQ29udHJvbGxlck1vdGlvbi5wcm90byJWChpHYW1lQ29udHJvbGxlckFjY2VsZXJhdGlvbhIMCgRkYXRhGAEgASgMEgkKAXgYAiABKAISCQoBeRgDIAEoAhIJCgF6GAQgASgCEgkKAXcYBSABKAIi2QEKFEdhbWVDb250cm9sbGVyTW90aW9uEiwKB2dyYXZpdHkYASABKAsyGy5HYW1lQ29udHJvbGxlckFjY2VsZXJhdGlvbhI1ChB1c2VyQWNjZWxlcmF0aW9uGAIgASgLMhsuR2FtZUNvbnRyb2xsZXJBY2NlbGVyYXRpb24SLQoIYXR0aXR1ZGUYAyABKAsyGy5HYW1lQ29udHJvbGxlckFjY2VsZXJhdGlvbhItCghyb3RhdGlvbhgEIAEoCzIbLkdhbWVDb250cm9sbGVyQWNjZWxlcmF0aW9u");

/**
 * @generated from message GameControllerAcceleration
 */
export type GameControllerAcceleration = Message<"GameControllerAcceleration"> & {
  /**
   * @generated from field: optional bytes data = 1;
   */
  data: Uint8Array;

  /**
   * @generated from field: optional float x = 2;
   */
  x: number;

  /**
   * @generated from field: optional float y = 3;
   */
  y: number;

  /**
   * @generated from field: optional float z = 4;
   */
  z: number;

  /**
   * @generated from field: optional float w = 5;
   */
  w: number;
};

/**
 * Describes the message GameControllerAcceleration.
 * Use `create(GameControllerAccelerationSchema)` to create a new message.
 */
export const GameControllerAccelerationSchema: GenMessage<GameControllerAcceleration> = /*@__PURE__*/
  messageDesc(file_GameControllerMotion, 0);

/**
 * @generated from message GameControllerMotion
 */
export type GameControllerMotion = Message<"GameControllerMotion"> & {
  /**
   * @generated from field: optional GameControllerAcceleration gravity = 1;
   */
  gravity?: GameControllerAcceleration;

  /**
   * @generated from field: optional GameControllerAcceleration userAcceleration = 2;
   */
  userAcceleration?: GameControllerAcceleration;

  /**
   * @generated from field: optional GameControllerAcceleration attitude = 3;
   */
  attitude?: GameControllerAcceleration;

  /**
   * @generated from field: optional GameControllerAcceleration rotation = 4;
   */
  rotation?: GameControllerAcceleration;
};

/**
 * Describes the message GameControllerMotion.
 * Use `create(GameControllerMotionSchema)` to create a new message.
 */
export const GameControllerMotionSchema: GenMessage<GameControllerMotion> = /*@__PURE__*/
  messageDesc(file_GameControllerMotion, 1);

