// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GameControllerMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { GameControllerButtons } from "./GameControllerButtons_pb";
import { file_GameControllerButtons } from "./GameControllerButtons_pb";
import type { GameControllerDigitizer } from "./GameControllerDigitizer_pb";
import { file_GameControllerDigitizer } from "./GameControllerDigitizer_pb";
import type { GameControllerMotion } from "./GameControllerMotion_pb";
import { file_GameControllerMotion } from "./GameControllerMotion_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GameControllerMessage.proto.
 */
export const file_GameControllerMessage: GenFile = /*@__PURE__*/
  fileDesc("ChtHYW1lQ29udHJvbGxlck1lc3NhZ2UucHJvdG8iqgEKFUdhbWVDb250cm9sbGVyTWVzc2FnZRIUCgxjb250cm9sbGVySUQYASABKAQSJQoGbW90aW9uGAIgASgLMhUuR2FtZUNvbnRyb2xsZXJNb3Rpb24SJwoHYnV0dG9ucxgDIAEoCzIWLkdhbWVDb250cm9sbGVyQnV0dG9ucxIrCglkaWdpdGl6ZXIYBCABKAsyGC5HYW1lQ29udHJvbGxlckRpZ2l0aXplcjpeChVnYW1lQ29udHJvbGxlck1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYFyABKAsyFi5HYW1lQ29udHJvbGxlck1lc3NhZ2VSFWdhbWVDb250cm9sbGVyTWVzc2FnZQ", [file_ProtocolMessage, file_GameControllerButtons, file_GameControllerDigitizer, file_GameControllerMotion]);

/**
 * @generated from message GameControllerMessage
 */
export type GameControllerMessage = Message<"GameControllerMessage"> & {
  /**
   * @generated from field: optional uint64 controllerID = 1;
   */
  controllerID: bigint;

  /**
   * @generated from field: optional GameControllerMotion motion = 2;
   */
  motion?: GameControllerMotion;

  /**
   * @generated from field: optional GameControllerButtons buttons = 3;
   */
  buttons?: GameControllerButtons;

  /**
   * @generated from field: optional GameControllerDigitizer digitizer = 4;
   */
  digitizer?: GameControllerDigitizer;
};

/**
 * Describes the message GameControllerMessage.
 * Use `create(GameControllerMessageSchema)` to create a new message.
 */
export const GameControllerMessageSchema: GenMessage<GameControllerMessage> = /*@__PURE__*/
  messageDesc(file_GameControllerMessage, 0);

/**
 * @generated from extension: optional GameControllerMessage gameControllerMessage = 23;
 */
export const gameControllerMessage: GenExtension<ProtocolMessage, GameControllerMessage> = /*@__PURE__*/
  extDesc(file_GameControllerMessage, 0);

