// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GameControllerPropertiesMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GameControllerPropertiesMessage.proto.
 */
export const file_GameControllerPropertiesMessage: GenFile = /*@__PURE__*/
  fileDesc("CiVHYW1lQ29udHJvbGxlclByb3BlcnRpZXNNZXNzYWdlLnByb3RvIowBChhHYW1lQ29udHJvbGxlclByb3BlcnRpZXMSEwoLcGxheWVySW5kZXgYASABKA0SEgoKdmVuZG9yTmFtZRgCIAEoCRIWCg5idXR0b25BVXBEZWxheRgDIAEoBRIPCgdwcm9maWxlGAQgASgFEh4KFnN1cHBvcnRzRXh0ZW5kZWRNb3Rpb24YBSABKAgiZgofR2FtZUNvbnRyb2xsZXJQcm9wZXJ0aWVzTWVzc2FnZRIUCgxjb250cm9sbGVySUQYASABKAQSLQoKcHJvcGVydGllcxgCIAEoCzIZLkdhbWVDb250cm9sbGVyUHJvcGVydGllczp8Ch9nYW1lQ29udHJvbGxlclByb3BlcnRpZXNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGCggASgLMiAuR2FtZUNvbnRyb2xsZXJQcm9wZXJ0aWVzTWVzc2FnZVIfZ2FtZUNvbnRyb2xsZXJQcm9wZXJ0aWVzTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message GameControllerProperties
 */
export type GameControllerProperties = Message<"GameControllerProperties"> & {
  /**
   * @generated from field: optional uint32 playerIndex = 1;
   */
  playerIndex: number;

  /**
   * @generated from field: optional string vendorName = 2;
   */
  vendorName: string;

  /**
   * @generated from field: optional int32 buttonAUpDelay = 3;
   */
  buttonAUpDelay: number;

  /**
   * @generated from field: optional int32 profile = 4;
   */
  profile: number;

  /**
   * @generated from field: optional bool supportsExtendedMotion = 5;
   */
  supportsExtendedMotion: boolean;
};

/**
 * Describes the message GameControllerProperties.
 * Use `create(GameControllerPropertiesSchema)` to create a new message.
 */
export const GameControllerPropertiesSchema: GenMessage<GameControllerProperties> = /*@__PURE__*/
  messageDesc(file_GameControllerPropertiesMessage, 0);

/**
 * @generated from message GameControllerPropertiesMessage
 */
export type GameControllerPropertiesMessage = Message<"GameControllerPropertiesMessage"> & {
  /**
   * @generated from field: optional uint64 controllerID = 1;
   */
  controllerID: bigint;

  /**
   * @generated from field: optional GameControllerProperties properties = 2;
   */
  properties?: GameControllerProperties;
};

/**
 * Describes the message GameControllerPropertiesMessage.
 * Use `create(GameControllerPropertiesMessageSchema)` to create a new message.
 */
export const GameControllerPropertiesMessageSchema: GenMessage<GameControllerPropertiesMessage> = /*@__PURE__*/
  messageDesc(file_GameControllerPropertiesMessage, 1);

/**
 * @generated from extension: optional GameControllerPropertiesMessage gameControllerPropertiesMessage = 40;
 */
export const gameControllerPropertiesMessage: GenExtension<ProtocolMessage, GameControllerPropertiesMessage> = /*@__PURE__*/
  extDesc(file_GameControllerPropertiesMessage, 0);

