// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file GenericMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GenericMessage.proto.
 */
export const file_GenericMessage: GenFile = /*@__PURE__*/
  fileDesc("ChRHZW5lcmljTWVzc2FnZS5wcm90byIsCg5HZW5lcmljTWVzc2FnZRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAw6SQoOZ2VuZXJpY01lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYLiABKAsyDy5HZW5lcmljTWVzc2FnZVIOZ2VuZXJpY01lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message GenericMessage
 */
export type GenericMessage = Message<"GenericMessage"> & {
  /**
   * @generated from field: optional string key = 1;
   */
  key: string;

  /**
   * @generated from field: optional bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message GenericMessage.
 * Use `create(GenericMessageSchema)` to create a new message.
 */
export const GenericMessageSchema: GenMessage<GenericMessage> = /*@__PURE__*/
  messageDesc(file_GenericMessage, 0);

/**
 * @generated from extension: optional GenericMessage genericMessage = 46;
 */
export const genericMessage: GenExtension<ProtocolMessage, GenericMessage> = /*@__PURE__*/
  extDesc(file_GenericMessage, 0);

