// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GetStateMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GetStateMessage.proto.
 */
export const file_GetStateMessage: GenFile = /*@__PURE__*/
  fileDesc("ChVHZXRTdGF0ZU1lc3NhZ2UucHJvdG8iEQoPR2V0U3RhdGVNZXNzYWdlOkwKD2dldFN0YXRlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgIIAEoCzIQLkdldFN0YXRlTWVzc2FnZVIPZ2V0U3RhdGVNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message GetStateMessage
 */
export type GetStateMessage = Message<"GetStateMessage"> & {
};

/**
 * Describes the message GetStateMessage.
 * Use `create(GetStateMessageSchema)` to create a new message.
 */
export const GetStateMessageSchema: GenMessage<GetStateMessage> = /*@__PURE__*/
  messageDesc(file_GetStateMessage, 0);

/**
 * @generated from extension: optional GetStateMessage getStateMessage = 8;
 */
export const getStateMessage: GenExtension<ProtocolMessage, GetStateMessage> = /*@__PURE__*/
  extDesc(file_GetStateMessage, 0);

