// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GetVolumeControlCapabilitiesMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GetVolumeControlCapabilitiesMessage.proto.
 */
export const file_GetVolumeControlCapabilitiesMessage: GenFile = /*@__PURE__*/
  fileDesc("CilHZXRWb2x1bWVDb250cm9sQ2FwYWJpbGl0aWVzTWVzc2FnZS5wcm90byI+CiNHZXRWb2x1bWVDb250cm9sQ2FwYWJpbGl0aWVzTWVzc2FnZRIXCg9vdXRwdXREZXZpY2VVSUQYASABKAk6iAEKI2dldFZvbHVtZUNvbnRyb2xDYXBhYmlsaXRpZXNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGEIgASgLMiQuR2V0Vm9sdW1lQ29udHJvbENhcGFiaWxpdGllc01lc3NhZ2VSI2dldFZvbHVtZUNvbnRyb2xDYXBhYmlsaXRpZXNNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message GetVolumeControlCapabilitiesMessage
 */
export type GetVolumeControlCapabilitiesMessage = Message<"GetVolumeControlCapabilitiesMessage"> & {
  /**
   * @generated from field: optional string outputDeviceUID = 1;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message GetVolumeControlCapabilitiesMessage.
 * Use `create(GetVolumeControlCapabilitiesMessageSchema)` to create a new message.
 */
export const GetVolumeControlCapabilitiesMessageSchema: GenMessage<GetVolumeControlCapabilitiesMessage> = /*@__PURE__*/
  messageDesc(file_GetVolumeControlCapabilitiesMessage, 0);

/**
 * @generated from extension: optional GetVolumeControlCapabilitiesMessage getVolumeControlCapabilitiesMessage = 66;
 */
export const getVolumeControlCapabilitiesMessage: GenExtension<ProtocolMessage, GetVolumeControlCapabilitiesMessage> = /*@__PURE__*/
  extDesc(file_GetVolumeControlCapabilitiesMessage, 0);

