// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file GetVolumeMutedMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GetVolumeMutedMessage.proto.
 */
export const file_GetVolumeMutedMessage: GenFile = /*@__PURE__*/
  fileDesc("ChtHZXRWb2x1bWVNdXRlZE1lc3NhZ2UucHJvdG8iMAoVR2V0Vm9sdW1lTXV0ZWRNZXNzYWdlEhcKD291dHB1dERldmljZVVJRBgBIAEoCTpeChVnZXRWb2x1bWVNdXRlZE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYYiABKAsyFi5HZXRWb2x1bWVNdXRlZE1lc3NhZ2VSFWdldFZvbHVtZU11dGVkTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message GetVolumeMutedMessage
 */
export type GetVolumeMutedMessage = Message<"GetVolumeMutedMessage"> & {
  /**
   * @generated from field: optional string outputDeviceUID = 1;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message GetVolumeMutedMessage.
 * Use `create(GetVolumeMutedMessageSchema)` to create a new message.
 */
export const GetVolumeMutedMessageSchema: GenMessage<GetVolumeMutedMessage> = /*@__PURE__*/
  messageDesc(file_GetVolumeMutedMessage, 0);

/**
 * @generated from extension: optional GetVolumeMutedMessage getVolumeMutedMessage = 98;
 */
export const getVolumeMutedMessage: GenExtension<ProtocolMessage, GetVolumeMutedMessage> = /*@__PURE__*/
  extDesc(file_GetVolumeMutedMessage, 0);

