// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file GetVolumeResultMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GetVolumeResultMessage.proto.
 */
export const file_GetVolumeResultMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxHZXRWb2x1bWVSZXN1bHRNZXNzYWdlLnByb3RvIigKFkdldFZvbHVtZVJlc3VsdE1lc3NhZ2USDgoGdm9sdW1lGAEgASgCOmEKFmdldFZvbHVtZVJlc3VsdE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYNiABKAsyFy5HZXRWb2x1bWVSZXN1bHRNZXNzYWdlUhZnZXRWb2x1bWVSZXN1bHRNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message GetVolumeResultMessage
 */
export type GetVolumeResultMessage = Message<"GetVolumeResultMessage"> & {
  /**
   * @generated from field: optional float volume = 1;
   */
  volume: number;
};

/**
 * Describes the message GetVolumeResultMessage.
 * Use `create(GetVolumeResultMessageSchema)` to create a new message.
 */
export const GetVolumeResultMessageSchema: GenMessage<GetVolumeResultMessage> = /*@__PURE__*/
  messageDesc(file_GetVolumeResultMessage, 0);

/**
 * @generated from extension: optional GetVolumeResultMessage getVolumeResultMessage = 54;
 */
export const getVolumeResultMessage: GenExtension<ProtocolMessage, GetVolumeResultMessage> = /*@__PURE__*/
  extDesc(file_GetVolumeResultMessage, 0);

