// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionIdentityShareMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { UserIdentity } from "./UserIdentity_pb";
import { file_UserIdentity } from "./UserIdentity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionIdentityShareMessage.proto.
 */
export const file_GroupSessionIdentityShareMessage: GenFile = /*@__PURE__*/
  fileDesc("CiZHcm91cFNlc3Npb25JZGVudGl0eVNoYXJlTWVzc2FnZS5wcm90byJDCiBHcm91cFNlc3Npb25JZGVudGl0eVNoYXJlTWVzc2FnZRIfCghpZGVudGl0eRgBIAEoCzINLlVzZXJJZGVudGl0eTp/CiBncm91cFNlc3Npb25JZGVudGl0eVNoYXJlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhqIAEoCzIhLkdyb3VwU2Vzc2lvbklkZW50aXR5U2hhcmVNZXNzYWdlUiBncm91cFNlc3Npb25JZGVudGl0eVNoYXJlTWVzc2FnZQ", [file_ProtocolMessage, file_UserIdentity]);

/**
 * @generated from message GroupSessionIdentityShareMessage
 */
export type GroupSessionIdentityShareMessage = Message<"GroupSessionIdentityShareMessage"> & {
  /**
   * @generated from field: optional UserIdentity identity = 1;
   */
  identity?: UserIdentity;
};

/**
 * Describes the message GroupSessionIdentityShareMessage.
 * Use `create(GroupSessionIdentityShareMessageSchema)` to create a new message.
 */
export const GroupSessionIdentityShareMessageSchema: GenMessage<GroupSessionIdentityShareMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionIdentityShareMessage, 0);

/**
 * @generated from extension: optional GroupSessionIdentityShareMessage groupSessionIdentityShareMessage = 106;
 */
export const groupSessionIdentityShareMessage: GenExtension<ProtocolMessage, GroupSessionIdentityShareMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionIdentityShareMessage, 0);

