// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionErrorReplyMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionErrorReplyMessage.proto.
 */
export const file_GroupSessionErrorReplyMessage: GenFile = /*@__PURE__*/
  fileDesc("CiNHcm91cFNlc3Npb25FcnJvclJlcGx5TWVzc2FnZS5wcm90byI1Ch1Hcm91cFNlc3Npb25FcnJvclJlcGx5TWVzc2FnZRIUCgxlcnJvck1lc3NhZ2UYASABKAk6dgodZ3JvdXBTZXNzaW9uRXJyb3JSZXBseU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYbiABKAsyHi5Hcm91cFNlc3Npb25FcnJvclJlcGx5TWVzc2FnZVIdZ3JvdXBTZXNzaW9uRXJyb3JSZXBseU1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message GroupSessionErrorReplyMessage
 */
export type GroupSessionErrorReplyMessage = Message<"GroupSessionErrorReplyMessage"> & {
  /**
   * @generated from field: optional string errorMessage = 1;
   */
  errorMessage: string;
};

/**
 * Describes the message GroupSessionErrorReplyMessage.
 * Use `create(GroupSessionErrorReplyMessageSchema)` to create a new message.
 */
export const GroupSessionErrorReplyMessageSchema: GenMessage<GroupSessionErrorReplyMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionErrorReplyMessage, 0);

/**
 * @generated from extension: optional GroupSessionErrorReplyMessage groupSessionErrorReplyMessage = 110;
 */
export const groupSessionErrorReplyMessage: GenExtension<ProtocolMessage, GroupSessionErrorReplyMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionErrorReplyMessage, 0);

