// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionFastSyncMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionFastSyncMessage.proto.
 */
export const file_GroupSessionFastSyncMessage: GenFile = /*@__PURE__*/
  fileDesc("CiFHcm91cFNlc3Npb25GYXN0U3luY01lc3NhZ2UucHJvdG8iQwobR3JvdXBTZXNzaW9uRmFzdFN5bmNNZXNzYWdlEhMKC21lc3NhZ2VUeXBlGAEgASgFEg8KB3BheWxvYWQYAiABKAw6cAobZ3JvdXBTZXNzaW9uRmFzdFN5bmNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGGkgASgLMhwuR3JvdXBTZXNzaW9uRmFzdFN5bmNNZXNzYWdlUhtncm91cFNlc3Npb25GYXN0U3luY01lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message GroupSessionFastSyncMessage
 */
export type GroupSessionFastSyncMessage = Message<"GroupSessionFastSyncMessage"> & {
  /**
   * @generated from field: optional int32 messageType = 1;
   */
  messageType: number;

  /**
   * @generated from field: optional bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message GroupSessionFastSyncMessage.
 * Use `create(GroupSessionFastSyncMessageSchema)` to create a new message.
 */
export const GroupSessionFastSyncMessageSchema: GenMessage<GroupSessionFastSyncMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionFastSyncMessage, 0);

/**
 * @generated from extension: optional GroupSessionFastSyncMessage groupSessionFastSyncMessage = 105;
 */
export const groupSessionFastSyncMessage: GenExtension<ProtocolMessage, GroupSessionFastSyncMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionFastSyncMessage, 0);

