// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionLeaderDiscoveryMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionLeaderDiscoveryMessage.proto.
 */
export const file_GroupSessionLeaderDiscoveryMessage: GenFile = /*@__PURE__*/
  fileDesc("CihHcm91cFNlc3Npb25MZWFkZXJEaXNjb3ZlcnlNZXNzYWdlLnByb3RvIjcKIkdyb3VwU2Vzc2lvbkxlYWRlckRpc2NvdmVyeU1lc3NhZ2USEQoJc2lnbmF0dXJlGAEgASgMOoUBCiJncm91cFNlc3Npb25MZWFkZXJEaXNjb3ZlcnlNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGGwgASgLMiMuR3JvdXBTZXNzaW9uTGVhZGVyRGlzY292ZXJ5TWVzc2FnZVIiZ3JvdXBTZXNzaW9uTGVhZGVyRGlzY292ZXJ5TWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message GroupSessionLeaderDiscoveryMessage
 */
export type GroupSessionLeaderDiscoveryMessage = Message<"GroupSessionLeaderDiscoveryMessage"> & {
  /**
   * @generated from field: optional bytes signature = 1;
   */
  signature: Uint8Array;
};

/**
 * Describes the message GroupSessionLeaderDiscoveryMessage.
 * Use `create(GroupSessionLeaderDiscoveryMessageSchema)` to create a new message.
 */
export const GroupSessionLeaderDiscoveryMessageSchema: GenMessage<GroupSessionLeaderDiscoveryMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionLeaderDiscoveryMessage, 0);

/**
 * @generated from extension: optional GroupSessionLeaderDiscoveryMessage groupSessionLeaderDiscoveryMessage = 108;
 */
export const groupSessionLeaderDiscoveryMessage: GenExtension<ProtocolMessage, GroupSessionLeaderDiscoveryMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionLeaderDiscoveryMessage, 0);

