// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionIdentityShareReplyMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GroupSessionParticipant } from "./GroupSession_pb";
import { file_GroupSession } from "./GroupSession_pb";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionIdentityShareReplyMessage.proto.
 */
export const file_GroupSessionIdentityShareReplyMessage: GenFile = /*@__PURE__*/
  fileDesc("CitHcm91cFNlc3Npb25JZGVudGl0eVNoYXJlUmVwbHlNZXNzYWdlLnByb3RvIpABCiVHcm91cFNlc3Npb25JZGVudGl0eVNoYXJlUmVwbHlNZXNzYWdlEjMKEWxlYWRlclBhcnRpY2lwYW50GAEgASgLMhguR3JvdXBTZXNzaW9uUGFydGljaXBhbnQSMgoQbG9jYWxQYXJ0aWNpcGFudBgCIAEoCzIYLkdyb3VwU2Vzc2lvblBhcnRpY2lwYW50Oo4BCiVncm91cFNlc3Npb25JZGVudGl0eVNoYXJlUmVwbHlNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGGsgASgLMiYuR3JvdXBTZXNzaW9uSWRlbnRpdHlTaGFyZVJlcGx5TWVzc2FnZVIlZ3JvdXBTZXNzaW9uSWRlbnRpdHlTaGFyZVJlcGx5TWVzc2FnZQ", [file_GroupSession, file_ProtocolMessage]);

/**
 * @generated from message GroupSessionIdentityShareReplyMessage
 */
export type GroupSessionIdentityShareReplyMessage = Message<"GroupSessionIdentityShareReplyMessage"> & {
  /**
   * @generated from field: optional GroupSessionParticipant leaderParticipant = 1;
   */
  leaderParticipant?: GroupSessionParticipant;

  /**
   * @generated from field: optional GroupSessionParticipant localParticipant = 2;
   */
  localParticipant?: GroupSessionParticipant;
};

/**
 * Describes the message GroupSessionIdentityShareReplyMessage.
 * Use `create(GroupSessionIdentityShareReplyMessageSchema)` to create a new message.
 */
export const GroupSessionIdentityShareReplyMessageSchema: GenMessage<GroupSessionIdentityShareReplyMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionIdentityShareReplyMessage, 0);

/**
 * @generated from extension: optional GroupSessionIdentityShareReplyMessage groupSessionIdentityShareReplyMessage = 107;
 */
export const groupSessionIdentityShareReplyMessage: GenExtension<ProtocolMessage, GroupSessionIdentityShareReplyMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionIdentityShareReplyMessage, 0);

