// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSession.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GroupSessionRouteType_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { RequestDetails } from "./RequestDetails_pb";
import { file_RequestDetails } from "./RequestDetails_pb";
import type { UserIdentity } from "./UserIdentity_pb";
import { file_UserIdentity } from "./UserIdentity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSession.proto.
 */
export const file_GroupSession: GenFile = /*@__PURE__*/
  fileDesc("ChJHcm91cFNlc3Npb24ucHJvdG8itwEKEEdyb3VwU2Vzc2lvbkluZm8SEgoKaWRlbnRpZmllchgBIAEoCRIXCg9ob3N0RGlzcGxheU5hbWUYAiABKAkSIQoZZXF1aXZhbGVudE1lZGlhSWRlbnRpZmllchgDIAEoCRIuCglyb3V0ZVR5cGUYBCABKA4yGy5Hcm91cFNlc3Npb25Sb3V0ZVR5cGUuRW51bRIOCgZob3N0ZWQYBSABKAgSEwoLcGxhY2Vob2xkZXIYBiABKAgi1QEKEUdyb3VwU2Vzc2lvblRva2VuEhkKEXNlc3Npb25JZGVudGlmaWVyGAEgASgJEhMKC2Rpc3BsYXlOYW1lGAIgASgJEiEKGWVxdWl2YWxlbnRNZWRpYUlkZW50aWZpZXIYAyABKAkSLgoJcm91dGVUeXBlGAQgASgOMhsuR3JvdXBTZXNzaW9uUm91dGVUeXBlLkVudW0SFAoMc2hhcmVkU2VjcmV0GAUgASgMEhYKDmludml0YXRpb25EYXRhGAYgASgMEg8KB3ZlcnNpb24YByABKAUigAEKF0dyb3VwU2Vzc2lvblBhcnRpY2lwYW50EhIKCmlkZW50aWZpZXIYASABKAkSHwoIaWRlbnRpdHkYAiABKAsyDS5Vc2VySWRlbnRpdHkSEQoJY29ubmVjdGVkGAMgASgIEg0KBWd1ZXN0GAQgASgIEg4KBmhpZGRlbhgFIAEoCCJfChdHcm91cFNlc3Npb25Kb2luUmVxdWVzdBISCgppZGVudGlmaWVyGAEgASgJEh8KCGlkZW50aXR5GAIgASgLMg0uVXNlcklkZW50aXR5Eg8KB29vYktleXMYAyABKAwiSQoYR3JvdXBTZXNzaW9uSm9pblJlc3BvbnNlEg8KB2pvaW5VUkwYASABKAkSHAoUcHVibGljU2lnbmluZ0tleURhdGEYAiABKAwiOgoZR3JvdXBTZXNzaW9uUmVtb3ZlUmVxdWVzdBIdChVwYXJ0aWNpcGFudElkZW50aWZpZXIYASABKAki6gMKIEdyb3VwVG9wb2xvZ3lNb2RpZmljYXRpb25SZXF1ZXN0EjQKBHR5cGUYASABKA4yJi5Hcm91cFRvcG9sb2d5TW9kaWZpY2F0aW9uUmVxdWVzdC5UeXBlEhgKEG91dHB1dERldmljZVVJRHMYAiADKAkSEAoIcGFzc3dvcmQYAyABKAkSIAoHZGV0YWlscxgEIAEoCzIPLlJlcXVlc3REZXRhaWxzEhEKCWZhZGVBdWRpbxgFIAEoCBIZChFtdXRlVW50aWxGaW5pc2hlZBgGIAEoCBIiChpzaG91bGRDbGVhclByZWRpY3RlZFJvdXRlcxgHIAEoCBIjChtzaG91bGRNb2RpZnlQcmVkaWN0ZWRSb3V0ZXMYCCABKAgSKQohc2hvdWxkTm90UGF1c2VJZkxhc3REZXZpY2VSZW1vdmVkGAkgASgIEikKIXNob3VsZFdhaXRGb3JVcGRhdGVkT3V0cHV0RGV2aWNlcxgKIAEoCBIbChNzdXBwcmVzc0Vycm9yRGlhbG9nGAsgASgIIlgKBFR5cGUSCwoHVW5rbm93bhAAEhQKEEFkZE91dHB1dERldmljZXMQARIXChNSZW1vdmVPdXRwdXREZXZpY2VzEAISFAoQU2V0T3V0cHV0RGV2aWNlcxAD", [file_Common, file_RequestDetails, file_UserIdentity]);

/**
 * @generated from message GroupSessionInfo
 */
export type GroupSessionInfo = Message<"GroupSessionInfo"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional string hostDisplayName = 2;
   */
  hostDisplayName: string;

  /**
   * @generated from field: optional string equivalentMediaIdentifier = 3;
   */
  equivalentMediaIdentifier: string;

  /**
   * @generated from field: optional GroupSessionRouteType.Enum routeType = 4;
   */
  routeType: GroupSessionRouteType_Enum;

  /**
   * @generated from field: optional bool hosted = 5;
   */
  hosted: boolean;

  /**
   * @generated from field: optional bool placeholder = 6;
   */
  placeholder: boolean;
};

/**
 * Describes the message GroupSessionInfo.
 * Use `create(GroupSessionInfoSchema)` to create a new message.
 */
export const GroupSessionInfoSchema: GenMessage<GroupSessionInfo> = /*@__PURE__*/
  messageDesc(file_GroupSession, 0);

/**
 * @generated from message GroupSessionToken
 */
export type GroupSessionToken = Message<"GroupSessionToken"> & {
  /**
   * @generated from field: optional string sessionIdentifier = 1;
   */
  sessionIdentifier: string;

  /**
   * @generated from field: optional string displayName = 2;
   */
  displayName: string;

  /**
   * @generated from field: optional string equivalentMediaIdentifier = 3;
   */
  equivalentMediaIdentifier: string;

  /**
   * @generated from field: optional GroupSessionRouteType.Enum routeType = 4;
   */
  routeType: GroupSessionRouteType_Enum;

  /**
   * @generated from field: optional bytes sharedSecret = 5;
   */
  sharedSecret: Uint8Array;

  /**
   * @generated from field: optional bytes invitationData = 6;
   */
  invitationData: Uint8Array;

  /**
   * @generated from field: optional int32 version = 7;
   */
  version: number;
};

/**
 * Describes the message GroupSessionToken.
 * Use `create(GroupSessionTokenSchema)` to create a new message.
 */
export const GroupSessionTokenSchema: GenMessage<GroupSessionToken> = /*@__PURE__*/
  messageDesc(file_GroupSession, 1);

/**
 * @generated from message GroupSessionParticipant
 */
export type GroupSessionParticipant = Message<"GroupSessionParticipant"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional UserIdentity identity = 2;
   */
  identity?: UserIdentity;

  /**
   * @generated from field: optional bool connected = 3;
   */
  connected: boolean;

  /**
   * @generated from field: optional bool guest = 4;
   */
  guest: boolean;

  /**
   * @generated from field: optional bool hidden = 5;
   */
  hidden: boolean;
};

/**
 * Describes the message GroupSessionParticipant.
 * Use `create(GroupSessionParticipantSchema)` to create a new message.
 */
export const GroupSessionParticipantSchema: GenMessage<GroupSessionParticipant> = /*@__PURE__*/
  messageDesc(file_GroupSession, 2);

/**
 * @generated from message GroupSessionJoinRequest
 */
export type GroupSessionJoinRequest = Message<"GroupSessionJoinRequest"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional UserIdentity identity = 2;
   */
  identity?: UserIdentity;

  /**
   * @generated from field: optional bytes oobKeys = 3;
   */
  oobKeys: Uint8Array;
};

/**
 * Describes the message GroupSessionJoinRequest.
 * Use `create(GroupSessionJoinRequestSchema)` to create a new message.
 */
export const GroupSessionJoinRequestSchema: GenMessage<GroupSessionJoinRequest> = /*@__PURE__*/
  messageDesc(file_GroupSession, 3);

/**
 * @generated from message GroupSessionJoinResponse
 */
export type GroupSessionJoinResponse = Message<"GroupSessionJoinResponse"> & {
  /**
   * @generated from field: optional string joinURL = 1;
   */
  joinURL: string;

  /**
   * @generated from field: optional bytes publicSigningKeyData = 2;
   */
  publicSigningKeyData: Uint8Array;
};

/**
 * Describes the message GroupSessionJoinResponse.
 * Use `create(GroupSessionJoinResponseSchema)` to create a new message.
 */
export const GroupSessionJoinResponseSchema: GenMessage<GroupSessionJoinResponse> = /*@__PURE__*/
  messageDesc(file_GroupSession, 4);

/**
 * @generated from message GroupSessionRemoveRequest
 */
export type GroupSessionRemoveRequest = Message<"GroupSessionRemoveRequest"> & {
  /**
   * @generated from field: optional string participantIdentifier = 1;
   */
  participantIdentifier: string;
};

/**
 * Describes the message GroupSessionRemoveRequest.
 * Use `create(GroupSessionRemoveRequestSchema)` to create a new message.
 */
export const GroupSessionRemoveRequestSchema: GenMessage<GroupSessionRemoveRequest> = /*@__PURE__*/
  messageDesc(file_GroupSession, 5);

/**
 * @generated from message GroupTopologyModificationRequest
 */
export type GroupTopologyModificationRequest = Message<"GroupTopologyModificationRequest"> & {
  /**
   * @generated from field: optional GroupTopologyModificationRequest.Type type = 1;
   */
  type: GroupTopologyModificationRequest_Type;

  /**
   * @generated from field: repeated string outputDeviceUIDs = 2;
   */
  outputDeviceUIDs: string[];

  /**
   * @generated from field: optional string password = 3;
   */
  password: string;

  /**
   * @generated from field: optional RequestDetails details = 4;
   */
  details?: RequestDetails;

  /**
   * @generated from field: optional bool fadeAudio = 5;
   */
  fadeAudio: boolean;

  /**
   * @generated from field: optional bool muteUntilFinished = 6;
   */
  muteUntilFinished: boolean;

  /**
   * @generated from field: optional bool shouldClearPredictedRoutes = 7;
   */
  shouldClearPredictedRoutes: boolean;

  /**
   * @generated from field: optional bool shouldModifyPredictedRoutes = 8;
   */
  shouldModifyPredictedRoutes: boolean;

  /**
   * @generated from field: optional bool shouldNotPauseIfLastDeviceRemoved = 9;
   */
  shouldNotPauseIfLastDeviceRemoved: boolean;

  /**
   * @generated from field: optional bool shouldWaitForUpdatedOutputDevices = 10;
   */
  shouldWaitForUpdatedOutputDevices: boolean;

  /**
   * @generated from field: optional bool suppressErrorDialog = 11;
   */
  suppressErrorDialog: boolean;
};

/**
 * Describes the message GroupTopologyModificationRequest.
 * Use `create(GroupTopologyModificationRequestSchema)` to create a new message.
 */
export const GroupTopologyModificationRequestSchema: GenMessage<GroupTopologyModificationRequest> = /*@__PURE__*/
  messageDesc(file_GroupSession, 6);

/**
 * @generated from enum GroupTopologyModificationRequest.Type
 */
export enum GroupTopologyModificationRequest_Type {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: AddOutputDevices = 1;
   */
  AddOutputDevices = 1,

  /**
   * @generated from enum value: RemoveOutputDevices = 2;
   */
  RemoveOutputDevices = 2,

  /**
   * @generated from enum value: SetOutputDevices = 3;
   */
  SetOutputDevices = 3,
}

/**
 * Describes the enum GroupTopologyModificationRequest.Type.
 */
export const GroupTopologyModificationRequest_TypeSchema: GenEnum<GroupTopologyModificationRequest_Type> = /*@__PURE__*/
  enumDesc(file_GroupSession, 6, 0);

