// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file GroupSessionJoinResponseMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file GroupSessionJoinResponseMessage.proto.
 */
export const file_GroupSessionJoinResponseMessage: GenFile = /*@__PURE__*/
  fileDesc("CiVHcm91cFNlc3Npb25Kb2luUmVzcG9uc2VNZXNzYWdlLnByb3RvIlIKH0dyb3VwU2Vzc2lvbkpvaW5SZXNwb25zZU1lc3NhZ2USEAoIYXBwcm92ZWQYASABKAgSHQoVcGFydGljaXBhbnRJZGVudGlmaWVyGAIgASgJOnwKH2dyb3VwU2Vzc2lvbkpvaW5SZXNwb25zZU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYaCABKAsyIC5Hcm91cFNlc3Npb25Kb2luUmVzcG9uc2VNZXNzYWdlUh9ncm91cFNlc3Npb25Kb2luUmVzcG9uc2VNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message GroupSessionJoinResponseMessage
 */
export type GroupSessionJoinResponseMessage = Message<"GroupSessionJoinResponseMessage"> & {
  /**
   * @generated from field: optional bool approved = 1;
   */
  approved: boolean;

  /**
   * @generated from field: optional string participantIdentifier = 2;
   */
  participantIdentifier: string;
};

/**
 * Describes the message GroupSessionJoinResponseMessage.
 * Use `create(GroupSessionJoinResponseMessageSchema)` to create a new message.
 */
export const GroupSessionJoinResponseMessageSchema: GenMessage<GroupSessionJoinResponseMessage> = /*@__PURE__*/
  messageDesc(file_GroupSessionJoinResponseMessage, 0);

/**
 * @generated from extension: optional GroupSessionJoinResponseMessage groupSessionJoinResponseMessage = 104;
 */
export const groupSessionJoinResponseMessage: GenExtension<ProtocolMessage, GroupSessionJoinResponseMessage> = /*@__PURE__*/
  extDesc(file_GroupSessionJoinResponseMessage, 0);

