// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file KeyboardMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file KeyboardMessage.proto.
 */
export const file_KeyboardMessage: GenFile = /*@__PURE__*/
  fileDesc("ChVLZXlib2FyZE1lc3NhZ2UucHJvdG8iigEKDUtleWJvYXJkU3RhdGUieQoERW51bRILCgdVbmtub3duEAASDgoKTm90RWRpdGluZxABEhMKD0RpZEJlZ2luRWRpdGluZxACEgsKB0VkaXRpbmcQAxIRCg1UZXh0RGlkQ2hhbmdlEAQSEQoNRGlkRW5kRWRpdGluZxAFEgwKCFJlc3BvbnNlEAYiVwoWQXV0b2NhcGl0YWxpemF0aW9uVHlwZSI9CgRFbnVtEggKBE5vbmUQABIJCgVXb3JkcxABEg0KCVNlbnRlbmNlcxACEhEKDUFsbENoYXJhY3RlcnMQAyLnAQoMS2V5Ym9hcmRUeXBlItYBCgRFbnVtEgsKB0RlZmF1bHQQABIRCg1BU0NJSV9DYXBhYmxlEAESGQoVTnVtYmVyc0FuZFB1bmN0dWF0aW9uEAISBwoDVVJMEAMSDQoJTnVtYmVyUGFkEAQSDAoIUGhvbmVQYWQQBRIQCgxOYW1lUGhvbmVQYWQQBhIQCgxFbWFpbEFkZHJlc3MQBxIOCgpEZWNpbWFsUGFkEAgSCwoHVHdpdHRlchAJEg0KCVdlYlNlYXJjaBAKEgwKCEFscGhhbmV0EAsSDwoLUGFzc2NvZGVQYWQQDCKkAQoNUmV0dXJuS2V5VHlwZSKSAQoERW51bRILCgdEZWZhdWx0EAASBgoCR28QARIKCgZHb29nbGUQAhIICgRKb2luEAMSCAoETmV4dBAEEgkKBVJvdXRlEAUSCgoGU2VhcmNoEAYSCAoEU2VuZBAHEgkKBVlhaG9vEAgSCAoERG9uZRAJEhEKDUVtZXJnZW5jeUNhbGwQChIMCghDb250aW51ZRALIvQCCg9UZXh0SW5wdXRUcmFpdHMSPAoWYXV0b2NhcGl0YWxpemF0aW9uVHlwZRgBIAEoDjIcLkF1dG9jYXBpdGFsaXphdGlvblR5cGUuRW51bRIoCgxrZXlib2FyZFR5cGUYAiABKA4yEi5LZXlib2FyZFR5cGUuRW51bRIqCg1yZXR1cm5LZXlUeXBlGAMgASgOMhMuUmV0dXJuS2V5VHlwZS5FbnVtEhYKDmF1dG9jb3JyZWN0aW9uGAQgASgIEhUKDXNwZWxsY2hlY2tpbmcYBSABKAgSJQodZW5hYmxlc1JldHVybktleUF1dG9tYXRpY2FsbHkYBiABKAgSFwoPc2VjdXJlVGV4dEVudHJ5GAcgASgIEh4KFnZhbGlkVGV4dFJhbmdlTG9jYXRpb24YCCABKAQSHAoUdmFsaWRUZXh0UmFuZ2VMZW5ndGgYCSABKAQSIAoYcElORW50cnlTZXBhcmF0b3JJbmRleGVzGAogAygEIl0KFVRleHRFZGl0aW5nQXR0cmlidXRlcxINCgV0aXRsZRgBIAEoCRIOCgZwcm9tcHQYAiABKAkSJQoLaW5wdXRUcmFpdHMYAyABKAsyEC5UZXh0SW5wdXRUcmFpdHMiggEKD0tleWJvYXJkTWVzc2FnZRIiCgVzdGF0ZRgBIAEoDjITLktleWJvYXJkU3RhdGUuRW51bRIqCgphdHRyaWJ1dGVzGAMgASgLMhYuVGV4dEVkaXRpbmdBdHRyaWJ1dGVzEh8KF2VuY3J5cHRlZFRleHRDeXBoZXJ0ZXh0GAQgASgMOkwKD2tleWJvYXJkTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgcIAEoCzIQLktleWJvYXJkTWVzc2FnZVIPa2V5Ym9hcmRNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message KeyboardState
 */
export type KeyboardState = Message<"KeyboardState"> & {
};

/**
 * Describes the message KeyboardState.
 * Use `create(KeyboardStateSchema)` to create a new message.
 */
export const KeyboardStateSchema: GenMessage<KeyboardState> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 0);

/**
 * @generated from enum KeyboardState.Enum
 */
export enum KeyboardState_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: NotEditing = 1;
   */
  NotEditing = 1,

  /**
   * @generated from enum value: DidBeginEditing = 2;
   */
  DidBeginEditing = 2,

  /**
   * @generated from enum value: Editing = 3;
   */
  Editing = 3,

  /**
   * @generated from enum value: TextDidChange = 4;
   */
  TextDidChange = 4,

  /**
   * @generated from enum value: DidEndEditing = 5;
   */
  DidEndEditing = 5,

  /**
   * @generated from enum value: Response = 6;
   */
  Response = 6,
}

/**
 * Describes the enum KeyboardState.Enum.
 */
export const KeyboardState_EnumSchema: GenEnum<KeyboardState_Enum> = /*@__PURE__*/
  enumDesc(file_KeyboardMessage, 0, 0);

/**
 * @generated from message AutocapitalizationType
 */
export type AutocapitalizationType = Message<"AutocapitalizationType"> & {
};

/**
 * Describes the message AutocapitalizationType.
 * Use `create(AutocapitalizationTypeSchema)` to create a new message.
 */
export const AutocapitalizationTypeSchema: GenMessage<AutocapitalizationType> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 1);

/**
 * @generated from enum AutocapitalizationType.Enum
 */
export enum AutocapitalizationType_Enum {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Words = 1;
   */
  Words = 1,

  /**
   * @generated from enum value: Sentences = 2;
   */
  Sentences = 2,

  /**
   * @generated from enum value: AllCharacters = 3;
   */
  AllCharacters = 3,
}

/**
 * Describes the enum AutocapitalizationType.Enum.
 */
export const AutocapitalizationType_EnumSchema: GenEnum<AutocapitalizationType_Enum> = /*@__PURE__*/
  enumDesc(file_KeyboardMessage, 1, 0);

/**
 * @generated from message KeyboardType
 */
export type KeyboardType = Message<"KeyboardType"> & {
};

/**
 * Describes the message KeyboardType.
 * Use `create(KeyboardTypeSchema)` to create a new message.
 */
export const KeyboardTypeSchema: GenMessage<KeyboardType> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 2);

/**
 * @generated from enum KeyboardType.Enum
 */
export enum KeyboardType_Enum {
  /**
   * @generated from enum value: Default = 0;
   */
  Default = 0,

  /**
   * @generated from enum value: ASCII_Capable = 1;
   */
  ASCII_Capable = 1,

  /**
   * @generated from enum value: NumbersAndPunctuation = 2;
   */
  NumbersAndPunctuation = 2,

  /**
   * @generated from enum value: URL = 3;
   */
  URL = 3,

  /**
   * @generated from enum value: NumberPad = 4;
   */
  NumberPad = 4,

  /**
   * @generated from enum value: PhonePad = 5;
   */
  PhonePad = 5,

  /**
   * @generated from enum value: NamePhonePad = 6;
   */
  NamePhonePad = 6,

  /**
   * @generated from enum value: EmailAddress = 7;
   */
  EmailAddress = 7,

  /**
   * @generated from enum value: DecimalPad = 8;
   */
  DecimalPad = 8,

  /**
   * @generated from enum value: Twitter = 9;
   */
  Twitter = 9,

  /**
   * @generated from enum value: WebSearch = 10;
   */
  WebSearch = 10,

  /**
   * @generated from enum value: Alphanet = 11;
   */
  Alphanet = 11,

  /**
   * @generated from enum value: PasscodePad = 12;
   */
  PasscodePad = 12,
}

/**
 * Describes the enum KeyboardType.Enum.
 */
export const KeyboardType_EnumSchema: GenEnum<KeyboardType_Enum> = /*@__PURE__*/
  enumDesc(file_KeyboardMessage, 2, 0);

/**
 * @generated from message ReturnKeyType
 */
export type ReturnKeyType = Message<"ReturnKeyType"> & {
};

/**
 * Describes the message ReturnKeyType.
 * Use `create(ReturnKeyTypeSchema)` to create a new message.
 */
export const ReturnKeyTypeSchema: GenMessage<ReturnKeyType> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 3);

/**
 * @generated from enum ReturnKeyType.Enum
 */
export enum ReturnKeyType_Enum {
  /**
   * @generated from enum value: Default = 0;
   */
  Default = 0,

  /**
   * @generated from enum value: Go = 1;
   */
  Go = 1,

  /**
   * @generated from enum value: Google = 2;
   */
  Google = 2,

  /**
   * @generated from enum value: Join = 3;
   */
  Join = 3,

  /**
   * @generated from enum value: Next = 4;
   */
  Next = 4,

  /**
   * @generated from enum value: Route = 5;
   */
  Route = 5,

  /**
   * @generated from enum value: Search = 6;
   */
  Search = 6,

  /**
   * @generated from enum value: Send = 7;
   */
  Send = 7,

  /**
   * @generated from enum value: Yahoo = 8;
   */
  Yahoo = 8,

  /**
   * @generated from enum value: Done = 9;
   */
  Done = 9,

  /**
   * @generated from enum value: EmergencyCall = 10;
   */
  EmergencyCall = 10,

  /**
   * @generated from enum value: Continue = 11;
   */
  Continue = 11,
}

/**
 * Describes the enum ReturnKeyType.Enum.
 */
export const ReturnKeyType_EnumSchema: GenEnum<ReturnKeyType_Enum> = /*@__PURE__*/
  enumDesc(file_KeyboardMessage, 3, 0);

/**
 * @generated from message TextInputTraits
 */
export type TextInputTraits = Message<"TextInputTraits"> & {
  /**
   * @generated from field: optional AutocapitalizationType.Enum autocapitalizationType = 1;
   */
  autocapitalizationType: AutocapitalizationType_Enum;

  /**
   * @generated from field: optional KeyboardType.Enum keyboardType = 2;
   */
  keyboardType: KeyboardType_Enum;

  /**
   * @generated from field: optional ReturnKeyType.Enum returnKeyType = 3;
   */
  returnKeyType: ReturnKeyType_Enum;

  /**
   * @generated from field: optional bool autocorrection = 4;
   */
  autocorrection: boolean;

  /**
   * @generated from field: optional bool spellchecking = 5;
   */
  spellchecking: boolean;

  /**
   * @generated from field: optional bool enablesReturnKeyAutomatically = 6;
   */
  enablesReturnKeyAutomatically: boolean;

  /**
   * @generated from field: optional bool secureTextEntry = 7;
   */
  secureTextEntry: boolean;

  /**
   * @generated from field: optional uint64 validTextRangeLocation = 8;
   */
  validTextRangeLocation: bigint;

  /**
   * @generated from field: optional uint64 validTextRangeLength = 9;
   */
  validTextRangeLength: bigint;

  /**
   * @generated from field: repeated uint64 pINEntrySeparatorIndexes = 10;
   */
  pINEntrySeparatorIndexes: bigint[];
};

/**
 * Describes the message TextInputTraits.
 * Use `create(TextInputTraitsSchema)` to create a new message.
 */
export const TextInputTraitsSchema: GenMessage<TextInputTraits> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 4);

/**
 * @generated from message TextEditingAttributes
 */
export type TextEditingAttributes = Message<"TextEditingAttributes"> & {
  /**
   * @generated from field: optional string title = 1;
   */
  title: string;

  /**
   * @generated from field: optional string prompt = 2;
   */
  prompt: string;

  /**
   * @generated from field: optional TextInputTraits inputTraits = 3;
   */
  inputTraits?: TextInputTraits;
};

/**
 * Describes the message TextEditingAttributes.
 * Use `create(TextEditingAttributesSchema)` to create a new message.
 */
export const TextEditingAttributesSchema: GenMessage<TextEditingAttributes> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 5);

/**
 * @generated from message KeyboardMessage
 */
export type KeyboardMessage = Message<"KeyboardMessage"> & {
  /**
   * @generated from field: optional KeyboardState.Enum state = 1;
   */
  state: KeyboardState_Enum;

  /**
   * @generated from field: optional TextEditingAttributes attributes = 3;
   */
  attributes?: TextEditingAttributes;

  /**
   * @generated from field: optional bytes encryptedTextCyphertext = 4;
   */
  encryptedTextCyphertext: Uint8Array;
};

/**
 * Describes the message KeyboardMessage.
 * Use `create(KeyboardMessageSchema)` to create a new message.
 */
export const KeyboardMessageSchema: GenMessage<KeyboardMessage> = /*@__PURE__*/
  messageDesc(file_KeyboardMessage, 6);

/**
 * @generated from extension: optional KeyboardMessage keyboardMessage = 28;
 */
export const keyboardMessage: GenExtension<ProtocolMessage, KeyboardMessage> = /*@__PURE__*/
  extDesc(file_KeyboardMessage, 0);

