// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file LanguageOption.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file LanguageOption.proto.
 */
export const file_LanguageOption: GenFile = /*@__PURE__*/
  fileDesc("ChRMYW5ndWFnZU9wdGlvbi5wcm90byJ1Cg5MYW5ndWFnZU9wdGlvbhIMCgR0eXBlGAEgASgFEhMKC2xhbmd1YWdlVGFnGAIgASgJEhcKD2NoYXJhY3RlcmlzdGljcxgDIAMoCRITCgtkaXNwbGF5TmFtZRgEIAEoCRISCgppZGVudGlmaWVyGAUgASgJ");

/**
 * @generated from message LanguageOption
 */
export type LanguageOption = Message<"LanguageOption"> & {
  /**
   * @generated from field: optional int32 type = 1;
   */
  type: number;

  /**
   * @generated from field: optional string languageTag = 2;
   */
  languageTag: string;

  /**
   * @generated from field: repeated string characteristics = 3;
   */
  characteristics: string[];

  /**
   * @generated from field: optional string displayName = 4;
   */
  displayName: string;

  /**
   * @generated from field: optional string identifier = 5;
   */
  identifier: string;
};

/**
 * Describes the message LanguageOption.
 * Use `create(LanguageOptionSchema)` to create a new message.
 */
export const LanguageOptionSchema: GenMessage<LanguageOption> = /*@__PURE__*/
  messageDesc(file_LanguageOption, 0);

