// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file LyricsItem.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file LyricsItem.proto.
 */
export const file_LyricsItem: GenFile = /*@__PURE__*/
  fileDesc("ChBMeXJpY3NJdGVtLnByb3RvIk8KCkx5cmljc0l0ZW0SDgoGbHlyaWNzGAEgASgJEhQKDHVzZXJQcm92aWRlZBgCIAEoCBIbCgV0b2tlbhgDIAEoCzIMLkx5cmljc1Rva2VuIjMKC0x5cmljc1Rva2VuEhIKCmlkZW50aWZpZXIYASABKAkSEAoIdXNlckRhdGEYAiABKAw");

/**
 * @generated from message LyricsItem
 */
export type LyricsItem = Message<"LyricsItem"> & {
  /**
   * @generated from field: optional string lyrics = 1;
   */
  lyrics: string;

  /**
   * @generated from field: optional bool userProvided = 2;
   */
  userProvided: boolean;

  /**
   * @generated from field: optional LyricsToken token = 3;
   */
  token?: LyricsToken;
};

/**
 * Describes the message LyricsItem.
 * Use `create(LyricsItemSchema)` to create a new message.
 */
export const LyricsItemSchema: GenMessage<LyricsItem> = /*@__PURE__*/
  messageDesc(file_LyricsItem, 0);

/**
 * @generated from message LyricsToken
 */
export type LyricsToken = Message<"LyricsToken"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional bytes userData = 2;
   */
  userData: Uint8Array;
};

/**
 * Describes the message LyricsToken.
 * Use `create(LyricsTokenSchema)` to create a new message.
 */
export const LyricsTokenSchema: GenMessage<LyricsToken> = /*@__PURE__*/
  messageDesc(file_LyricsItem, 1);

