// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file MicrophoneConnectionRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { RequestDetails } from "./RequestDetails_pb";
import { file_RequestDetails } from "./RequestDetails_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file MicrophoneConnectionRequestMessage.proto.
 */
export const file_MicrophoneConnectionRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CihNaWNyb3Bob25lQ29ubmVjdGlvblJlcXVlc3RNZXNzYWdlLnByb3RvImEKIk1pY3JvcGhvbmVDb25uZWN0aW9uUmVxdWVzdE1lc3NhZ2USIAoHZGV0YWlscxgBIAEoCzIPLlJlcXVlc3REZXRhaWxzEhkKEXJhcHBvcnRJZGVudGlmaWVyGAIgASgJOoUBCiJtaWNyb3Bob25lQ29ubmVjdGlvblJlcXVlc3RNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGFsgASgLMiMuTWljcm9waG9uZUNvbm5lY3Rpb25SZXF1ZXN0TWVzc2FnZVIibWljcm9waG9uZUNvbm5lY3Rpb25SZXF1ZXN0TWVzc2FnZQ", [file_ProtocolMessage, file_RequestDetails]);

/**
 * @generated from message MicrophoneConnectionRequestMessage
 */
export type MicrophoneConnectionRequestMessage = Message<"MicrophoneConnectionRequestMessage"> & {
  /**
   * @generated from field: optional RequestDetails details = 1;
   */
  details?: RequestDetails;

  /**
   * @generated from field: optional string rapportIdentifier = 2;
   */
  rapportIdentifier: string;
};

/**
 * Describes the message MicrophoneConnectionRequestMessage.
 * Use `create(MicrophoneConnectionRequestMessageSchema)` to create a new message.
 */
export const MicrophoneConnectionRequestMessageSchema: GenMessage<MicrophoneConnectionRequestMessage> = /*@__PURE__*/
  messageDesc(file_MicrophoneConnectionRequestMessage, 0);

/**
 * @generated from extension: optional MicrophoneConnectionRequestMessage microphoneConnectionRequestMessage = 91;
 */
export const microphoneConnectionRequestMessage: GenExtension<ProtocolMessage, MicrophoneConnectionRequestMessage> = /*@__PURE__*/
  extDesc(file_MicrophoneConnectionRequestMessage, 0);

