// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ModifyOutputContextRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ModifyOutputContextRequestMessage.proto.
 */
export const file_ModifyOutputContextRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CidNb2RpZnlPdXRwdXRDb250ZXh0UmVxdWVzdE1lc3NhZ2UucHJvdG8iRQoeTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RUeXBlIiMKBEVudW0SGwoXU2hhcmVkQXVkaW9QcmVzZW50YXRpb24QASLOAgohTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RNZXNzYWdlEj8KEW91dHB1dENvbnRleHRUeXBlGAEgASgOMiQuTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RUeXBlLkVudW0SHgoWYWRkaW5nT3V0cHV0RGV2aWNlVUlEcxgCIAMoCRIgChhyZW1vdmluZ091dHB1dERldmljZVVJRHMYAyADKAkSHwoXc2V0dGluZ091dHB1dERldmljZVVJRHMYBCADKAkSKgoiY2x1c3RlckF3YXJlQWRkaW5nT3V0cHV0RGV2aWNlVUlEcxgFIAMoCRIsCiRjbHVzdGVyQXdhcmVSZW1vdmluZ091dHB1dERldmljZVVJRHMYBiADKAkSKwojY2x1c3RlckF3YXJlU2V0dGluZ091dHB1dERldmljZVVJRHMYByADKAk6ggEKIW1vZGlmeU91dHB1dENvbnRleHRSZXF1ZXN0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRg0IAEoCzIiLk1vZGlmeU91dHB1dENvbnRleHRSZXF1ZXN0TWVzc2FnZVIhbW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message ModifyOutputContextRequestType
 */
export type ModifyOutputContextRequestType = Message<"ModifyOutputContextRequestType"> & {
};

/**
 * Describes the message ModifyOutputContextRequestType.
 * Use `create(ModifyOutputContextRequestTypeSchema)` to create a new message.
 */
export const ModifyOutputContextRequestTypeSchema: GenMessage<ModifyOutputContextRequestType> = /*@__PURE__*/
  messageDesc(file_ModifyOutputContextRequestMessage, 0);

/**
 * @generated from enum ModifyOutputContextRequestType.Enum
 */
export enum ModifyOutputContextRequestType_Enum {
  /**
   * @generated from enum value: SharedAudioPresentation = 1;
   */
  SharedAudioPresentation = 1,
}

/**
 * Describes the enum ModifyOutputContextRequestType.Enum.
 */
export const ModifyOutputContextRequestType_EnumSchema: GenEnum<ModifyOutputContextRequestType_Enum> = /*@__PURE__*/
  enumDesc(file_ModifyOutputContextRequestMessage, 0, 0);

/**
 * @generated from message ModifyOutputContextRequestMessage
 */
export type ModifyOutputContextRequestMessage = Message<"ModifyOutputContextRequestMessage"> & {
  /**
   * @generated from field: optional ModifyOutputContextRequestType.Enum outputContextType = 1;
   */
  outputContextType: ModifyOutputContextRequestType_Enum;

  /**
   * @generated from field: repeated string addingOutputDeviceUIDs = 2;
   */
  addingOutputDeviceUIDs: string[];

  /**
   * @generated from field: repeated string removingOutputDeviceUIDs = 3;
   */
  removingOutputDeviceUIDs: string[];

  /**
   * @generated from field: repeated string settingOutputDeviceUIDs = 4;
   */
  settingOutputDeviceUIDs: string[];

  /**
   * @generated from field: repeated string clusterAwareAddingOutputDeviceUIDs = 5;
   */
  clusterAwareAddingOutputDeviceUIDs: string[];

  /**
   * @generated from field: repeated string clusterAwareRemovingOutputDeviceUIDs = 6;
   */
  clusterAwareRemovingOutputDeviceUIDs: string[];

  /**
   * @generated from field: repeated string clusterAwareSettingOutputDeviceUIDs = 7;
   */
  clusterAwareSettingOutputDeviceUIDs: string[];
};

/**
 * Describes the message ModifyOutputContextRequestMessage.
 * Use `create(ModifyOutputContextRequestMessageSchema)` to create a new message.
 */
export const ModifyOutputContextRequestMessageSchema: GenMessage<ModifyOutputContextRequestMessage> = /*@__PURE__*/
  messageDesc(file_ModifyOutputContextRequestMessage, 1);

/**
 * @generated from extension: optional ModifyOutputContextRequestMessage modifyOutputContextRequestMessage = 52;
 */
export const modifyOutputContextRequestMessage: GenExtension<ProtocolMessage, ModifyOutputContextRequestMessage> = /*@__PURE__*/
  extDesc(file_ModifyOutputContextRequestMessage, 0);

