// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ModifyOutputContextRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ModifyOutputContextRequestMessage.proto.
 */
export const file_ModifyOutputContextRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CidNb2RpZnlPdXRwdXRDb250ZXh0UmVxdWVzdE1lc3NhZ2UucHJvdG8iRQoeTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RUeXBlIiMKBEVudW0SGwoXU2hhcmVkQXVkaW9QcmVzZW50YXRpb24QASKLAgohTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RNZXNzYWdlEjIKBHR5cGUYASABKA4yJC5Nb2RpZnlPdXRwdXRDb250ZXh0UmVxdWVzdFR5cGUuRW51bRIVCg1hZGRpbmdEZXZpY2VzGAIgAygJEhcKD3JlbW92aW5nRGV2aWNlcxgDIAMoCRIWCg5zZXR0aW5nRGV2aWNlcxgEIAMoCRIhChljbHVzdGVyQXdhcmVBZGRpbmdEZXZpY2VzGAUgAygJEiMKG2NsdXN0ZXJBd2FyZVJlbW92aW5nRGV2aWNlcxgGIAMoCRIiChpjbHVzdGVyQXdhcmVTZXR0aW5nRGV2aWNlcxgHIAMoCTqCAQohbW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGDQgASgLMiIuTW9kaWZ5T3V0cHV0Q29udGV4dFJlcXVlc3RNZXNzYWdlUiFtb2RpZnlPdXRwdXRDb250ZXh0UmVxdWVzdE1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message ModifyOutputContextRequestType
 */
export type ModifyOutputContextRequestType = Message<"ModifyOutputContextRequestType"> & {
};

/**
 * Describes the message ModifyOutputContextRequestType.
 * Use `create(ModifyOutputContextRequestTypeSchema)` to create a new message.
 */
export const ModifyOutputContextRequestTypeSchema: GenMessage<ModifyOutputContextRequestType> = /*@__PURE__*/
  messageDesc(file_ModifyOutputContextRequestMessage, 0);

/**
 * @generated from enum ModifyOutputContextRequestType.Enum
 */
export enum ModifyOutputContextRequestType_Enum {
  /**
   * @generated from enum value: SharedAudioPresentation = 1;
   */
  SharedAudioPresentation = 1,
}

/**
 * Describes the enum ModifyOutputContextRequestType.Enum.
 */
export const ModifyOutputContextRequestType_EnumSchema: GenEnum<ModifyOutputContextRequestType_Enum> = /*@__PURE__*/
  enumDesc(file_ModifyOutputContextRequestMessage, 0, 0);

/**
 * @generated from message ModifyOutputContextRequestMessage
 */
export type ModifyOutputContextRequestMessage = Message<"ModifyOutputContextRequestMessage"> & {
  /**
   * @generated from field: optional ModifyOutputContextRequestType.Enum type = 1;
   */
  type: ModifyOutputContextRequestType_Enum;

  /**
   * @generated from field: repeated string addingDevices = 2;
   */
  addingDevices: string[];

  /**
   * @generated from field: repeated string removingDevices = 3;
   */
  removingDevices: string[];

  /**
   * @generated from field: repeated string settingDevices = 4;
   */
  settingDevices: string[];

  /**
   * @generated from field: repeated string clusterAwareAddingDevices = 5;
   */
  clusterAwareAddingDevices: string[];

  /**
   * @generated from field: repeated string clusterAwareRemovingDevices = 6;
   */
  clusterAwareRemovingDevices: string[];

  /**
   * @generated from field: repeated string clusterAwareSettingDevices = 7;
   */
  clusterAwareSettingDevices: string[];
};

/**
 * Describes the message ModifyOutputContextRequestMessage.
 * Use `create(ModifyOutputContextRequestMessageSchema)` to create a new message.
 */
export const ModifyOutputContextRequestMessageSchema: GenMessage<ModifyOutputContextRequestMessage> = /*@__PURE__*/
  messageDesc(file_ModifyOutputContextRequestMessage, 1);

/**
 * @generated from extension: optional ModifyOutputContextRequestMessage modifyOutputContextRequestMessage = 52;
 */
export const modifyOutputContextRequestMessage: GenExtension<ProtocolMessage, ModifyOutputContextRequestMessage> = /*@__PURE__*/
  extDesc(file_ModifyOutputContextRequestMessage, 0);

