// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file MusicHandoff.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file MusicHandoff.proto.
 */
export const file_MusicHandoff: GenFile = /*@__PURE__*/
  fileDesc("ChJNdXNpY0hhbmRvZmYucHJvdG8ihQEKEU11c2ljSGFuZG9mZkV2ZW50EhkKEXNlc3Npb25JZGVudGlmaWVyGAEgASgJEiUKBHR5cGUYAiABKA4yFy5NdXNpY0hhbmRvZmZFdmVudC5UeXBlIi4KBFR5cGUSCwoHVW5rbm93bhAAEg0KCVN1Y2NlZWRlZBABEgoKBkZhaWxlZBACInwKE011c2ljSGFuZG9mZlNlc3Npb24SEgoKaWRlbnRpZmllchgBIAEoCRIlChBzb3VyY2VQbGF5ZXJQYXRoGAIgASgLMgsuUGxheWVyUGF0aBIqChVkZXN0aW5hdGlvblBsYXllclBhdGgYAyABKAsyCy5QbGF5ZXJQYXRo", [file_PlayerPath]);

/**
 * @generated from message MusicHandoffEvent
 */
export type MusicHandoffEvent = Message<"MusicHandoffEvent"> & {
  /**
   * @generated from field: optional string sessionIdentifier = 1;
   */
  sessionIdentifier: string;

  /**
   * @generated from field: optional MusicHandoffEvent.Type type = 2;
   */
  type: MusicHandoffEvent_Type;
};

/**
 * Describes the message MusicHandoffEvent.
 * Use `create(MusicHandoffEventSchema)` to create a new message.
 */
export const MusicHandoffEventSchema: GenMessage<MusicHandoffEvent> = /*@__PURE__*/
  messageDesc(file_MusicHandoff, 0);

/**
 * @generated from enum MusicHandoffEvent.Type
 */
export enum MusicHandoffEvent_Type {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Succeeded = 1;
   */
  Succeeded = 1,

  /**
   * @generated from enum value: Failed = 2;
   */
  Failed = 2,
}

/**
 * Describes the enum MusicHandoffEvent.Type.
 */
export const MusicHandoffEvent_TypeSchema: GenEnum<MusicHandoffEvent_Type> = /*@__PURE__*/
  enumDesc(file_MusicHandoff, 0, 0);

/**
 * @generated from message MusicHandoffSession
 */
export type MusicHandoffSession = Message<"MusicHandoffSession"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional PlayerPath sourcePlayerPath = 2;
   */
  sourcePlayerPath?: PlayerPath;

  /**
   * @generated from field: optional PlayerPath destinationPlayerPath = 3;
   */
  destinationPlayerPath?: PlayerPath;
};

/**
 * Describes the message MusicHandoffSession.
 * Use `create(MusicHandoffSessionSchema)` to create a new message.
 */
export const MusicHandoffSessionSchema: GenMessage<MusicHandoffSession> = /*@__PURE__*/
  messageDesc(file_MusicHandoff, 1);

