// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file NotificationMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file NotificationMessage.proto.
 */
export const file_NotificationMessage: GenFile = /*@__PURE__*/
  fileDesc("ChlOb3RpZmljYXRpb25NZXNzYWdlLnByb3RvIl4KE05vdGlmaWNhdGlvbk1lc3NhZ2USFAoMbm90aWZpY2F0aW9uGAEgASgJEhAKCHVzZXJJbmZvGAIgASgMEh8KCnBsYXllclBhdGgYAyADKAsyCy5QbGF5ZXJQYXRoOlgKE25vdGlmaWNhdGlvbk1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYECABKAsyFC5Ob3RpZmljYXRpb25NZXNzYWdlUhNub3RpZmljYXRpb25NZXNzYWdl", [file_PlayerPath, file_ProtocolMessage]);

/**
 * @generated from message NotificationMessage
 */
export type NotificationMessage = Message<"NotificationMessage"> & {
  /**
   * @generated from field: optional string notification = 1;
   */
  notification: string;

  /**
   * @generated from field: optional bytes userInfo = 2;
   */
  userInfo: Uint8Array;

  /**
   * @generated from field: repeated PlayerPath playerPath = 3;
   */
  playerPath: PlayerPath[];
};

/**
 * Describes the message NotificationMessage.
 * Use `create(NotificationMessageSchema)` to create a new message.
 */
export const NotificationMessageSchema: GenMessage<NotificationMessage> = /*@__PURE__*/
  messageDesc(file_NotificationMessage, 0);

/**
 * @generated from extension: optional NotificationMessage notificationMessage = 16;
 */
export const notificationMessage: GenExtension<ProtocolMessage, NotificationMessage> = /*@__PURE__*/
  extDesc(file_NotificationMessage, 0);

