// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file NowPlayingClient.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file NowPlayingClient.proto.
 */
export const file_NowPlayingClient: GenFile = /*@__PURE__*/
  fileDesc("ChZOb3dQbGF5aW5nQ2xpZW50LnByb3RvIqcCChBOb3dQbGF5aW5nQ2xpZW50EhkKEXByb2Nlc3NJZGVudGlmaWVyGAEgASgFEhgKEGJ1bmRsZUlkZW50aWZpZXIYAiABKAkSKQohcGFyZW50QXBwbGljYXRpb25CdW5kbGVJZGVudGlmaWVyGAMgASgJEh0KFXByb2Nlc3NVc2VySWRlbnRpZmllchgEIAEoBRIcChRub3dQbGF5aW5nVmlzaWJpbGl0eRgFIAEoBRIRCgl0aW50Q29sb3IYBiABKAwSEwoLZGlzcGxheU5hbWUYByABKAkSIgoaYnVuZGxlSWRlbnRpZmllckhpZXJhcmNoeXMYCCADKAkSDwoHaWNvblVSTBgJIAEoCRIZChFpc0VtcHR5RGVwcmVjYXRlZBgKIAEoCA");

/**
 * @generated from message NowPlayingClient
 */
export type NowPlayingClient = Message<"NowPlayingClient"> & {
  /**
   * @generated from field: optional int32 processIdentifier = 1;
   */
  processIdentifier: number;

  /**
   * @generated from field: optional string bundleIdentifier = 2;
   */
  bundleIdentifier: string;

  /**
   * @generated from field: optional string parentApplicationBundleIdentifier = 3;
   */
  parentApplicationBundleIdentifier: string;

  /**
   * @generated from field: optional int32 processUserIdentifier = 4;
   */
  processUserIdentifier: number;

  /**
   * @generated from field: optional int32 nowPlayingVisibility = 5;
   */
  nowPlayingVisibility: number;

  /**
   * @generated from field: optional bytes tintColor = 6;
   */
  tintColor: Uint8Array;

  /**
   * @generated from field: optional string displayName = 7;
   */
  displayName: string;

  /**
   * @generated from field: repeated string bundleIdentifierHierarchys = 8;
   */
  bundleIdentifierHierarchys: string[];

  /**
   * @generated from field: optional string iconURL = 9;
   */
  iconURL: string;

  /**
   * @generated from field: optional bool isEmptyDeprecated = 10;
   */
  isEmptyDeprecated: boolean;
};

/**
 * Describes the message NowPlayingClient.
 * Use `create(NowPlayingClientSchema)` to create a new message.
 */
export const NowPlayingClientSchema: GenMessage<NowPlayingClient> = /*@__PURE__*/
  messageDesc(file_NowPlayingClient, 0);

