// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file NowPlayingInfo.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { RepeatMode_Enum, ShuffleMode_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file NowPlayingInfo.proto.
 */
export const file_NowPlayingInfo: GenFile = /*@__PURE__*/
  fileDesc("ChROb3dQbGF5aW5nSW5mby5wcm90byLBAwoOTm93UGxheWluZ0luZm8SDQoFYWxidW0YASABKAkSDgoGYXJ0aXN0GAIgASgJEhAKCGR1cmF0aW9uGAMgASgBEhMKC2VsYXBzZWRUaW1lGAQgASgBEhQKDHBsYXliYWNrUmF0ZRgFIAEoAhIkCgpyZXBlYXRNb2RlGAYgASgOMhAuUmVwZWF0TW9kZS5FbnVtEiYKC3NodWZmbGVNb2RlGAcgASgOMhEuU2h1ZmZsZU1vZGUuRW51bRIRCgl0aW1lc3RhbXAYCCABKAESDQoFdGl0bGUYCSABKAkSGAoQdW5pcXVlSWRlbnRpZmllchgKIAEoBBIXCg9pc0V4cGxpY2l0VHJhY2sYCyABKAgSEgoKaXNNdXNpY0FwcBgMIAEoCBIeChZyYWRpb1N0YXRpb25JZGVudGlmaWVyGA0gASgDEhgKEHJhZGlvU3RhdGlvbkhhc2gYDiABKAkSGAoQcmFkaW9TdGF0aW9uTmFtZRgPIAEoCRIZChFhcnR3b3JrRGF0YURpZ2VzdBgQIAEoDBIUCgxpc0Fsd2F5c0xpdmUYESABKAgSFwoPaXNBZHZlcnRpc2VtZW50GBIgASgI", [file_Common]);

/**
 * @generated from message NowPlayingInfo
 */
export type NowPlayingInfo = Message<"NowPlayingInfo"> & {
  /**
   * @generated from field: optional string album = 1;
   */
  album: string;

  /**
   * @generated from field: optional string artist = 2;
   */
  artist: string;

  /**
   * @generated from field: optional double duration = 3;
   */
  duration: number;

  /**
   * @generated from field: optional double elapsedTime = 4;
   */
  elapsedTime: number;

  /**
   * @generated from field: optional float playbackRate = 5;
   */
  playbackRate: number;

  /**
   * @generated from field: optional RepeatMode.Enum repeatMode = 6;
   */
  repeatMode: RepeatMode_Enum;

  /**
   * @generated from field: optional ShuffleMode.Enum shuffleMode = 7;
   */
  shuffleMode: ShuffleMode_Enum;

  /**
   * @generated from field: optional double timestamp = 8;
   */
  timestamp: number;

  /**
   * @generated from field: optional string title = 9;
   */
  title: string;

  /**
   * @generated from field: optional uint64 uniqueIdentifier = 10;
   */
  uniqueIdentifier: bigint;

  /**
   * @generated from field: optional bool isExplicitTrack = 11;
   */
  isExplicitTrack: boolean;

  /**
   * @generated from field: optional bool isMusicApp = 12;
   */
  isMusicApp: boolean;

  /**
   * @generated from field: optional int64 radioStationIdentifier = 13;
   */
  radioStationIdentifier: bigint;

  /**
   * @generated from field: optional string radioStationHash = 14;
   */
  radioStationHash: string;

  /**
   * @generated from field: optional string radioStationName = 15;
   */
  radioStationName: string;

  /**
   * @generated from field: optional bytes artworkDataDigest = 16;
   */
  artworkDataDigest: Uint8Array;

  /**
   * @generated from field: optional bool isAlwaysLive = 17;
   */
  isAlwaysLive: boolean;

  /**
   * @generated from field: optional bool isAdvertisement = 18;
   */
  isAdvertisement: boolean;
};

/**
 * Describes the message NowPlayingInfo.
 * Use `create(NowPlayingInfoSchema)` to create a new message.
 */
export const NowPlayingInfoSchema: GenMessage<NowPlayingInfo> = /*@__PURE__*/
  messageDesc(file_NowPlayingInfo, 0);

