// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file NowPlayingAudioFormatContentInfo.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AudioFormat } from "./ContentItemMetadata_pb";
import { file_ContentItemMetadata } from "./ContentItemMetadata_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file NowPlayingAudioFormatContentInfo.proto.
 */
export const file_NowPlayingAudioFormatContentInfo: GenFile = /*@__PURE__*/
  fileDesc("CiZOb3dQbGF5aW5nQXVkaW9Gb3JtYXRDb250ZW50SW5mby5wcm90byLTAgogTm93UGxheWluZ0F1ZGlvRm9ybWF0Q29udGVudEluZm8SIQoLYXVkaW9Gb3JtYXQYASABKAsyDC5BdWRpb0Zvcm1hdBIQCghidW5kbGVJRBgCIAEoCRILCgNwaWQYAyABKAUSFgoOYXVkaW9TZXNzaW9uSUQYBCABKAMSFAoMY2hhbm5lbENvdW50GAUgASgFEhUKDXJlbmRlcmluZ01vZGUYBiABKAUSEwoLc3BhdGlhbGl6ZWQYByABKAgSIQoZZWxpZ2libGVGb3JTcGF0aWFsaXphdGlvbhgIIAEoCBIhChlpbnRlbmRlZFNwYXRpYWxFeHBlcmllbmNlGAkgASgFEiEKGXJlc29sdmVkU3BhdGlhbEV4cGVyaWVuY2UYCiABKAUSKgoUYmVzdEF2YWlsYWJsZUNvbnRlbnQYCyABKAsyDC5BdWRpb0Zvcm1hdA", [file_ContentItemMetadata]);

/**
 * @generated from message NowPlayingAudioFormatContentInfo
 */
export type NowPlayingAudioFormatContentInfo = Message<"NowPlayingAudioFormatContentInfo"> & {
  /**
   * @generated from field: optional AudioFormat audioFormat = 1;
   */
  audioFormat?: AudioFormat;

  /**
   * @generated from field: optional string bundleID = 2;
   */
  bundleID: string;

  /**
   * @generated from field: optional int32 pid = 3;
   */
  pid: number;

  /**
   * @generated from field: optional int64 audioSessionID = 4;
   */
  audioSessionID: bigint;

  /**
   * @generated from field: optional int32 channelCount = 5;
   */
  channelCount: number;

  /**
   * @generated from field: optional int32 renderingMode = 6;
   */
  renderingMode: number;

  /**
   * @generated from field: optional bool spatialized = 7;
   */
  spatialized: boolean;

  /**
   * @generated from field: optional bool eligibleForSpatialization = 8;
   */
  eligibleForSpatialization: boolean;

  /**
   * @generated from field: optional int32 intendedSpatialExperience = 9;
   */
  intendedSpatialExperience: number;

  /**
   * @generated from field: optional int32 resolvedSpatialExperience = 10;
   */
  resolvedSpatialExperience: number;

  /**
   * @generated from field: optional AudioFormat bestAvailableContent = 11;
   */
  bestAvailableContent?: AudioFormat;
};

/**
 * Describes the message NowPlayingAudioFormatContentInfo.
 * Use `create(NowPlayingAudioFormatContentInfoSchema)` to create a new message.
 */
export const NowPlayingAudioFormatContentInfoSchema: GenMessage<NowPlayingAudioFormatContentInfo> = /*@__PURE__*/
  messageDesc(file_NowPlayingAudioFormatContentInfo, 0);

