// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file NowPlayingPlayer.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file NowPlayingPlayer.proto.
 */
export const file_NowPlayingPlayer: GenFile = /*@__PURE__*/
  fileDesc("ChZOb3dQbGF5aW5nUGxheWVyLnByb3RvIpQBChBOb3dQbGF5aW5nUGxheWVyEhIKCmlkZW50aWZpZXIYASABKAkSEwoLZGlzcGxheU5hbWUYAiABKAkSGAoQYXVkaW9TZXNzaW9uVHlwZRgEIAEoBRIUCgxteFNlc3Npb25JRHMYBSABKAMSFgoOYXVkaW9TZXNzaW9uSUQYBiABKA0SDwoHaWNvblVSTBgHIAEoCQ");

/**
 * @generated from message NowPlayingPlayer
 */
export type NowPlayingPlayer = Message<"NowPlayingPlayer"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional string displayName = 2;
   */
  displayName: string;

  /**
   * @generated from field: optional int32 audioSessionType = 4;
   */
  audioSessionType: number;

  /**
   * @generated from field: optional int64 mxSessionIDs = 5;
   */
  mxSessionIDs: bigint;

  /**
   * @generated from field: optional uint32 audioSessionID = 6;
   */
  audioSessionID: number;

  /**
   * @generated from field: optional string iconURL = 7;
   */
  iconURL: string;
};

/**
 * Describes the message NowPlayingPlayer.
 * Use `create(NowPlayingPlayerSchema)` to create a new message.
 */
export const NowPlayingPlayerSchema: GenMessage<NowPlayingPlayer> = /*@__PURE__*/
  messageDesc(file_NowPlayingPlayer, 0);

