// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file Origin.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import { file_DeviceInfoMessage } from "./DeviceInfoMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Origin.proto.
 */
export const file_Origin: GenFile = /*@__PURE__*/
  fileDesc("CgxPcmlnaW4ucHJvdG8iugEKBk9yaWdpbhIaCgR0eXBlGAEgASgOMgwuT3JpZ2luLlR5cGUSEwoLZGlzcGxheU5hbWUYAiABKAkSEgoKaWRlbnRpZmllchgDIAEoBRImCgpkZXZpY2VJbmZvGAQgASgLMhIuRGV2aWNlSW5mb01lc3NhZ2USFwoPaXNMb2NhbGx5SG9zdGVkGAUgASgIIioKBFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvY2FsEAESCgoGQ3VzdG9tEAI", [file_DeviceInfoMessage]);

/**
 * @generated from message Origin
 */
export type Origin = Message<"Origin"> & {
  /**
   * @generated from field: optional Origin.Type type = 1;
   */
  type: Origin_Type;

  /**
   * @generated from field: optional string displayName = 2;
   */
  displayName: string;

  /**
   * @generated from field: optional int32 identifier = 3;
   */
  identifier: number;

  /**
   * @generated from field: optional DeviceInfoMessage deviceInfo = 4;
   */
  deviceInfo?: DeviceInfoMessage;

  /**
   * @generated from field: optional bool isLocallyHosted = 5;
   */
  isLocallyHosted: boolean;
};

/**
 * Describes the message Origin.
 * Use `create(OriginSchema)` to create a new message.
 */
export const OriginSchema: GenMessage<Origin> = /*@__PURE__*/
  messageDesc(file_Origin, 0);

/**
 * @generated from enum Origin.Type
 */
export enum Origin_Type {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Local = 1;
   */
  Local = 1,

  /**
   * @generated from enum value: Custom = 2;
   */
  Custom = 2,
}

/**
 * Describes the enum Origin.Type.
 */
export const Origin_TypeSchema: GenEnum<Origin_Type> = /*@__PURE__*/
  enumDesc(file_Origin, 0, 0);

