// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackQueue.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ContentItem } from "./ContentItem_pb";
import { file_ContentItem } from "./ContentItem_pb";
import type { Dictionary } from "./Dictionary_pb";
import { file_Dictionary } from "./Dictionary_pb";
import type { PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import { file_PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackQueue.proto.
 */
export const file_PlaybackQueue: GenFile = /*@__PURE__*/
  fileDesc("ChNQbGF5YmFja1F1ZXVlLnByb3RvIvsCCg1QbGF5YmFja1F1ZXVlEhAKCGxvY2F0aW9uGAEgASgFEiIKDGNvbnRlbnRJdGVtcxgCIAMoCzIMLkNvbnRlbnRJdGVtEiYKB2NvbnRleHQYAyABKAsyFS5QbGF5YmFja1F1ZXVlQ29udGV4dBIRCglyZXF1ZXN0SUQYBCABKAkSJwoScmVzb2x2ZWRQbGF5ZXJQYXRoGAUgASgLMgsuUGxheWVyUGF0aBInCh9zZW5kaW5nUGxheWJhY2tRdWV1ZVRyYW5zYWN0aW9uGAYgASgIEhcKD3F1ZXVlSWRlbnRpZmllchgHIAEoCRIiCgxwYXJ0aWNpcGFudHMYCCADKAsyDC5Db250ZW50SXRlbRIbChNob21lVXNlcklkZW50aWZpZXJzGAkgAygJEh8KCnByb3BlcnRpZXMYCiABKAsyCy5EaWN0aW9uYXJ5EiwKF2F1eGlsaWFyeU5vd1BsYXlpbmdJbmZvGAsgASgLMgsuRGljdGlvbmFyeQ", [file_ContentItem, file_Dictionary, file_PlaybackQueueContext, file_PlayerPath]);

/**
 * @generated from message PlaybackQueue
 */
export type PlaybackQueue = Message<"PlaybackQueue"> & {
  /**
   * @generated from field: optional int32 location = 1;
   */
  location: number;

  /**
   * @generated from field: repeated ContentItem contentItems = 2;
   */
  contentItems: ContentItem[];

  /**
   * @generated from field: optional PlaybackQueueContext context = 3;
   */
  context?: PlaybackQueueContext;

  /**
   * @generated from field: optional string requestID = 4;
   */
  requestID: string;

  /**
   * @generated from field: optional PlayerPath resolvedPlayerPath = 5;
   */
  resolvedPlayerPath?: PlayerPath;

  /**
   * @generated from field: optional bool sendingPlaybackQueueTransaction = 6;
   */
  sendingPlaybackQueueTransaction: boolean;

  /**
   * @generated from field: optional string queueIdentifier = 7;
   */
  queueIdentifier: string;

  /**
   * @generated from field: repeated ContentItem participants = 8;
   */
  participants: ContentItem[];

  /**
   * @generated from field: repeated string homeUserIdentifiers = 9;
   */
  homeUserIdentifiers: string[];

  /**
   * @generated from field: optional Dictionary properties = 10;
   */
  properties?: Dictionary;

  /**
   * @generated from field: optional Dictionary auxiliaryNowPlayingInfo = 11;
   */
  auxiliaryNowPlayingInfo?: Dictionary;
};

/**
 * Describes the message PlaybackQueue.
 * Use `create(PlaybackQueueSchema)` to create a new message.
 */
export const PlaybackQueueSchema: GenMessage<PlaybackQueue> = /*@__PURE__*/
  messageDesc(file_PlaybackQueue, 0);

