// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file PlayerClientPropertiesMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlayerClientPropertiesMessage.proto.
 */
export const file_PlayerClientPropertiesMessage: GenFile = /*@__PURE__*/
  fileDesc("CiNQbGF5ZXJDbGllbnRQcm9wZXJ0aWVzTWVzc2FnZS5wcm90byJeCh1QbGF5ZXJDbGllbnRQcm9wZXJ0aWVzTWVzc2FnZRIfCgpwbGF5ZXJQYXRoGAEgASgLMgsuUGxheWVyUGF0aBIcChRsYXN0UGxheWluZ1RpbWVzdGFtcBgCIAEoATp2Ch1wbGF5ZXJDbGllbnRQcm9wZXJ0aWVzTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhWIAEoCzIeLlBsYXllckNsaWVudFByb3BlcnRpZXNNZXNzYWdlUh1wbGF5ZXJDbGllbnRQcm9wZXJ0aWVzTWVzc2FnZQ", [file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message PlayerClientPropertiesMessage
 */
export type PlayerClientPropertiesMessage = Message<"PlayerClientPropertiesMessage"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional double lastPlayingTimestamp = 2;
   */
  lastPlayingTimestamp: number;
};

/**
 * Describes the message PlayerClientPropertiesMessage.
 * Use `create(PlayerClientPropertiesMessageSchema)` to create a new message.
 */
export const PlayerClientPropertiesMessageSchema: GenMessage<PlayerClientPropertiesMessage> = /*@__PURE__*/
  messageDesc(file_PlayerClientPropertiesMessage, 0);

/**
 * @generated from extension: optional PlayerClientPropertiesMessage playerClientPropertiesMessage = 86;
 */
export const playerClientPropertiesMessage: GenExtension<ProtocolMessage, PlayerClientPropertiesMessage> = /*@__PURE__*/
  extDesc(file_PlayerClientPropertiesMessage, 0);

