// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionRequest.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Dictionary } from "./Dictionary_pb";
import { file_Dictionary } from "./Dictionary_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionRequest.proto.
 */
export const file_PlaybackSessionRequest: GenFile = /*@__PURE__*/
  fileDesc("ChxQbGF5YmFja1Nlc3Npb25SZXF1ZXN0LnByb3RvIrsBChZQbGF5YmFja1Nlc3Npb25SZXF1ZXN0EhEKCXJlcXVlc3RJRBgBIAEoCRISCgppZGVudGlmaWVyGAIgASgJEgwKBHR5cGUYBSABKAkSKgoVZGVzdGluYXRpb25QbGF5ZXJQYXRoGAYgASgLMgsuUGxheWVyUGF0aBIrChZkZXN0aW5hdGlvbkNvbW1hbmRJbmZvGAcgASgLMgsuRGljdGlvbmFyeRITCgtpc1ByZWZsaWdodBgIIAEoCA", [file_Dictionary, file_PlayerPath]);

/**
 * @generated from message PlaybackSessionRequest
 */
export type PlaybackSessionRequest = Message<"PlaybackSessionRequest"> & {
  /**
   * @generated from field: optional string requestID = 1;
   */
  requestID: string;

  /**
   * @generated from field: optional string identifier = 2;
   */
  identifier: string;

  /**
   * @generated from field: optional string type = 5;
   */
  type: string;

  /**
   * @generated from field: optional PlayerPath destinationPlayerPath = 6;
   */
  destinationPlayerPath?: PlayerPath;

  /**
   * @generated from field: optional Dictionary destinationCommandInfo = 7;
   */
  destinationCommandInfo?: Dictionary;

  /**
   * @generated from field: optional bool isPreflight = 8;
   */
  isPreflight: boolean;
};

/**
 * Describes the message PlaybackSessionRequest.
 * Use `create(PlaybackSessionRequestSchema)` to create a new message.
 */
export const PlaybackSessionRequestSchema: GenMessage<PlaybackSessionRequest> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionRequest, 0);

