// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateRequest.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ContentItem } from "./ContentItem_pb";
import { file_ContentItem } from "./ContentItem_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSessionMigrateRequestEvent } from "./PlaybackSessionMigrateRequestEvent_pb";
import { file_PlaybackSessionMigrateRequestEvent } from "./PlaybackSessionMigrateRequestEvent_pb";
import type { PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import { file_PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import type { SendCommandResultStatus } from "./SendCommandResultMessage_pb";
import { file_SendCommandResultMessage } from "./SendCommandResultMessage_pb";
import type { EndpointOptions_Enum, PlaybackState_Enum, RecipeType_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateRequest.proto.
 */
export const file_PlaybackSessionMigrateRequest: GenFile = /*@__PURE__*/
  fileDesc("CiNQbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdC5wcm90byL7BAodUGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlcXVlc3QSEQoJcmVxdWVzdElkGAEgASgJEhUKDXBsYXllck9wdGlvbnMYAiABKAUSLgoPZW5kcG9pbnRPcHRpb25zGAMgASgOMhUuRW5kcG9pbnRPcHRpb25zLkVudW0SMwoGZXZlbnRzGAQgAygLMiMuUGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlcXVlc3RFdmVudBIYChBwbGF5YmFja1Bvc2l0aW9uGAUgASgBEiEKC2NvbnRlbnRJdGVtGAYgASgLMgwuQ29udGVudEl0ZW0SHwoKcGxheWVyUGF0aBgHIAEoCzILLlBsYXllclBhdGgSKgoNcGxheWJhY2tTdGF0ZRgIIAEoDjITLlBsYXliYWNrU3RhdGUuRW51bRIUCgxwbGF5YmFja1JhdGUYCSABKAESNwoWcGxheWJhY2tTZXNzaW9uUmVxdWVzdBgKIAEoCzIXLlBsYXliYWNrU2Vzc2lvblJlcXVlc3QSGwoTYWxsb3dGYWRlVHJhbnNpdGlvbhgLIAEoCBIWCg5vcmlnaW5hdG9yVHlwZRgMIAEoDRIYChBkZXN0aW5hdGlvblR5cGVzGA0gASgNEhEKCWluaXRpYXRvchgOIAEoCRInChJyZXNvbHZlZFBsYXllclBhdGgYDyABKAsyCy5QbGF5ZXJQYXRoEkEKH3NldFBsYXliYWNrU2Vzc2lvbkNvbW1hbmRTdGF0dXMYECABKAsyGC5TZW5kQ29tbWFuZFJlc3VsdFN0YXR1cxIkCgpyZWNpcGVUeXBlGBEgASgOMhAuUmVjaXBlVHlwZS5FbnVt", [file_ContentItem, file_PlayerPath, file_PlaybackSessionMigrateRequestEvent, file_PlaybackSessionRequest, file_SendCommandResultMessage, file_Common]);

/**
 * @generated from message PlaybackSessionMigrateRequest
 */
export type PlaybackSessionMigrateRequest = Message<"PlaybackSessionMigrateRequest"> & {
  /**
   * @generated from field: optional string requestId = 1;
   */
  requestId: string;

  /**
   * @generated from field: optional int32 playerOptions = 2;
   */
  playerOptions: number;

  /**
   * @generated from field: optional EndpointOptions.Enum endpointOptions = 3;
   */
  endpointOptions: EndpointOptions_Enum;

  /**
   * @generated from field: repeated PlaybackSessionMigrateRequestEvent events = 4;
   */
  events: PlaybackSessionMigrateRequestEvent[];

  /**
   * @generated from field: optional double playbackPosition = 5;
   */
  playbackPosition: number;

  /**
   * @generated from field: optional ContentItem contentItem = 6;
   */
  contentItem?: ContentItem;

  /**
   * @generated from field: optional PlayerPath playerPath = 7;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional PlaybackState.Enum playbackState = 8;
   */
  playbackState: PlaybackState_Enum;

  /**
   * @generated from field: optional double playbackRate = 9;
   */
  playbackRate: number;

  /**
   * @generated from field: optional PlaybackSessionRequest playbackSessionRequest = 10;
   */
  playbackSessionRequest?: PlaybackSessionRequest;

  /**
   * @generated from field: optional bool allowFadeTransition = 11;
   */
  allowFadeTransition: boolean;

  /**
   * @generated from field: optional uint32 originatorType = 12;
   */
  originatorType: number;

  /**
   * @generated from field: optional uint32 destinationTypes = 13;
   */
  destinationTypes: number;

  /**
   * @generated from field: optional string initiator = 14;
   */
  initiator: string;

  /**
   * @generated from field: optional PlayerPath resolvedPlayerPath = 15;
   */
  resolvedPlayerPath?: PlayerPath;

  /**
   * @generated from field: optional SendCommandResultStatus setPlaybackSessionCommandStatus = 16;
   */
  setPlaybackSessionCommandStatus?: SendCommandResultStatus;

  /**
   * @generated from field: optional RecipeType.Enum recipeType = 17;
   */
  recipeType: RecipeType_Enum;
};

/**
 * Describes the message PlaybackSessionMigrateRequest.
 * Use `create(PlaybackSessionMigrateRequestSchema)` to create a new message.
 */
export const PlaybackSessionMigrateRequestSchema: GenMessage<PlaybackSessionMigrateRequest> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateRequest, 0);

