// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file PlaybackQueue.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ContentItem } from "./ContentItem_pb";
import { file_ContentItem } from "./ContentItem_pb";
import type { PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import { file_PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackQueue.proto.
 */
export const file_PlaybackQueue: GenFile = /*@__PURE__*/
  fileDesc("ChNQbGF5YmFja1F1ZXVlLnByb3RvIusBCg1QbGF5YmFja1F1ZXVlEhAKCGxvY2F0aW9uGAEgASgFEiIKDGNvbnRlbnRJdGVtcxgCIAMoCzIMLkNvbnRlbnRJdGVtEiYKB2NvbnRleHQYAyABKAsyFS5QbGF5YmFja1F1ZXVlQ29udGV4dBIRCglyZXF1ZXN0SWQYBCABKAkSJwoScmVzb2x2ZWRQbGF5ZXJQYXRoGAUgASgLMgsuUGxheWVyUGF0aBInCh9zZW5kaW5nUGxheWJhY2tRdWV1ZVRyYW5zYWN0aW9uGAYgASgIEhcKD3F1ZXVlSWRlbnRpZmllchgHIAEoCQ", [file_ContentItem, file_PlaybackQueueContext, file_PlayerPath]);

/**
 * @generated from message PlaybackQueue
 */
export type PlaybackQueue = Message<"PlaybackQueue"> & {
  /**
   * @generated from field: optional int32 location = 1;
   */
  location: number;

  /**
   * @generated from field: repeated ContentItem contentItems = 2;
   */
  contentItems: ContentItem[];

  /**
   * @generated from field: optional PlaybackQueueContext context = 3;
   */
  context?: PlaybackQueueContext;

  /**
   * @generated from field: optional string requestId = 4;
   */
  requestId: string;

  /**
   * @generated from field: optional PlayerPath resolvedPlayerPath = 5;
   */
  resolvedPlayerPath?: PlayerPath;

  /**
   * @generated from field: optional bool sendingPlaybackQueueTransaction = 6;
   */
  sendingPlaybackQueueTransaction: boolean;

  /**
   * @generated from field: optional string queueIdentifier = 7;
   */
  queueIdentifier: string;
};

/**
 * Describes the message PlaybackQueue.
 * Use `create(PlaybackQueueSchema)` to create a new message.
 */
export const PlaybackQueueSchema: GenMessage<PlaybackQueue> = /*@__PURE__*/
  messageDesc(file_PlaybackQueue, 0);

