// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateEndMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import { file_PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import type { Error } from "./Error_pb";
import { file_Error } from "./Error_pb";
import type { SendCommandResultStatus } from "./SendCommandResultMessage_pb";
import { file_SendCommandResultMessage } from "./SendCommandResultMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateEndMessage.proto.
 */
export const file_PlaybackSessionMigrateEndMessage: GenFile = /*@__PURE__*/
  fileDesc("CiZQbGF5YmFja1Nlc3Npb25NaWdyYXRlRW5kTWVzc2FnZS5wcm90byL0AQogUGxheWJhY2tTZXNzaW9uTWlncmF0ZUVuZE1lc3NhZ2USKAoHcmVxdWVzdBgBIAEoCzIXLlBsYXliYWNrU2Vzc2lvblJlcXVlc3QSHwoKcGxheWVyUGF0aBgCIAEoCzILLlBsYXllclBhdGgSEQoJZXJyb3JDb2RlGAMgASgDEhgKEGVycm9yRGVzY3JpcHRpb24YBCABKAkSFQoFZXJyb3IYBSABKAsyBi5FcnJvchJBCh9zZXRQbGF5YmFja1Nlc3Npb25Db21tYW5kU3RhdHVzGAYgASgLMhguU2VuZENvbW1hbmRSZXN1bHRTdGF0dXM6fwogcGxheWJhY2tTZXNzaW9uTWlncmF0ZUVuZE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYUCABKAsyIS5QbGF5YmFja1Nlc3Npb25NaWdyYXRlRW5kTWVzc2FnZVIgcGxheWJhY2tTZXNzaW9uTWlncmF0ZUVuZE1lc3NhZ2U", [file_ProtocolMessage, file_PlayerPath, file_PlaybackSessionRequest, file_Error, file_SendCommandResultMessage]);

/**
 * @generated from message PlaybackSessionMigrateEndMessage
 */
export type PlaybackSessionMigrateEndMessage = Message<"PlaybackSessionMigrateEndMessage"> & {
  /**
   * @generated from field: optional PlaybackSessionRequest request = 1;
   */
  request?: PlaybackSessionRequest;

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional int64 errorCode = 3;
   */
  errorCode: bigint;

  /**
   * @generated from field: optional string errorDescription = 4;
   */
  errorDescription: string;

  /**
   * @generated from field: optional Error error = 5;
   */
  error?: Error;

  /**
   * @generated from field: optional SendCommandResultStatus setPlaybackSessionCommandStatus = 6;
   */
  setPlaybackSessionCommandStatus?: SendCommandResultStatus;
};

/**
 * Describes the message PlaybackSessionMigrateEndMessage.
 * Use `create(PlaybackSessionMigrateEndMessageSchema)` to create a new message.
 */
export const PlaybackSessionMigrateEndMessageSchema: GenMessage<PlaybackSessionMigrateEndMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateEndMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionMigrateEndMessage playbackSessionMigrateEndMessage = 80;
 */
export const playbackSessionMigrateEndMessage: GenExtension<ProtocolMessage, PlaybackSessionMigrateEndMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionMigrateEndMessage, 0);

