// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file PlayerPath.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Origin } from "./Origin_pb";
import { file_Origin } from "./Origin_pb";
import type { NowPlayingClient } from "./NowPlayingClient_pb";
import { file_NowPlayingClient } from "./NowPlayingClient_pb";
import type { NowPlayingPlayer } from "./NowPlayingPlayer_pb";
import { file_NowPlayingPlayer } from "./NowPlayingPlayer_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlayerPath.proto.
 */
export const file_PlayerPath: GenFile = /*@__PURE__*/
  fileDesc("ChBQbGF5ZXJQYXRoLnByb3RvImsKClBsYXllclBhdGgSFwoGb3JpZ2luGAEgASgLMgcuT3JpZ2luEiEKBmNsaWVudBgCIAEoCzIRLk5vd1BsYXlpbmdDbGllbnQSIQoGcGxheWVyGAMgASgLMhEuTm93UGxheWluZ1BsYXllcg", [file_Origin, file_NowPlayingClient, file_NowPlayingPlayer]);

/**
 * @generated from message PlayerPath
 */
export type PlayerPath = Message<"PlayerPath"> & {
  /**
   * @generated from field: optional Origin origin = 1;
   */
  origin?: Origin;

  /**
   * @generated from field: optional NowPlayingClient client = 2;
   */
  client?: NowPlayingClient;

  /**
   * @generated from field: optional NowPlayingPlayer player = 3;
   */
  player?: NowPlayingPlayer;
};

/**
 * Describes the message PlayerPath.
 * Use `create(PlayerPathSchema)` to create a new message.
 */
export const PlayerPathSchema: GenMessage<PlayerPath> = /*@__PURE__*/
  messageDesc(file_PlayerPath, 0);

