// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import { file_PlaybackSessionRequest } from "./PlaybackSessionRequest_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionRequestMessage.proto.
 */
export const file_PlaybackSessionRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CiNQbGF5YmFja1Nlc3Npb25SZXF1ZXN0TWVzc2FnZS5wcm90byJqCh1QbGF5YmFja1Nlc3Npb25SZXF1ZXN0TWVzc2FnZRIoCgdyZXF1ZXN0GAEgASgLMhcuUGxheWJhY2tTZXNzaW9uUmVxdWVzdBIfCgpwbGF5ZXJQYXRoGAIgASgLMgsuUGxheWVyUGF0aDp2Ch1wbGF5YmFja1Nlc3Npb25SZXF1ZXN0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhJIAEoCzIeLlBsYXliYWNrU2Vzc2lvblJlcXVlc3RNZXNzYWdlUh1wbGF5YmFja1Nlc3Npb25SZXF1ZXN0TWVzc2FnZQ", [file_ProtocolMessage, file_PlayerPath, file_PlaybackSessionRequest]);

/**
 * @generated from message PlaybackSessionRequestMessage
 */
export type PlaybackSessionRequestMessage = Message<"PlaybackSessionRequestMessage"> & {
  /**
   * @generated from field: optional PlaybackSessionRequest request = 1;
   */
  request?: PlaybackSessionRequest;

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message PlaybackSessionRequestMessage.
 * Use `create(PlaybackSessionRequestMessageSchema)` to create a new message.
 */
export const PlaybackSessionRequestMessageSchema: GenMessage<PlaybackSessionRequestMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionRequestMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionRequestMessage playbackSessionRequestMessage = 73;
 */
export const playbackSessionRequestMessage: GenExtension<ProtocolMessage, PlaybackSessionRequestMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionRequestMessage, 0);

