// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateRequestEvent.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Dictionary } from "./Dictionary_pb";
import { file_Dictionary } from "./Dictionary_pb";
import type { Error } from "./Error_pb";
import { file_Error } from "./Error_pb";
import type { PlaybackSessionMigrateRequestEventRole_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateRequestEvent.proto.
 */
export const file_PlaybackSessionMigrateRequestEvent: GenFile = /*@__PURE__*/
  fileDesc("CihQbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdEV2ZW50LnByb3RvIuICCiJQbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdEV2ZW50EgwKBG5hbWUYASABKAkSFgoOc3RhcnRUaW1lc3RhbXAYAiABKAESFAoMZW5kVGltZXN0YW1wGAMgASgBEhEKCWVycm9yQ29kZRgFIAEoAxIYChBlcnJvckRlc2NyaXB0aW9uGAYgASgJEhUKBWVycm9yGAcgASgLMgYuRXJyb3ISOgoEcm9sZRgIIAEoDjIsLlBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXF1ZXN0RXZlbnRSb2xlLkVudW0SGgoFaW5wdXQYCSABKAsyCy5EaWN0aW9uYXJ5EhsKBm91dHB1dBgKIAEoCzILLkRpY3Rpb25hcnkSMwoGZXZlbnRzGAsgAygLMiMuUGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlcXVlc3RFdmVudBISCgppZGVudGlmaWVyGGQgASgN", [file_Dictionary, file_Error, file_Common]);

/**
 * @generated from message PlaybackSessionMigrateRequestEvent
 */
export type PlaybackSessionMigrateRequestEvent = Message<"PlaybackSessionMigrateRequestEvent"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional double startTimestamp = 2;
   */
  startTimestamp: number;

  /**
   * @generated from field: optional double endTimestamp = 3;
   */
  endTimestamp: number;

  /**
   * @generated from field: optional int64 errorCode = 5;
   */
  errorCode: bigint;

  /**
   * @generated from field: optional string errorDescription = 6;
   */
  errorDescription: string;

  /**
   * @generated from field: optional Error error = 7;
   */
  error?: Error;

  /**
   * @generated from field: optional PlaybackSessionMigrateRequestEventRole.Enum role = 8;
   */
  role: PlaybackSessionMigrateRequestEventRole_Enum;

  /**
   * @generated from field: optional Dictionary input = 9;
   */
  input?: Dictionary;

  /**
   * @generated from field: optional Dictionary output = 10;
   */
  output?: Dictionary;

  /**
   * @generated from field: repeated PlaybackSessionMigrateRequestEvent events = 11;
   */
  events: PlaybackSessionMigrateRequestEvent[];

  /**
   * @generated from field: optional uint32 identifier = 100;
   */
  identifier: number;
};

/**
 * Describes the message PlaybackSessionMigrateRequestEvent.
 * Use `create(PlaybackSessionMigrateRequestEventSchema)` to create a new message.
 */
export const PlaybackSessionMigrateRequestEventSchema: GenMessage<PlaybackSessionMigrateRequestEvent> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateRequestEvent, 0);

