// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file PlaybackQueueRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import { file_PlaybackQueueContext } from "./PlaybackQueueContext_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackQueueRequestMessage.proto.
 */
export const file_PlaybackQueueRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CiFQbGF5YmFja1F1ZXVlUmVxdWVzdE1lc3NhZ2UucHJvdG8i5AMKG1BsYXliYWNrUXVldWVSZXF1ZXN0TWVzc2FnZRIQCghsb2NhdGlvbhgBIAEoBRIOCgZsZW5ndGgYAiABKAUSFwoPaW5jbHVkZU1ldGFkYXRhGAMgASgIEhQKDGFydHdvcmtXaWR0aBgEIAEoARIVCg1hcnR3b3JrSGVpZ2h0GAUgASgBEhUKDWluY2x1ZGVMeXJpY3MYBiABKAgSFwoPaW5jbHVkZVNlY3Rpb25zGAcgASgIEhMKC2luY2x1ZGVJbmZvGAggASgIEh4KFmluY2x1ZGVMYW5ndWFnZU9wdGlvbnMYCSABKAgSJgoHY29udGV4dBgKIAEoCzIVLlBsYXliYWNrUXVldWVDb250ZXh0EhEKCXJlcXVlc3RJRBgLIAEoCRIeChZjb250ZW50SXRlbUlkZW50aWZpZXJzGAwgAygJEi8KJ3JldHVybkNvbnRlbnRJdGVtQXNzZXRzSW5Vc2VyQ29tcGxldGlvbhgNIAEoCBIfCgpwbGF5ZXJQYXRoGA4gASgLMgsuUGxheWVyUGF0aBIVCg1jYWNoaW5nUG9saWN5GA8gASgFEg0KBWxhYmVsGBAgASgJEiUKHWlzTGVnYWN5Tm93UGxheWluZ0luZm9SZXF1ZXN0GBEgASgIOnAKG3BsYXliYWNrUXVldWVSZXF1ZXN0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRglIAEoCzIcLlBsYXliYWNrUXVldWVSZXF1ZXN0TWVzc2FnZVIbcGxheWJhY2tRdWV1ZVJlcXVlc3RNZXNzYWdl", [file_ProtocolMessage, file_PlaybackQueueContext, file_PlayerPath]);

/**
 * @generated from message PlaybackQueueRequestMessage
 */
export type PlaybackQueueRequestMessage = Message<"PlaybackQueueRequestMessage"> & {
  /**
   * @generated from field: optional int32 location = 1;
   */
  location: number;

  /**
   * @generated from field: optional int32 length = 2;
   */
  length: number;

  /**
   * @generated from field: optional bool includeMetadata = 3;
   */
  includeMetadata: boolean;

  /**
   * @generated from field: optional double artworkWidth = 4;
   */
  artworkWidth: number;

  /**
   * @generated from field: optional double artworkHeight = 5;
   */
  artworkHeight: number;

  /**
   * @generated from field: optional bool includeLyrics = 6;
   */
  includeLyrics: boolean;

  /**
   * @generated from field: optional bool includeSections = 7;
   */
  includeSections: boolean;

  /**
   * @generated from field: optional bool includeInfo = 8;
   */
  includeInfo: boolean;

  /**
   * @generated from field: optional bool includeLanguageOptions = 9;
   */
  includeLanguageOptions: boolean;

  /**
   * @generated from field: optional PlaybackQueueContext context = 10;
   */
  context?: PlaybackQueueContext;

  /**
   * @generated from field: optional string requestID = 11;
   */
  requestID: string;

  /**
   * @generated from field: repeated string contentItemIdentifiers = 12;
   */
  contentItemIdentifiers: string[];

  /**
   * @generated from field: optional bool returnContentItemAssetsInUserCompletion = 13;
   */
  returnContentItemAssetsInUserCompletion: boolean;

  /**
   * @generated from field: optional PlayerPath playerPath = 14;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional int32 cachingPolicy = 15;
   */
  cachingPolicy: number;

  /**
   * @generated from field: optional string label = 16;
   */
  label: string;

  /**
   * @generated from field: optional bool isLegacyNowPlayingInfoRequest = 17;
   */
  isLegacyNowPlayingInfoRequest: boolean;
};

/**
 * Describes the message PlaybackQueueRequestMessage.
 * Use `create(PlaybackQueueRequestMessageSchema)` to create a new message.
 */
export const PlaybackQueueRequestMessageSchema: GenMessage<PlaybackQueueRequestMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackQueueRequestMessage, 0);

/**
 * @generated from extension: optional PlaybackQueueRequestMessage playbackQueueRequestMessage = 37;
 */
export const playbackQueueRequestMessage: GenExtension<ProtocolMessage, PlaybackQueueRequestMessage> = /*@__PURE__*/
  extDesc(file_PlaybackQueueRequestMessage, 0);

