// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigratePostMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_Error } from "./Error_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import { file_PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import type { ErrorCode, ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigratePostMessage.proto.
 */
export const file_PlaybackSessionMigratePostMessage: GenFile = /*@__PURE__*/
  fileDesc("CidQbGF5YmFja1Nlc3Npb25NaWdyYXRlUG9zdE1lc3NhZ2UucHJvdG8ixgEKIVBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVQb3N0TWVzc2FnZRIvCgdyZXF1ZXN0GAEgASgLMh4uUGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlcXVlc3QSHwoKcGxheWVyUGF0aBgCIAEoCzILLlBsYXllclBhdGgSGQoFZXJyb3IYAyABKAsyCi5FcnJvckNvZGUSDwoHbWV0cmljcxgEIAEoDBIjChtzZXRQbGF5YmFja1Nlc3Npb25Db21tYW5kSUQYBSABKAk6ggEKIXBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVQb3N0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhvIAEoCzIiLlBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVQb3N0TWVzc2FnZVIhcGxheWJhY2tTZXNzaW9uTWlncmF0ZVBvc3RNZXNzYWdl", [file_Error, file_PlayerPath, file_PlaybackSessionMigrateRequest, file_ProtocolMessage]);

/**
 * @generated from message PlaybackSessionMigratePostMessage
 */
export type PlaybackSessionMigratePostMessage = Message<"PlaybackSessionMigratePostMessage"> & {
  /**
   * @generated from field: optional PlaybackSessionMigrateRequest request = 1;
   */
  request?: PlaybackSessionMigrateRequest;

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional ErrorCode error = 3;
   */
  error?: ErrorCode;

  /**
   * @generated from field: optional bytes metrics = 4;
   */
  metrics: Uint8Array;

  /**
   * @generated from field: optional string setPlaybackSessionCommandID = 5;
   */
  setPlaybackSessionCommandID: string;
};

/**
 * Describes the message PlaybackSessionMigratePostMessage.
 * Use `create(PlaybackSessionMigratePostMessageSchema)` to create a new message.
 */
export const PlaybackSessionMigratePostMessageSchema: GenMessage<PlaybackSessionMigratePostMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigratePostMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionMigratePostMessage playbackSessionMigratePostMessage = 111;
 */
export const playbackSessionMigratePostMessage: GenExtension<ProtocolMessage, PlaybackSessionMigratePostMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionMigratePostMessage, 0);

