// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackQueueParticipant.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { UserIdentity } from "./UserIdentity_pb";
import { file_UserIdentity } from "./UserIdentity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackQueueParticipant.proto.
 */
export const file_PlaybackQueueParticipant: GenFile = /*@__PURE__*/
  fileDesc("Ch5QbGF5YmFja1F1ZXVlUGFydGljaXBhbnQucHJvdG8iTwoYUGxheWJhY2tRdWV1ZVBhcnRpY2lwYW50EhIKCmlkZW50aWZpZXIYASABKAkSHwoIaWRlbnRpdHkYAiABKAsyDS5Vc2VySWRlbnRpdHk", [file_UserIdentity]);

/**
 * @generated from message PlaybackQueueParticipant
 */
export type PlaybackQueueParticipant = Message<"PlaybackQueueParticipant"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional UserIdentity identity = 2;
   */
  identity?: UserIdentity;
};

/**
 * Describes the message PlaybackQueueParticipant.
 * Use `create(PlaybackQueueParticipantSchema)` to create a new message.
 */
export const PlaybackQueueParticipantSchema: GenMessage<PlaybackQueueParticipant> = /*@__PURE__*/
  messageDesc(file_PlaybackQueueParticipant, 0);

