// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateResponseMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import { file_PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateResponseMessage.proto.
 */
export const file_PlaybackSessionMigrateResponseMessage: GenFile = /*@__PURE__*/
  fileDesc("CitQbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVzcG9uc2VNZXNzYWdlLnByb3RvIlgKJVBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXNwb25zZU1lc3NhZ2USLwoHcmVxdWVzdBgBIAEoCzIeLlBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXF1ZXN0Oo4BCiVwbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVzcG9uc2VNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGE0gASgLMiYuUGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlc3BvbnNlTWVzc2FnZVIlcGxheWJhY2tTZXNzaW9uTWlncmF0ZVJlc3BvbnNlTWVzc2FnZQ", [file_ProtocolMessage, file_PlaybackSessionMigrateRequest]);

/**
 * @generated from message PlaybackSessionMigrateResponseMessage
 */
export type PlaybackSessionMigrateResponseMessage = Message<"PlaybackSessionMigrateResponseMessage"> & {
  /**
   * @generated from field: optional PlaybackSessionMigrateRequest request = 1;
   */
  request?: PlaybackSessionMigrateRequest;
};

/**
 * Describes the message PlaybackSessionMigrateResponseMessage.
 * Use `create(PlaybackSessionMigrateResponseMessageSchema)` to create a new message.
 */
export const PlaybackSessionMigrateResponseMessageSchema: GenMessage<PlaybackSessionMigrateResponseMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateResponseMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionMigrateResponseMessage playbackSessionMigrateResponseMessage = 77;
 */
export const playbackSessionMigrateResponseMessage: GenExtension<ProtocolMessage, PlaybackSessionMigrateResponseMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionMigrateResponseMessage, 0);

