// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateBeginMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSessionRequestMessage } from "./PlaybackSessionRequestMessage_pb";
import { file_PlaybackSessionRequestMessage } from "./PlaybackSessionRequestMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateBeginMessage.proto.
 */
export const file_PlaybackSessionMigrateBeginMessage: GenFile = /*@__PURE__*/
  fileDesc("CihQbGF5YmFja1Nlc3Npb25NaWdyYXRlQmVnaW5NZXNzYWdlLnByb3RvInYKIlBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVCZWdpbk1lc3NhZ2USLwoHcmVxdWVzdBgBIAEoCzIeLlBsYXliYWNrU2Vzc2lvblJlcXVlc3RNZXNzYWdlEh8KCnBsYXllclBhdGgYAiABKAsyCy5QbGF5ZXJQYXRoOoUBCiJwbGF5YmFja1Nlc3Npb25NaWdyYXRlQmVnaW5NZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGE8gASgLMiMuUGxheWJhY2tTZXNzaW9uTWlncmF0ZUJlZ2luTWVzc2FnZVIicGxheWJhY2tTZXNzaW9uTWlncmF0ZUJlZ2luTWVzc2FnZQ", [file_ProtocolMessage, file_PlayerPath, file_PlaybackSessionRequestMessage]);

/**
 * @generated from message PlaybackSessionMigrateBeginMessage
 */
export type PlaybackSessionMigrateBeginMessage = Message<"PlaybackSessionMigrateBeginMessage"> & {
  /**
   * @generated from field: optional PlaybackSessionRequestMessage request = 1;
   */
  request?: PlaybackSessionRequestMessage;

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message PlaybackSessionMigrateBeginMessage.
 * Use `create(PlaybackSessionMigrateBeginMessageSchema)` to create a new message.
 */
export const PlaybackSessionMigrateBeginMessageSchema: GenMessage<PlaybackSessionMigrateBeginMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateBeginMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionMigrateBeginMessage playbackSessionMigrateBeginMessage = 79;
 */
export const playbackSessionMigrateBeginMessage: GenExtension<ProtocolMessage, PlaybackSessionMigrateBeginMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionMigrateBeginMessage, 0);

