// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PlaybackSessionMigrateRequestMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackSession } from "./PlaybackSession_pb";
import { file_PlaybackSession } from "./PlaybackSession_pb";
import type { PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import { file_PlaybackSessionMigrateRequest } from "./PlaybackSessionMigrateRequest_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PlaybackSessionMigrateRequestMessage.proto.
 */
export const file_PlaybackSessionMigrateRequestMessage: GenFile = /*@__PURE__*/
  fileDesc("CipQbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdE1lc3NhZ2UucHJvdG8iowEKJFBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXF1ZXN0TWVzc2FnZRIpCg9wbGF5YmFja1Nlc3Npb24YASABKAsyEC5QbGF5YmFja1Nlc3Npb24SLwoHcmVxdWVzdBgCIAEoCzIeLlBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXF1ZXN0Eh8KCnBsYXllclBhdGgYAyABKAsyCy5QbGF5ZXJQYXRoOosBCiRwbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYTCABKAsyJS5QbGF5YmFja1Nlc3Npb25NaWdyYXRlUmVxdWVzdE1lc3NhZ2VSJHBsYXliYWNrU2Vzc2lvbk1pZ3JhdGVSZXF1ZXN0TWVzc2FnZQ", [file_ProtocolMessage, file_PlayerPath, file_PlaybackSession, file_PlaybackSessionMigrateRequest]);

/**
 * @generated from message PlaybackSessionMigrateRequestMessage
 */
export type PlaybackSessionMigrateRequestMessage = Message<"PlaybackSessionMigrateRequestMessage"> & {
  /**
   * @generated from field: optional PlaybackSession playbackSession = 1;
   */
  playbackSession?: PlaybackSession;

  /**
   * @generated from field: optional PlaybackSessionMigrateRequest request = 2;
   */
  request?: PlaybackSessionMigrateRequest;

  /**
   * @generated from field: optional PlayerPath playerPath = 3;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message PlaybackSessionMigrateRequestMessage.
 * Use `create(PlaybackSessionMigrateRequestMessageSchema)` to create a new message.
 */
export const PlaybackSessionMigrateRequestMessageSchema: GenMessage<PlaybackSessionMigrateRequestMessage> = /*@__PURE__*/
  messageDesc(file_PlaybackSessionMigrateRequestMessage, 0);

/**
 * @generated from extension: optional PlaybackSessionMigrateRequestMessage playbackSessionMigrateRequestMessage = 76;
 */
export const playbackSessionMigrateRequestMessage: GenExtension<ProtocolMessage, PlaybackSessionMigrateRequestMessage> = /*@__PURE__*/
  extDesc(file_PlaybackSessionMigrateRequestMessage, 0);

