// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PresentRouteAuthorizationStatusMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PresentRouteAuthorizationStatusMessage.proto.
 */
export const file_PresentRouteAuthorizationStatusMessage: GenFile = /*@__PURE__*/
  fileDesc("CixQcmVzZW50Um91dGVBdXRob3JpemF0aW9uU3RhdHVzTWVzc2FnZS5wcm90byJHCiZQcmVzZW50Um91dGVBdXRob3JpemF0aW9uU3RhdHVzTWVzc2FnZRINCgVyb3V0ZRgBIAEoCRIOCgZzdGF0dXMYAiABKAU6kQEKJnByZXNlbnRSb3V0ZUF1dGhvcml6YXRpb25TdGF0dXNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGEEgASgLMicuUHJlc2VudFJvdXRlQXV0aG9yaXphdGlvblN0YXR1c01lc3NhZ2VSJnByZXNlbnRSb3V0ZUF1dGhvcml6YXRpb25TdGF0dXNNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message PresentRouteAuthorizationStatusMessage
 */
export type PresentRouteAuthorizationStatusMessage = Message<"PresentRouteAuthorizationStatusMessage"> & {
  /**
   * @generated from field: optional string route = 1;
   */
  route: string;

  /**
   * @generated from field: optional int32 status = 2;
   */
  status: number;
};

/**
 * Describes the message PresentRouteAuthorizationStatusMessage.
 * Use `create(PresentRouteAuthorizationStatusMessageSchema)` to create a new message.
 */
export const PresentRouteAuthorizationStatusMessageSchema: GenMessage<PresentRouteAuthorizationStatusMessage> = /*@__PURE__*/
  messageDesc(file_PresentRouteAuthorizationStatusMessage, 0);

/**
 * @generated from extension: optional PresentRouteAuthorizationStatusMessage presentRouteAuthorizationStatusMessage = 65;
 */
export const presentRouteAuthorizationStatusMessage: GenExtension<ProtocolMessage, PresentRouteAuthorizationStatusMessage> = /*@__PURE__*/
  extDesc(file_PresentRouteAuthorizationStatusMessage, 0);

