// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PromptForRouteAuthorizationMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PromptForRouteAuthorizationMessage.proto.
 */
export const file_PromptForRouteAuthorizationMessage: GenFile = /*@__PURE__*/
  fileDesc("CihQcm9tcHRGb3JSb3V0ZUF1dGhvcml6YXRpb25NZXNzYWdlLnByb3RvIkYKIlByb21wdEZvclJvdXRlQXV0aG9yaXphdGlvbk1lc3NhZ2USDQoFcm91dGUYASABKAkSEQoJaW5wdXRUeXBlGAIgASgFOoUBCiJwcm9tcHRGb3JSb3V0ZUF1dGhvcml6YXRpb25NZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGD8gASgLMiMuUHJvbXB0Rm9yUm91dGVBdXRob3JpemF0aW9uTWVzc2FnZVIicHJvbXB0Rm9yUm91dGVBdXRob3JpemF0aW9uTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message PromptForRouteAuthorizationMessage
 */
export type PromptForRouteAuthorizationMessage = Message<"PromptForRouteAuthorizationMessage"> & {
  /**
   * @generated from field: optional string route = 1;
   */
  route: string;

  /**
   * @generated from field: optional int32 inputType = 2;
   */
  inputType: number;
};

/**
 * Describes the message PromptForRouteAuthorizationMessage.
 * Use `create(PromptForRouteAuthorizationMessageSchema)` to create a new message.
 */
export const PromptForRouteAuthorizationMessageSchema: GenMessage<PromptForRouteAuthorizationMessage> = /*@__PURE__*/
  messageDesc(file_PromptForRouteAuthorizationMessage, 0);

/**
 * @generated from extension: optional PromptForRouteAuthorizationMessage promptForRouteAuthorizationMessage = 63;
 */
export const promptForRouteAuthorizationMessage: GenExtension<ProtocolMessage, PromptForRouteAuthorizationMessage> = /*@__PURE__*/
  extDesc(file_PromptForRouteAuthorizationMessage, 0);

