// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file PromptForRouteAuthorizationResponseMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PromptForRouteAuthorizationResponseMessage.proto.
 */
export const file_PromptForRouteAuthorizationResponseMessage: GenFile = /*@__PURE__*/
  fileDesc("CjBQcm9tcHRGb3JSb3V0ZUF1dGhvcml6YXRpb25SZXNwb25zZU1lc3NhZ2UucHJvdG8iPgoqUHJvbXB0Rm9yUm91dGVBdXRob3JpemF0aW9uUmVzcG9uc2VNZXNzYWdlEhAKCHJlc3BvbnNlGAEgASgMOp0BCipwcm9tcHRGb3JSb3V0ZUF1dGhvcml6YXRpb25SZXNwb25zZU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYQCABKAsyKy5Qcm9tcHRGb3JSb3V0ZUF1dGhvcml6YXRpb25SZXNwb25zZU1lc3NhZ2VSKnByb21wdEZvclJvdXRlQXV0aG9yaXphdGlvblJlc3BvbnNlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message PromptForRouteAuthorizationResponseMessage
 */
export type PromptForRouteAuthorizationResponseMessage = Message<"PromptForRouteAuthorizationResponseMessage"> & {
  /**
   * @generated from field: optional bytes response = 1;
   */
  response: Uint8Array;
};

/**
 * Describes the message PromptForRouteAuthorizationResponseMessage.
 * Use `create(PromptForRouteAuthorizationResponseMessageSchema)` to create a new message.
 */
export const PromptForRouteAuthorizationResponseMessageSchema: GenMessage<PromptForRouteAuthorizationResponseMessage> = /*@__PURE__*/
  messageDesc(file_PromptForRouteAuthorizationResponseMessage, 0);

/**
 * @generated from extension: optional PromptForRouteAuthorizationResponseMessage promptForRouteAuthorizationResponseMessage = 64;
 */
export const promptForRouteAuthorizationResponseMessage: GenExtension<ProtocolMessage, PromptForRouteAuthorizationResponseMessage> = /*@__PURE__*/
  extDesc(file_PromptForRouteAuthorizationResponseMessage, 0);

