// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ReceivedCommand.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CommandOptions } from "./CommandOptions_pb";
import { file_CommandOptions } from "./CommandOptions_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ReceivedCommand.proto.
 */
export const file_ReceivedCommand: GenFile = /*@__PURE__*/
  fileDesc("ChVSZWNlaXZlZENvbW1hbmQucHJvdG8iNgoZUmVjZWl2ZWRDb21tYW5kQXBwT3B0aW9ucxIZChFsYXVuY2hBcHBsaWNhdGlvbhgBIAEoCCKoAgoPUmVjZWl2ZWRDb21tYW5kEg8KB2NvbW1hbmQYASABKAUSIAoHb3B0aW9ucxgCIAEoCzIPLkNvbW1hbmRPcHRpb25zEi4KCmFwcE9wdGlvbnMYAyABKAsyGi5SZWNlaXZlZENvbW1hbmRBcHBPcHRpb25zEh8KCnBsYXllclBhdGgYBCABKAsyCy5QbGF5ZXJQYXRoEhEKCW9yaWdpblVJRBgFIAEoCRIgChhyZW1vdGVDb250cm9sSW50ZXJmYWNlSUQYBiABKAkSGgoSc2VuZGVyQXBwRGlzcGxheUlEGAcgASgJEh8KF2Rlc3RpbmF0aW9uQXBwRGlzcGxheUlEGAggASgJEh8KF2Rlc3RpbmF0aW9uQXBwUHJvY2Vzc0lEGAkgASgF", [file_CommandOptions, file_PlayerPath]);

/**
 * @generated from message ReceivedCommandAppOptions
 */
export type ReceivedCommandAppOptions = Message<"ReceivedCommandAppOptions"> & {
  /**
   * @generated from field: optional bool launchApplication = 1;
   */
  launchApplication: boolean;
};

/**
 * Describes the message ReceivedCommandAppOptions.
 * Use `create(ReceivedCommandAppOptionsSchema)` to create a new message.
 */
export const ReceivedCommandAppOptionsSchema: GenMessage<ReceivedCommandAppOptions> = /*@__PURE__*/
  messageDesc(file_ReceivedCommand, 0);

/**
 * @generated from message ReceivedCommand
 */
export type ReceivedCommand = Message<"ReceivedCommand"> & {
  /**
   * @generated from field: optional int32 command = 1;
   */
  command: number;

  /**
   * @generated from field: optional CommandOptions options = 2;
   */
  options?: CommandOptions;

  /**
   * @generated from field: optional ReceivedCommandAppOptions appOptions = 3;
   */
  appOptions?: ReceivedCommandAppOptions;

  /**
   * @generated from field: optional PlayerPath playerPath = 4;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional string originUID = 5;
   */
  originUID: string;

  /**
   * @generated from field: optional string remoteControlInterfaceID = 6;
   */
  remoteControlInterfaceID: string;

  /**
   * @generated from field: optional string senderAppDisplayID = 7;
   */
  senderAppDisplayID: string;

  /**
   * @generated from field: optional string destinationAppDisplayID = 8;
   */
  destinationAppDisplayID: string;

  /**
   * @generated from field: optional int32 destinationAppProcessID = 9;
   */
  destinationAppProcessID: number;
};

/**
 * Describes the message ReceivedCommand.
 * Use `create(ReceivedCommandSchema)` to create a new message.
 */
export const ReceivedCommandSchema: GenMessage<ReceivedCommand> = /*@__PURE__*/
  messageDesc(file_ReceivedCommand, 1);

