// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file RegisterVoiceInputDeviceMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { VoiceInputDeviceDescriptor } from "./VoiceInputDeviceDescriptorMessage_pb";
import { file_VoiceInputDeviceDescriptorMessage } from "./VoiceInputDeviceDescriptorMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterVoiceInputDeviceMessage.proto.
 */
export const file_RegisterVoiceInputDeviceMessage: GenFile = /*@__PURE__*/
  fileDesc("CiVSZWdpc3RlclZvaWNlSW5wdXREZXZpY2VNZXNzYWdlLnByb3RvIlgKH1JlZ2lzdGVyVm9pY2VJbnB1dERldmljZU1lc3NhZ2USNQoQZGV2aWNlRGVzY3JpcHRvchgBIAEoCzIbLlZvaWNlSW5wdXREZXZpY2VEZXNjcmlwdG9yOnwKH3JlZ2lzdGVyVm9pY2VJbnB1dERldmljZU1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYISABKAsyIC5SZWdpc3RlclZvaWNlSW5wdXREZXZpY2VNZXNzYWdlUh9yZWdpc3RlclZvaWNlSW5wdXREZXZpY2VNZXNzYWdl", [file_ProtocolMessage, file_VoiceInputDeviceDescriptorMessage]);

/**
 * @generated from message RegisterVoiceInputDeviceMessage
 */
export type RegisterVoiceInputDeviceMessage = Message<"RegisterVoiceInputDeviceMessage"> & {
  /**
   * @generated from field: optional VoiceInputDeviceDescriptor deviceDescriptor = 1;
   */
  deviceDescriptor?: VoiceInputDeviceDescriptor;
};

/**
 * Describes the message RegisterVoiceInputDeviceMessage.
 * Use `create(RegisterVoiceInputDeviceMessageSchema)` to create a new message.
 */
export const RegisterVoiceInputDeviceMessageSchema: GenMessage<RegisterVoiceInputDeviceMessage> = /*@__PURE__*/
  messageDesc(file_RegisterVoiceInputDeviceMessage, 0);

/**
 * @generated from extension: optional RegisterVoiceInputDeviceMessage registerVoiceInputDeviceMessage = 33;
 */
export const registerVoiceInputDeviceMessage: GenExtension<ProtocolMessage, RegisterVoiceInputDeviceMessage> = /*@__PURE__*/
  extDesc(file_RegisterVoiceInputDeviceMessage, 0);

