// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file RegisterHIDDeviceMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { VirtualTouchDeviceDescriptor } from "./VirtualTouchDeviceDescriptorMessage_pb";
import { file_VirtualTouchDeviceDescriptorMessage } from "./VirtualTouchDeviceDescriptorMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterHIDDeviceMessage.proto.
 */
export const file_RegisterHIDDeviceMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch5SZWdpc3RlckhJRERldmljZU1lc3NhZ2UucHJvdG8iUwoYUmVnaXN0ZXJISUREZXZpY2VNZXNzYWdlEjcKEGRldmljZURlc2NyaXB0b3IYASABKAsyHS5WaXJ0dWFsVG91Y2hEZXZpY2VEZXNjcmlwdG9yOmcKGHJlZ2lzdGVySElERGV2aWNlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgLIAEoCzIZLlJlZ2lzdGVySElERGV2aWNlTWVzc2FnZVIYcmVnaXN0ZXJISUREZXZpY2VNZXNzYWdl", [file_ProtocolMessage, file_VirtualTouchDeviceDescriptorMessage]);

/**
 * @generated from message RegisterHIDDeviceMessage
 */
export type RegisterHIDDeviceMessage = Message<"RegisterHIDDeviceMessage"> & {
  /**
   * @generated from field: optional VirtualTouchDeviceDescriptor deviceDescriptor = 1;
   */
  deviceDescriptor?: VirtualTouchDeviceDescriptor;
};

/**
 * Describes the message RegisterHIDDeviceMessage.
 * Use `create(RegisterHIDDeviceMessageSchema)` to create a new message.
 */
export const RegisterHIDDeviceMessageSchema: GenMessage<RegisterHIDDeviceMessage> = /*@__PURE__*/
  messageDesc(file_RegisterHIDDeviceMessage, 0);

/**
 * @generated from extension: optional RegisterHIDDeviceMessage registerHIDDeviceMessage = 11;
 */
export const registerHIDDeviceMessage: GenExtension<ProtocolMessage, RegisterHIDDeviceMessage> = /*@__PURE__*/
  extDesc(file_RegisterHIDDeviceMessage, 0);

