// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file RegisterHIDDeviceResultMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterHIDDeviceResultMessage.proto.
 */
export const file_RegisterHIDDeviceResultMessage: GenFile = /*@__PURE__*/
  fileDesc("CiRSZWdpc3RlckhJRERldmljZVJlc3VsdE1lc3NhZ2UucHJvdG8iTQoeUmVnaXN0ZXJISUREZXZpY2VSZXN1bHRNZXNzYWdlEhEKCWVycm9yQ29kZRgBIAEoBRIYChBkZXZpY2VJZGVudGlmaWVyGAIgASgFOnkKHnJlZ2lzdGVySElERGV2aWNlUmVzdWx0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgMIAEoCzIfLlJlZ2lzdGVySElERGV2aWNlUmVzdWx0TWVzc2FnZVIecmVnaXN0ZXJISUREZXZpY2VSZXN1bHRNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message RegisterHIDDeviceResultMessage
 */
export type RegisterHIDDeviceResultMessage = Message<"RegisterHIDDeviceResultMessage"> & {
  /**
   * @generated from field: optional int32 errorCode = 1;
   */
  errorCode: number;

  /**
   * @generated from field: optional int32 deviceIdentifier = 2;
   */
  deviceIdentifier: number;
};

/**
 * Describes the message RegisterHIDDeviceResultMessage.
 * Use `create(RegisterHIDDeviceResultMessageSchema)` to create a new message.
 */
export const RegisterHIDDeviceResultMessageSchema: GenMessage<RegisterHIDDeviceResultMessage> = /*@__PURE__*/
  messageDesc(file_RegisterHIDDeviceResultMessage, 0);

/**
 * @generated from extension: optional RegisterHIDDeviceResultMessage registerHIDDeviceResultMessage = 12;
 */
export const registerHIDDeviceResultMessage: GenExtension<ProtocolMessage, RegisterHIDDeviceResultMessage> = /*@__PURE__*/
  extDesc(file_RegisterHIDDeviceResultMessage, 0);

