// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file RegisterVoiceInputDeviceResponseMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterVoiceInputDeviceResponseMessage.proto.
 */
export const file_RegisterVoiceInputDeviceResponseMessage: GenFile = /*@__PURE__*/
  fileDesc("Ci1SZWdpc3RlclZvaWNlSW5wdXREZXZpY2VSZXNwb25zZU1lc3NhZ2UucHJvdG8iTgonUmVnaXN0ZXJWb2ljZUlucHV0RGV2aWNlUmVzcG9uc2VNZXNzYWdlEhAKCGRldmljZUlEGAEgASgFEhEKCWVycm9yQ29kZRgCIAEoBTqUAQoncmVnaXN0ZXJWb2ljZUlucHV0RGV2aWNlUmVzcG9uc2VNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGCIgASgLMiguUmVnaXN0ZXJWb2ljZUlucHV0RGV2aWNlUmVzcG9uc2VNZXNzYWdlUidyZWdpc3RlclZvaWNlSW5wdXREZXZpY2VSZXNwb25zZU1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message RegisterVoiceInputDeviceResponseMessage
 */
export type RegisterVoiceInputDeviceResponseMessage = Message<"RegisterVoiceInputDeviceResponseMessage"> & {
  /**
   * @generated from field: optional int32 deviceID = 1;
   */
  deviceID: number;

  /**
   * @generated from field: optional int32 errorCode = 2;
   */
  errorCode: number;
};

/**
 * Describes the message RegisterVoiceInputDeviceResponseMessage.
 * Use `create(RegisterVoiceInputDeviceResponseMessageSchema)` to create a new message.
 */
export const RegisterVoiceInputDeviceResponseMessageSchema: GenMessage<RegisterVoiceInputDeviceResponseMessage> = /*@__PURE__*/
  messageDesc(file_RegisterVoiceInputDeviceResponseMessage, 0);

/**
 * @generated from extension: optional RegisterVoiceInputDeviceResponseMessage registerVoiceInputDeviceResponseMessage = 34;
 */
export const registerVoiceInputDeviceResponseMessage: GenExtension<ProtocolMessage, RegisterVoiceInputDeviceResponseMessage> = /*@__PURE__*/
  extDesc(file_RegisterVoiceInputDeviceResponseMessage, 0);

