// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file RegisterGameControllerMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { GameControllerProperties } from "./GameControllerPropertiesMessage_pb";
import { file_GameControllerPropertiesMessage } from "./GameControllerPropertiesMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterGameControllerMessage.proto.
 */
export const file_RegisterGameControllerMessage: GenFile = /*@__PURE__*/
  fileDesc("CiNSZWdpc3RlckdhbWVDb250cm9sbGVyTWVzc2FnZS5wcm90byJOCh1SZWdpc3RlckdhbWVDb250cm9sbGVyTWVzc2FnZRItCgpwcm9wZXJ0aWVzGAEgASgLMhkuR2FtZUNvbnRyb2xsZXJQcm9wZXJ0aWVzOnYKHXJlZ2lzdGVyR2FtZUNvbnRyb2xsZXJNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGBggASgLMh4uUmVnaXN0ZXJHYW1lQ29udHJvbGxlck1lc3NhZ2VSHXJlZ2lzdGVyR2FtZUNvbnRyb2xsZXJNZXNzYWdl", [file_ProtocolMessage, file_GameControllerPropertiesMessage]);

/**
 * @generated from message RegisterGameControllerMessage
 */
export type RegisterGameControllerMessage = Message<"RegisterGameControllerMessage"> & {
  /**
   * @generated from field: optional GameControllerProperties properties = 1;
   */
  properties?: GameControllerProperties;
};

/**
 * Describes the message RegisterGameControllerMessage.
 * Use `create(RegisterGameControllerMessageSchema)` to create a new message.
 */
export const RegisterGameControllerMessageSchema: GenMessage<RegisterGameControllerMessage> = /*@__PURE__*/
  messageDesc(file_RegisterGameControllerMessage, 0);

/**
 * @generated from extension: optional RegisterGameControllerMessage registerGameControllerMessage = 24;
 */
export const registerGameControllerMessage: GenExtension<ProtocolMessage, RegisterGameControllerMessage> = /*@__PURE__*/
  extDesc(file_RegisterGameControllerMessage, 0);

