// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file RegisterForGameControllerEventsMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RegisterForGameControllerEventsMessage.proto.
 */
export const file_RegisterForGameControllerEventsMessage: GenFile = /*@__PURE__*/
  fileDesc("CixSZWdpc3RlckZvckdhbWVDb250cm9sbGVyRXZlbnRzTWVzc2FnZS5wcm90byK8AQomUmVnaXN0ZXJGb3JHYW1lQ29udHJvbGxlckV2ZW50c01lc3NhZ2USTgoOaW5wdXRNb2RlRmxhZ3MYASABKA4yNi5SZWdpc3RlckZvckdhbWVDb250cm9sbGVyRXZlbnRzTWVzc2FnZS5JbnB1dE1vZGVGbGFncyJCCg5JbnB1dE1vZGVGbGFncxIICgROb25lEAASCgoGTW90aW9uEAESCwoHQnV0dG9ucxACEg0KCURpZ2l0aXplchADOpEBCiZyZWdpc3RlckZvckdhbWVDb250cm9sbGVyRXZlbnRzTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgbIAEoCzInLlJlZ2lzdGVyRm9yR2FtZUNvbnRyb2xsZXJFdmVudHNNZXNzYWdlUiZyZWdpc3RlckZvckdhbWVDb250cm9sbGVyRXZlbnRzTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message RegisterForGameControllerEventsMessage
 */
export type RegisterForGameControllerEventsMessage = Message<"RegisterForGameControllerEventsMessage"> & {
  /**
   * @generated from field: optional RegisterForGameControllerEventsMessage.InputModeFlags inputModeFlags = 1;
   */
  inputModeFlags: RegisterForGameControllerEventsMessage_InputModeFlags;
};

/**
 * Describes the message RegisterForGameControllerEventsMessage.
 * Use `create(RegisterForGameControllerEventsMessageSchema)` to create a new message.
 */
export const RegisterForGameControllerEventsMessageSchema: GenMessage<RegisterForGameControllerEventsMessage> = /*@__PURE__*/
  messageDesc(file_RegisterForGameControllerEventsMessage, 0);

/**
 * @generated from enum RegisterForGameControllerEventsMessage.InputModeFlags
 */
export enum RegisterForGameControllerEventsMessage_InputModeFlags {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Motion = 1;
   */
  Motion = 1,

  /**
   * @generated from enum value: Buttons = 2;
   */
  Buttons = 2,

  /**
   * @generated from enum value: Digitizer = 3;
   */
  Digitizer = 3,
}

/**
 * Describes the enum RegisterForGameControllerEventsMessage.InputModeFlags.
 */
export const RegisterForGameControllerEventsMessage_InputModeFlagsSchema: GenEnum<RegisterForGameControllerEventsMessage_InputModeFlags> = /*@__PURE__*/
  enumDesc(file_RegisterForGameControllerEventsMessage, 0, 0);

/**
 * @generated from extension: optional RegisterForGameControllerEventsMessage registerForGameControllerEventsMessage = 27;
 */
export const registerForGameControllerEventsMessage: GenExtension<ProtocolMessage, RegisterForGameControllerEventsMessage> = /*@__PURE__*/
  extDesc(file_RegisterForGameControllerEventsMessage, 0);

