// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file RemoveEndpointsMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RemoveEndpointsMessage.proto.
 */
export const file_RemoveEndpointsMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxSZW1vdmVFbmRwb2ludHNNZXNzYWdlLnByb3RvIi4KFlJlbW92ZUVuZHBvaW50c01lc3NhZ2USFAoMZW5kcG9pbnRVSURzGAEgAygJOmEKFnJlbW92ZUVuZHBvaW50c01lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYVCABKAsyFy5SZW1vdmVFbmRwb2ludHNNZXNzYWdlUhZyZW1vdmVFbmRwb2ludHNNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message RemoveEndpointsMessage
 */
export type RemoveEndpointsMessage = Message<"RemoveEndpointsMessage"> & {
  /**
   * @generated from field: repeated string endpointUIDs = 1;
   */
  endpointUIDs: string[];
};

/**
 * Describes the message RemoveEndpointsMessage.
 * Use `create(RemoveEndpointsMessageSchema)` to create a new message.
 */
export const RemoveEndpointsMessageSchema: GenMessage<RemoveEndpointsMessage> = /*@__PURE__*/
  messageDesc(file_RemoveEndpointsMessage, 0);

/**
 * @generated from extension: optional RemoveEndpointsMessage removeEndpointsMessage = 84;
 */
export const removeEndpointsMessage: GenExtension<ProtocolMessage, RemoveEndpointsMessage> = /*@__PURE__*/
  extDesc(file_RemoveEndpointsMessage, 0);

