// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file RemovePlayerMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RemovePlayerMessage.proto.
 */
export const file_RemovePlayerMessage: GenFile = /*@__PURE__*/
  fileDesc("ChlSZW1vdmVQbGF5ZXJNZXNzYWdlLnByb3RvIjYKE1JlbW92ZVBsYXllck1lc3NhZ2USHwoKcGxheWVyUGF0aBgBIAEoCzILLlBsYXllclBhdGg6WAoTcmVtb3ZlUGxheWVyTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRg6IAEoCzIULlJlbW92ZVBsYXllck1lc3NhZ2VSE3JlbW92ZVBsYXllck1lc3NhZ2U", [file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message RemovePlayerMessage
 */
export type RemovePlayerMessage = Message<"RemovePlayerMessage"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message RemovePlayerMessage.
 * Use `create(RemovePlayerMessageSchema)` to create a new message.
 */
export const RemovePlayerMessageSchema: GenMessage<RemovePlayerMessage> = /*@__PURE__*/
  messageDesc(file_RemovePlayerMessage, 0);

/**
 * @generated from extension: optional RemovePlayerMessage removePlayerMessage = 58;
 */
export const removePlayerMessage: GenExtension<ProtocolMessage, RemovePlayerMessage> = /*@__PURE__*/
  extDesc(file_RemovePlayerMessage, 0);

