// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file RemoteTextInputMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RemoteTextInputMessage.proto.
 */
export const file_RemoteTextInputMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxSZW1vdGVUZXh0SW5wdXRNZXNzYWdlLnByb3RvIkoKFlJlbW90ZVRleHRJbnB1dE1lc3NhZ2USEQoJdGltZXN0YW1wGAEgASgBEg8KB3ZlcnNpb24YAiABKAQSDAoEZGF0YRgDIAEoDDphChZyZW1vdGVUZXh0SW5wdXRNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGEcgASgLMhcuUmVtb3RlVGV4dElucHV0TWVzc2FnZVIWcmVtb3RlVGV4dElucHV0TWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message RemoteTextInputMessage
 */
export type RemoteTextInputMessage = Message<"RemoteTextInputMessage"> & {
  /**
   * @generated from field: optional double timestamp = 1;
   */
  timestamp: number;

  /**
   * @generated from field: optional uint64 version = 2;
   */
  version: bigint;

  /**
   * @generated from field: optional bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message RemoteTextInputMessage.
 * Use `create(RemoteTextInputMessageSchema)` to create a new message.
 */
export const RemoteTextInputMessageSchema: GenMessage<RemoteTextInputMessage> = /*@__PURE__*/
  messageDesc(file_RemoteTextInputMessage, 0);

/**
 * @generated from extension: optional RemoteTextInputMessage remoteTextInputMessage = 71;
 */
export const remoteTextInputMessage: GenExtension<ProtocolMessage, RemoteTextInputMessage> = /*@__PURE__*/
  extDesc(file_RemoteTextInputMessage, 0);

