// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file RemoveOutputDevicesMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RemoveOutputDevicesMessage.proto.
 */
export const file_RemoveOutputDevicesMessage: GenFile = /*@__PURE__*/
  fileDesc("CiBSZW1vdmVPdXRwdXREZXZpY2VzTWVzc2FnZS5wcm90byJLChpSZW1vdmVPdXRwdXREZXZpY2VzTWVzc2FnZRIYChBvdXRwdXREZXZpY2VVSURzGAEgAygJEhMKC2VuZHBvaW50VUlEGAIgASgJOm0KGnJlbW92ZU91dHB1dERldmljZXNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGEYgASgLMhsuUmVtb3ZlT3V0cHV0RGV2aWNlc01lc3NhZ2VSGnJlbW92ZU91dHB1dERldmljZXNNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message RemoveOutputDevicesMessage
 */
export type RemoveOutputDevicesMessage = Message<"RemoveOutputDevicesMessage"> & {
  /**
   * @generated from field: repeated string outputDeviceUIDs = 1;
   */
  outputDeviceUIDs: string[];

  /**
   * @generated from field: optional string endpointUID = 2;
   */
  endpointUID: string;
};

/**
 * Describes the message RemoveOutputDevicesMessage.
 * Use `create(RemoveOutputDevicesMessageSchema)` to create a new message.
 */
export const RemoveOutputDevicesMessageSchema: GenMessage<RemoveOutputDevicesMessage> = /*@__PURE__*/
  messageDesc(file_RemoveOutputDevicesMessage, 0);

/**
 * @generated from extension: optional RemoveOutputDevicesMessage removeOutputDevicesMessage = 70;
 */
export const removeOutputDevicesMessage: GenExtension<ProtocolMessage, RemoveOutputDevicesMessage> = /*@__PURE__*/
  extDesc(file_RemoveOutputDevicesMessage, 0);

