// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file RequestDetails.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file RequestDetails.proto.
 */
export const file_RequestDetails: GenFile = /*@__PURE__*/
  fileDesc("ChRSZXF1ZXN0RGV0YWlscy5wcm90byLeAQoOUmVxdWVzdERldGFpbHMSEQoJaW5pdGlhdG9yGAEgASgJEhEKCXJlcXVlc3RJRBgCIAEoCRIOCgZyZWFzb24YAyABKAkSCwoDcW9zGAQgASgNEhEKCXN0YXJ0RGF0ZRgFIAEoBBIVCg11c2VySW5pdGlhdGVkGAYgASgIEhwKFGluaXRpYXRvcldhc0luZmVycmVkGAcgASgIEhsKE29yaWdpbmF0aW5nQnVuZGxlSUQYCCABKAkSEwoLb3BlcmF0aW9uSUQYCSABKAkSDwoHc3VyZmFjZRgKIAEoCQ");

/**
 * @generated from message RequestDetails
 */
export type RequestDetails = Message<"RequestDetails"> & {
  /**
   * @generated from field: optional string initiator = 1;
   */
  initiator: string;

  /**
   * @generated from field: optional string requestID = 2;
   */
  requestID: string;

  /**
   * @generated from field: optional string reason = 3;
   */
  reason: string;

  /**
   * @generated from field: optional uint32 qos = 4;
   */
  qos: number;

  /**
   * @generated from field: optional uint64 startDate = 5;
   */
  startDate: bigint;

  /**
   * @generated from field: optional bool userInitiated = 6;
   */
  userInitiated: boolean;

  /**
   * @generated from field: optional bool initiatorWasInferred = 7;
   */
  initiatorWasInferred: boolean;

  /**
   * @generated from field: optional string originatingBundleID = 8;
   */
  originatingBundleID: string;

  /**
   * @generated from field: optional string operationID = 9;
   */
  operationID: string;

  /**
   * @generated from field: optional string surface = 10;
   */
  surface: string;
};

/**
 * Describes the message RequestDetails.
 * Use `create(RequestDetailsSchema)` to create a new message.
 */
export const RequestDetailsSchema: GenMessage<RequestDetails> = /*@__PURE__*/
  messageDesc(file_RequestDetails, 0);

