// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SendLyricsEventMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SendLyricsEventMessage.proto.
 */
export const file_SendLyricsEventMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxTZW5kTHlyaWNzRXZlbnRNZXNzYWdlLnByb3RvIhgKFlNlbmRMeXJpY3NFdmVudE1lc3NhZ2U6YQoWc2VuZEx5cmljc0V2ZW50TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgwIAEoCzIXLlNlbmRMeXJpY3NFdmVudE1lc3NhZ2VSFnNlbmRMeXJpY3NFdmVudE1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message SendLyricsEventMessage
 */
export type SendLyricsEventMessage = Message<"SendLyricsEventMessage"> & {
};

/**
 * Describes the message SendLyricsEventMessage.
 * Use `create(SendLyricsEventMessageSchema)` to create a new message.
 */
export const SendLyricsEventMessageSchema: GenMessage<SendLyricsEventMessage> = /*@__PURE__*/
  messageDesc(file_SendLyricsEventMessage, 0);

/**
 * @generated from extension: optional SendLyricsEventMessage sendLyricsEventMessage = 48;
 */
export const sendLyricsEventMessage: GenExtension<ProtocolMessage, SendLyricsEventMessage> = /*@__PURE__*/
  extDesc(file_SendLyricsEventMessage, 0);

