// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SendCommandResultHandlerDialog.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SendCommandResultHandlerDialog.proto.
 */
export const file_SendCommandResultHandlerDialog: GenFile = /*@__PURE__*/
  fileDesc("CiRTZW5kQ29tbWFuZFJlc3VsdEhhbmRsZXJEaWFsb2cucHJvdG8iTAooU2VuZENvbW1hbmRSZXN1bHRIYW5kbGVyRGlhbG9nQWN0aW9uVHlwZSIgCgRFbnVtEgsKB0Rpc21pc3MQABILCgdEZWZhdWx0EAEiggEKJFNlbmRDb21tYW5kUmVzdWx0SGFuZGxlckRpYWxvZ0FjdGlvbhINCgV0aXRsZRgBIAEoCRI8CgR0eXBlGAIgASgOMi4uU2VuZENvbW1hbmRSZXN1bHRIYW5kbGVyRGlhbG9nQWN0aW9uVHlwZS5FbnVtEg0KBWV2ZW50GAMgASgMIooBCh5TZW5kQ29tbWFuZFJlc3VsdEhhbmRsZXJEaWFsb2cSFgoObG9jYWxpemVkVGl0bGUYASABKAkSGAoQbG9jYWxpemVkTWVzc2FnZRgCIAEoCRI2CgdhY3Rpb25zGAMgAygLMiUuU2VuZENvbW1hbmRSZXN1bHRIYW5kbGVyRGlhbG9nQWN0aW9u");

/**
 * @generated from message SendCommandResultHandlerDialogActionType
 */
export type SendCommandResultHandlerDialogActionType = Message<"SendCommandResultHandlerDialogActionType"> & {
};

/**
 * Describes the message SendCommandResultHandlerDialogActionType.
 * Use `create(SendCommandResultHandlerDialogActionTypeSchema)` to create a new message.
 */
export const SendCommandResultHandlerDialogActionTypeSchema: GenMessage<SendCommandResultHandlerDialogActionType> = /*@__PURE__*/
  messageDesc(file_SendCommandResultHandlerDialog, 0);

/**
 * @generated from enum SendCommandResultHandlerDialogActionType.Enum
 */
export enum SendCommandResultHandlerDialogActionType_Enum {
  /**
   * @generated from enum value: Dismiss = 0;
   */
  Dismiss = 0,

  /**
   * @generated from enum value: Default = 1;
   */
  Default = 1,
}

/**
 * Describes the enum SendCommandResultHandlerDialogActionType.Enum.
 */
export const SendCommandResultHandlerDialogActionType_EnumSchema: GenEnum<SendCommandResultHandlerDialogActionType_Enum> = /*@__PURE__*/
  enumDesc(file_SendCommandResultHandlerDialog, 0, 0);

/**
 * @generated from message SendCommandResultHandlerDialogAction
 */
export type SendCommandResultHandlerDialogAction = Message<"SendCommandResultHandlerDialogAction"> & {
  /**
   * @generated from field: optional string title = 1;
   */
  title: string;

  /**
   * @generated from field: optional SendCommandResultHandlerDialogActionType.Enum type = 2;
   */
  type: SendCommandResultHandlerDialogActionType_Enum;

  /**
   * @generated from field: optional bytes event = 3;
   */
  event: Uint8Array;
};

/**
 * Describes the message SendCommandResultHandlerDialogAction.
 * Use `create(SendCommandResultHandlerDialogActionSchema)` to create a new message.
 */
export const SendCommandResultHandlerDialogActionSchema: GenMessage<SendCommandResultHandlerDialogAction> = /*@__PURE__*/
  messageDesc(file_SendCommandResultHandlerDialog, 1);

/**
 * @generated from message SendCommandResultHandlerDialog
 */
export type SendCommandResultHandlerDialog = Message<"SendCommandResultHandlerDialog"> & {
  /**
   * @generated from field: optional string localizedTitle = 1;
   */
  localizedTitle: string;

  /**
   * @generated from field: optional string localizedMessage = 2;
   */
  localizedMessage: string;

  /**
   * @generated from field: repeated SendCommandResultHandlerDialogAction actions = 3;
   */
  actions: SendCommandResultHandlerDialogAction[];
};

/**
 * Describes the message SendCommandResultHandlerDialog.
 * Use `create(SendCommandResultHandlerDialogSchema)` to create a new message.
 */
export const SendCommandResultHandlerDialogSchema: GenMessage<SendCommandResultHandlerDialog> = /*@__PURE__*/
  messageDesc(file_SendCommandResultHandlerDialog, 2);

