// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SendButtonEventMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SendButtonEventMessage.proto.
 */
export const file_SendButtonEventMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxTZW5kQnV0dG9uRXZlbnRNZXNzYWdlLnByb3RvIk4KFlNlbmRCdXR0b25FdmVudE1lc3NhZ2USEQoJdXNhZ2VQYWdlGAEgASgNEg0KBXVzYWdlGAIgASgNEhIKCmJ1dHRvbkRvd24YAyABKAg6YQoWc2VuZEJ1dHRvbkV2ZW50TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgrIAEoCzIXLlNlbmRCdXR0b25FdmVudE1lc3NhZ2VSFnNlbmRCdXR0b25FdmVudE1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message SendButtonEventMessage
 */
export type SendButtonEventMessage = Message<"SendButtonEventMessage"> & {
  /**
   * @generated from field: optional uint32 usagePage = 1;
   */
  usagePage: number;

  /**
   * @generated from field: optional uint32 usage = 2;
   */
  usage: number;

  /**
   * @generated from field: optional bool buttonDown = 3;
   */
  buttonDown: boolean;
};

/**
 * Describes the message SendButtonEventMessage.
 * Use `create(SendButtonEventMessageSchema)` to create a new message.
 */
export const SendButtonEventMessageSchema: GenMessage<SendButtonEventMessage> = /*@__PURE__*/
  messageDesc(file_SendButtonEventMessage, 0);

/**
 * @generated from extension: optional SendButtonEventMessage sendButtonEventMessage = 43;
 */
export const sendButtonEventMessage: GenExtension<ProtocolMessage, SendButtonEventMessage> = /*@__PURE__*/
  extDesc(file_SendButtonEventMessage, 0);

