// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file SendCommandMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Command } from "./CommandInfo_pb";
import { file_CommandInfo } from "./CommandInfo_pb";
import type { CommandOptions } from "./CommandOptions_pb";
import { file_CommandOptions } from "./CommandOptions_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SendCommandMessage.proto.
 */
export const file_SendCommandMessage: GenFile = /*@__PURE__*/
  fileDesc("ChhTZW5kQ29tbWFuZE1lc3NhZ2UucHJvdG8icgoSU2VuZENvbW1hbmRNZXNzYWdlEhkKB2NvbW1hbmQYASABKA4yCC5Db21tYW5kEiAKB29wdGlvbnMYAiABKAsyDy5Db21tYW5kT3B0aW9ucxIfCgpwbGF5ZXJQYXRoGAMgASgLMgsuUGxheWVyUGF0aDpVChJzZW5kQ29tbWFuZE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYBiABKAsyEy5TZW5kQ29tbWFuZE1lc3NhZ2VSEnNlbmRDb21tYW5kTWVzc2FnZQ", [file_ProtocolMessage, file_CommandInfo, file_CommandOptions, file_PlayerPath]);

/**
 * @generated from message SendCommandMessage
 */
export type SendCommandMessage = Message<"SendCommandMessage"> & {
  /**
   * @generated from field: optional Command command = 1;
   */
  command: Command;

  /**
   * @generated from field: optional CommandOptions options = 2;
   */
  options?: CommandOptions;

  /**
   * @generated from field: optional PlayerPath playerPath = 3;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message SendCommandMessage.
 * Use `create(SendCommandMessageSchema)` to create a new message.
 */
export const SendCommandMessageSchema: GenMessage<SendCommandMessage> = /*@__PURE__*/
  messageDesc(file_SendCommandMessage, 0);

/**
 * @generated from extension: optional SendCommandMessage sendCommandMessage = 6;
 */
export const sendCommandMessage: GenExtension<ProtocolMessage, SendCommandMessage> = /*@__PURE__*/
  extDesc(file_SendCommandMessage, 0);

