// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SendVirtualTouchEventMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SendVirtualTouchEventMessage.proto.
 */
export const file_SendVirtualTouchEventMessage: GenFile = /*@__PURE__*/
  fileDesc("CiJTZW5kVmlydHVhbFRvdWNoRXZlbnRNZXNzYWdlLnByb3RvIloKHFNlbmRWaXJ0dWFsVG91Y2hFdmVudE1lc3NhZ2USFwoPdmlydHVhbERldmljZUlEGAEgASgEEiEKBWV2ZW50GAIgASgLMhIuVmlydHVhbFRvdWNoRXZlbnQiSAoRVmlydHVhbFRvdWNoRXZlbnQSCQoBeBgBIAEoBBIJCgF5GAIgASgEEg0KBXBoYXNlGAMgASgNEg4KBmZpbmdlchgEIAEoDTpzChxzZW5kVmlydHVhbFRvdWNoRXZlbnRNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGA8gASgLMh0uU2VuZFZpcnR1YWxUb3VjaEV2ZW50TWVzc2FnZVIcc2VuZFZpcnR1YWxUb3VjaEV2ZW50TWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message SendVirtualTouchEventMessage
 */
export type SendVirtualTouchEventMessage = Message<"SendVirtualTouchEventMessage"> & {
  /**
   * @generated from field: optional uint64 virtualDeviceID = 1;
   */
  virtualDeviceID: bigint;

  /**
   * @generated from field: optional VirtualTouchEvent event = 2;
   */
  event?: VirtualTouchEvent;
};

/**
 * Describes the message SendVirtualTouchEventMessage.
 * Use `create(SendVirtualTouchEventMessageSchema)` to create a new message.
 */
export const SendVirtualTouchEventMessageSchema: GenMessage<SendVirtualTouchEventMessage> = /*@__PURE__*/
  messageDesc(file_SendVirtualTouchEventMessage, 0);

/**
 * @generated from message VirtualTouchEvent
 */
export type VirtualTouchEvent = Message<"VirtualTouchEvent"> & {
  /**
   * @generated from field: optional uint64 x = 1;
   */
  x: bigint;

  /**
   * @generated from field: optional uint64 y = 2;
   */
  y: bigint;

  /**
   * @generated from field: optional uint32 phase = 3;
   */
  phase: number;

  /**
   * @generated from field: optional uint32 finger = 4;
   */
  finger: number;
};

/**
 * Describes the message VirtualTouchEvent.
 * Use `create(VirtualTouchEventSchema)` to create a new message.
 */
export const VirtualTouchEventSchema: GenMessage<VirtualTouchEvent> = /*@__PURE__*/
  messageDesc(file_SendVirtualTouchEventMessage, 1);

/**
 * @generated from extension: optional SendVirtualTouchEventMessage sendVirtualTouchEventMessage = 15;
 */
export const sendVirtualTouchEventMessage: GenExtension<ProtocolMessage, SendVirtualTouchEventMessage> = /*@__PURE__*/
  extDesc(file_SendVirtualTouchEventMessage, 0);

