// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetArtworkMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetArtworkMessage.proto.
 */
export const file_SetArtworkMessage: GenFile = /*@__PURE__*/
  fileDesc("ChdTZXRBcnR3b3JrTWVzc2FnZS5wcm90byIlChFTZXRBcnR3b3JrTWVzc2FnZRIQCghqcGVnRGF0YRgBIAEoDDpSChFzZXRBcnR3b3JrTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgKIAEoCzISLlNldEFydHdvcmtNZXNzYWdlUhFzZXRBcnR3b3JrTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message SetArtworkMessage
 */
export type SetArtworkMessage = Message<"SetArtworkMessage"> & {
  /**
   * @generated from field: optional bytes jpegData = 1;
   */
  jpegData: Uint8Array;
};

/**
 * Describes the message SetArtworkMessage.
 * Use `create(SetArtworkMessageSchema)` to create a new message.
 */
export const SetArtworkMessageSchema: GenMessage<SetArtworkMessage> = /*@__PURE__*/
  messageDesc(file_SetArtworkMessage, 0);

/**
 * @generated from extension: optional SetArtworkMessage setArtworkMessage = 10;
 */
export const setArtworkMessage: GenExtension<ProtocolMessage, SetArtworkMessage> = /*@__PURE__*/
  extDesc(file_SetArtworkMessage, 0);

