// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetConnectionStateMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetConnectionStateMessage.proto.
 */
export const file_SetConnectionStateMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch9TZXRDb25uZWN0aW9uU3RhdGVNZXNzYWdlLnByb3RvIqQBChlTZXRDb25uZWN0aW9uU3RhdGVNZXNzYWdlEjkKBXN0YXRlGAEgASgOMiouU2V0Q29ubmVjdGlvblN0YXRlTWVzc2FnZS5Db25uZWN0aW9uU3RhdGUiTAoPQ29ubmVjdGlvblN0YXRlEggKBE5vbmUQABIOCgpDb25uZWN0aW5nEAESDQoJQ29ubmVjdGVkEAISEAoMRGlzY29ubmVjdGVkEAM6agoZc2V0Q29ubmVjdGlvblN0YXRlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgqIAEoCzIaLlNldENvbm5lY3Rpb25TdGF0ZU1lc3NhZ2VSGXNldENvbm5lY3Rpb25TdGF0ZU1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message SetConnectionStateMessage
 */
export type SetConnectionStateMessage = Message<"SetConnectionStateMessage"> & {
  /**
   * @generated from field: optional SetConnectionStateMessage.ConnectionState state = 1;
   */
  state: SetConnectionStateMessage_ConnectionState;
};

/**
 * Describes the message SetConnectionStateMessage.
 * Use `create(SetConnectionStateMessageSchema)` to create a new message.
 */
export const SetConnectionStateMessageSchema: GenMessage<SetConnectionStateMessage> = /*@__PURE__*/
  messageDesc(file_SetConnectionStateMessage, 0);

/**
 * @generated from enum SetConnectionStateMessage.ConnectionState
 */
export enum SetConnectionStateMessage_ConnectionState {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Connecting = 1;
   */
  Connecting = 1,

  /**
   * @generated from enum value: Connected = 2;
   */
  Connected = 2,

  /**
   * @generated from enum value: Disconnected = 3;
   */
  Disconnected = 3,
}

/**
 * Describes the enum SetConnectionStateMessage.ConnectionState.
 */
export const SetConnectionStateMessage_ConnectionStateSchema: GenEnum<SetConnectionStateMessage_ConnectionState> = /*@__PURE__*/
  enumDesc(file_SetConnectionStateMessage, 0, 0);

/**
 * @generated from extension: optional SetConnectionStateMessage setConnectionStateMessage = 42;
 */
export const setConnectionStateMessage: GenExtension<ProtocolMessage, SetConnectionStateMessage> = /*@__PURE__*/
  extDesc(file_SetConnectionStateMessage, 0);

