// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SetConversationDetectionEnabledMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetConversationDetectionEnabledMessage.proto.
 */
export const file_SetConversationDetectionEnabledMessage: GenFile = /*@__PURE__*/
  fileDesc("CixTZXRDb252ZXJzYXRpb25EZXRlY3Rpb25FbmFibGVkTWVzc2FnZS5wcm90byJSCiZTZXRDb252ZXJzYXRpb25EZXRlY3Rpb25FbmFibGVkTWVzc2FnZRIPCgdlbmFibGVkGAEgASgIEhcKD291dHB1dERldmljZVVJRBgCIAEoCTqRAQomc2V0Q29udmVyc2F0aW9uRGV0ZWN0aW9uRW5hYmxlZE1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYWiABKAsyJy5TZXRDb252ZXJzYXRpb25EZXRlY3Rpb25FbmFibGVkTWVzc2FnZVImc2V0Q29udmVyc2F0aW9uRGV0ZWN0aW9uRW5hYmxlZE1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message SetConversationDetectionEnabledMessage
 */
export type SetConversationDetectionEnabledMessage = Message<"SetConversationDetectionEnabledMessage"> & {
  /**
   * @generated from field: optional bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: optional string outputDeviceUID = 2;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message SetConversationDetectionEnabledMessage.
 * Use `create(SetConversationDetectionEnabledMessageSchema)` to create a new message.
 */
export const SetConversationDetectionEnabledMessageSchema: GenMessage<SetConversationDetectionEnabledMessage> = /*@__PURE__*/
  messageDesc(file_SetConversationDetectionEnabledMessage, 0);

/**
 * @generated from extension: optional SetConversationDetectionEnabledMessage setConversationDetectionEnabledMessage = 90;
 */
export const setConversationDetectionEnabledMessage: GenExtension<ProtocolMessage, SetConversationDetectionEnabledMessage> = /*@__PURE__*/
  extDesc(file_SetConversationDetectionEnabledMessage, 0);

