// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetDefaultSupportedCommandsMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { NowPlayingInfo } from "./NowPlayingInfo_pb";
import { file_NowPlayingInfo } from "./NowPlayingInfo_pb";
import type { PlaybackQueue } from "./PlaybackQueue_pb";
import { file_PlaybackQueue } from "./PlaybackQueue_pb";
import type { SupportedCommands } from "./SupportedCommands_pb";
import { file_SupportedCommands } from "./SupportedCommands_pb";
import type { PlaybackQueueCapabilities } from "./PlaybackQueueCapabilities_pb";
import { file_PlaybackQueueCapabilities } from "./PlaybackQueueCapabilities_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackQueueRequestMessage } from "./PlaybackQueueRequestMessage_pb";
import { file_PlaybackQueueRequestMessage } from "./PlaybackQueueRequestMessage_pb";
import type { PlaybackState_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetDefaultSupportedCommandsMessage.proto.
 */
export const file_SetDefaultSupportedCommandsMessage: GenFile = /*@__PURE__*/
  fileDesc("CihTZXREZWZhdWx0U3VwcG9ydGVkQ29tbWFuZHNNZXNzYWdlLnByb3RvIqYDCiJTZXREZWZhdWx0U3VwcG9ydGVkQ29tbWFuZHNNZXNzYWdlEicKDm5vd1BsYXlpbmdJbmZvGAEgASgLMg8uTm93UGxheWluZ0luZm8SLQoRc3VwcG9ydGVkQ29tbWFuZHMYAiABKAsyEi5TdXBwb3J0ZWRDb21tYW5kcxIlCg1wbGF5YmFja1F1ZXVlGAMgASgLMg4uUGxheWJhY2tRdWV1ZRIRCglkaXNwbGF5SUQYBCABKAkSEwoLZGlzcGxheU5hbWUYBSABKAkSKgoNcGxheWJhY2tTdGF0ZRgGIAEoDjITLlBsYXliYWNrU3RhdGUuRW51bRI9ChlwbGF5YmFja1F1ZXVlQ2FwYWJpbGl0aWVzGAggASgLMhouUGxheWJhY2tRdWV1ZUNhcGFiaWxpdGllcxIfCgpwbGF5ZXJQYXRoGAkgASgLMgsuUGxheWVyUGF0aBItCgdyZXF1ZXN0GAogASgLMhwuUGxheWJhY2tRdWV1ZVJlcXVlc3RNZXNzYWdlEh4KFnBsYXliYWNrU3RhdGVUaW1lc3RhbXAYCyABKAE6hQEKInNldERlZmF1bHRTdXBwb3J0ZWRDb21tYW5kc01lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYSyABKAsyIy5TZXREZWZhdWx0U3VwcG9ydGVkQ29tbWFuZHNNZXNzYWdlUiJzZXREZWZhdWx0U3VwcG9ydGVkQ29tbWFuZHNNZXNzYWdl", [file_ProtocolMessage, file_NowPlayingInfo, file_PlaybackQueue, file_SupportedCommands, file_PlaybackQueueCapabilities, file_PlayerPath, file_PlaybackQueueRequestMessage, file_Common]);

/**
 * Seems to be the same as SetStateMessage
 *
 * @generated from message SetDefaultSupportedCommandsMessage
 */
export type SetDefaultSupportedCommandsMessage = Message<"SetDefaultSupportedCommandsMessage"> & {
  /**
   * @generated from field: optional NowPlayingInfo nowPlayingInfo = 1;
   */
  nowPlayingInfo?: NowPlayingInfo;

  /**
   * @generated from field: optional SupportedCommands supportedCommands = 2;
   */
  supportedCommands?: SupportedCommands;

  /**
   * @generated from field: optional PlaybackQueue playbackQueue = 3;
   */
  playbackQueue?: PlaybackQueue;

  /**
   * @generated from field: optional string displayID = 4;
   */
  displayID: string;

  /**
   * @generated from field: optional string displayName = 5;
   */
  displayName: string;

  /**
   * @generated from field: optional PlaybackState.Enum playbackState = 6;
   */
  playbackState: PlaybackState_Enum;

  /**
   * @generated from field: optional PlaybackQueueCapabilities playbackQueueCapabilities = 8;
   */
  playbackQueueCapabilities?: PlaybackQueueCapabilities;

  /**
   * @generated from field: optional PlayerPath playerPath = 9;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional PlaybackQueueRequestMessage request = 10;
   */
  request?: PlaybackQueueRequestMessage;

  /**
   * @generated from field: optional double playbackStateTimestamp = 11;
   */
  playbackStateTimestamp: number;
};

/**
 * Describes the message SetDefaultSupportedCommandsMessage.
 * Use `create(SetDefaultSupportedCommandsMessageSchema)` to create a new message.
 */
export const SetDefaultSupportedCommandsMessageSchema: GenMessage<SetDefaultSupportedCommandsMessage> = /*@__PURE__*/
  messageDesc(file_SetDefaultSupportedCommandsMessage, 0);

/**
 * @generated from extension: optional SetDefaultSupportedCommandsMessage setDefaultSupportedCommandsMessage = 75;
 */
export const setDefaultSupportedCommandsMessage: GenExtension<ProtocolMessage, SetDefaultSupportedCommandsMessage> = /*@__PURE__*/
  extDesc(file_SetDefaultSupportedCommandsMessage, 0);

