// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetDiscoveryModeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetDiscoveryModeMessage.proto.
 */
export const file_SetDiscoveryModeMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch1TZXREaXNjb3ZlcnlNb2RlTWVzc2FnZS5wcm90byI5ChdTZXREaXNjb3ZlcnlNb2RlTWVzc2FnZRIMCgRtb2RlGAEgASgFEhAKCGZlYXR1cmVzGAIgASgFOmQKF3NldERpc2NvdmVyeU1vZGVNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGFIgASgLMhguU2V0RGlzY292ZXJ5TW9kZU1lc3NhZ2VSF3NldERpc2NvdmVyeU1vZGVNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message SetDiscoveryModeMessage
 */
export type SetDiscoveryModeMessage = Message<"SetDiscoveryModeMessage"> & {
  /**
   * @generated from field: optional int32 mode = 1;
   */
  mode: number;

  /**
   * @generated from field: optional int32 features = 2;
   */
  features: number;
};

/**
 * Describes the message SetDiscoveryModeMessage.
 * Use `create(SetDiscoveryModeMessageSchema)` to create a new message.
 */
export const SetDiscoveryModeMessageSchema: GenMessage<SetDiscoveryModeMessage> = /*@__PURE__*/
  messageDesc(file_SetDiscoveryModeMessage, 0);

/**
 * @generated from extension: optional SetDiscoveryModeMessage setDiscoveryModeMessage = 82;
 */
export const setDiscoveryModeMessage: GenExtension<ProtocolMessage, SetDiscoveryModeMessage> = /*@__PURE__*/
  extDesc(file_SetDiscoveryModeMessage, 0);

