// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetHiliteModeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetHiliteModeMessage.proto.
 */
export const file_SetHiliteModeMessage: GenFile = /*@__PURE__*/
  fileDesc("ChpTZXRIaWxpdGVNb2RlTWVzc2FnZS5wcm90byIqChRTZXRIaWxpdGVNb2RlTWVzc2FnZRISCgpoaWxpdGVNb2RlGAEgASgFOlsKFHNldEhpbGl0ZU1vZGVNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGCwgASgLMhUuU2V0SGlsaXRlTW9kZU1lc3NhZ2VSFHNldEhpbGl0ZU1vZGVNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message SetHiliteModeMessage
 */
export type SetHiliteModeMessage = Message<"SetHiliteModeMessage"> & {
  /**
   * @generated from field: optional int32 hiliteMode = 1;
   */
  hiliteMode: number;
};

/**
 * Describes the message SetHiliteModeMessage.
 * Use `create(SetHiliteModeMessageSchema)` to create a new message.
 */
export const SetHiliteModeMessageSchema: GenMessage<SetHiliteModeMessage> = /*@__PURE__*/
  messageDesc(file_SetHiliteModeMessage, 0);

/**
 * @generated from extension: optional SetHiliteModeMessage setHiliteModeMessage = 44;
 */
export const setHiliteModeMessage: GenExtension<ProtocolMessage, SetHiliteModeMessage> = /*@__PURE__*/
  extDesc(file_SetHiliteModeMessage, 0);

