// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SetListeningModeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetListeningModeMessage.proto.
 */
export const file_SetListeningModeMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch1TZXRMaXN0ZW5pbmdNb2RlTWVzc2FnZS5wcm90byJJChdTZXRMaXN0ZW5pbmdNb2RlTWVzc2FnZRIVCg1saXN0ZW5pbmdNb2RlGAEgASgJEhcKD291dHB1dERldmljZVVJRBgCIAEoCTpkChdzZXRMaXN0ZW5pbmdNb2RlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhcIAEoCzIYLlNldExpc3RlbmluZ01vZGVNZXNzYWdlUhdzZXRMaXN0ZW5pbmdNb2RlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message SetListeningModeMessage
 */
export type SetListeningModeMessage = Message<"SetListeningModeMessage"> & {
  /**
   * @generated from field: optional string listeningMode = 1;
   */
  listeningMode: string;

  /**
   * @generated from field: optional string outputDeviceUID = 2;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message SetListeningModeMessage.
 * Use `create(SetListeningModeMessageSchema)` to create a new message.
 */
export const SetListeningModeMessageSchema: GenMessage<SetListeningModeMessage> = /*@__PURE__*/
  messageDesc(file_SetListeningModeMessage, 0);

/**
 * @generated from extension: optional SetListeningModeMessage setListeningModeMessage = 92;
 */
export const setListeningModeMessage: GenExtension<ProtocolMessage, SetListeningModeMessage> = /*@__PURE__*/
  extDesc(file_SetListeningModeMessage, 0);

