// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file SetNowPlayingPlayerMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetNowPlayingPlayerMessage.proto.
 */
export const file_SetNowPlayingPlayerMessage: GenFile = /*@__PURE__*/
  fileDesc("CiBTZXROb3dQbGF5aW5nUGxheWVyTWVzc2FnZS5wcm90byI9ChpTZXROb3dQbGF5aW5nUGxheWVyTWVzc2FnZRIfCgpwbGF5ZXJQYXRoGAEgASgLMgsuUGxheWVyUGF0aDptChpzZXROb3dQbGF5aW5nUGxheWVyTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgzIAEoCzIbLlNldE5vd1BsYXlpbmdQbGF5ZXJNZXNzYWdlUhpzZXROb3dQbGF5aW5nUGxheWVyTWVzc2FnZQ", [file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message SetNowPlayingPlayerMessage
 */
export type SetNowPlayingPlayerMessage = Message<"SetNowPlayingPlayerMessage"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message SetNowPlayingPlayerMessage.
 * Use `create(SetNowPlayingPlayerMessageSchema)` to create a new message.
 */
export const SetNowPlayingPlayerMessageSchema: GenMessage<SetNowPlayingPlayerMessage> = /*@__PURE__*/
  messageDesc(file_SetNowPlayingPlayerMessage, 0);

/**
 * @generated from extension: optional SetNowPlayingPlayerMessage setNowPlayingPlayerMessage = 51;
 */
export const setNowPlayingPlayerMessage: GenExtension<ProtocolMessage, SetNowPlayingPlayerMessage> = /*@__PURE__*/
  extDesc(file_SetNowPlayingPlayerMessage, 0);

