// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetReadyStateMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetReadyStateMessage.proto.
 */
export const file_SetReadyStateMessage: GenFile = /*@__PURE__*/
  fileDesc("ChpTZXRSZWFkeVN0YXRlTWVzc2FnZS5wcm90byIWChRTZXRSZWFkeVN0YXRlTWVzc2FnZTpVChFyZWFkeVN0YXRlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgpIAEoCzIVLlNldFJlYWR5U3RhdGVNZXNzYWdlUhFyZWFkeVN0YXRlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message SetReadyStateMessage
 */
export type SetReadyStateMessage = Message<"SetReadyStateMessage"> & {
};

/**
 * Describes the message SetReadyStateMessage.
 * Use `create(SetReadyStateMessageSchema)` to create a new message.
 */
export const SetReadyStateMessageSchema: GenMessage<SetReadyStateMessage> = /*@__PURE__*/
  messageDesc(file_SetReadyStateMessage, 0);

/**
 * @generated from extension: optional SetReadyStateMessage readyStateMessage = 41;
 */
export const readyStateMessage: GenExtension<ProtocolMessage, SetReadyStateMessage> = /*@__PURE__*/
  extDesc(file_SetReadyStateMessage, 0);

