// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SetRecordingStateMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetRecordingStateMessage.proto.
 */
export const file_SetRecordingStateMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch5TZXRSZWNvcmRpbmdTdGF0ZU1lc3NhZ2UucHJvdG8ikwEKGFNldFJlY29yZGluZ1N0YXRlTWVzc2FnZRI3CgVzdGF0ZRgBIAEoDjIoLlNldFJlY29yZGluZ1N0YXRlTWVzc2FnZS5SZWNvcmRpbmdTdGF0ZSI+Cg5SZWNvcmRpbmdTdGF0ZRILCgdVbmtub3duEAASDQoJUmVjb3JkaW5nEAESEAoMTm90UmVjb3JkaW5nEAI6ZwoYc2V0UmVjb3JkaW5nU3RhdGVNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGCMgASgLMhkuU2V0UmVjb3JkaW5nU3RhdGVNZXNzYWdlUhhzZXRSZWNvcmRpbmdTdGF0ZU1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message SetRecordingStateMessage
 */
export type SetRecordingStateMessage = Message<"SetRecordingStateMessage"> & {
  /**
   * @generated from field: optional SetRecordingStateMessage.RecordingState state = 1;
   */
  state: SetRecordingStateMessage_RecordingState;
};

/**
 * Describes the message SetRecordingStateMessage.
 * Use `create(SetRecordingStateMessageSchema)` to create a new message.
 */
export const SetRecordingStateMessageSchema: GenMessage<SetRecordingStateMessage> = /*@__PURE__*/
  messageDesc(file_SetRecordingStateMessage, 0);

/**
 * @generated from enum SetRecordingStateMessage.RecordingState
 */
export enum SetRecordingStateMessage_RecordingState {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Recording = 1;
   */
  Recording = 1,

  /**
   * @generated from enum value: NotRecording = 2;
   */
  NotRecording = 2,
}

/**
 * Describes the enum SetRecordingStateMessage.RecordingState.
 */
export const SetRecordingStateMessage_RecordingStateSchema: GenEnum<SetRecordingStateMessage_RecordingState> = /*@__PURE__*/
  enumDesc(file_SetRecordingStateMessage, 0, 0);

/**
 * @generated from extension: optional SetRecordingStateMessage setRecordingStateMessage = 35;
 */
export const setRecordingStateMessage: GenExtension<ProtocolMessage, SetRecordingStateMessage> = /*@__PURE__*/
  extDesc(file_SetRecordingStateMessage, 0);

