// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SetStateMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { NowPlayingInfo } from "./NowPlayingInfo_pb";
import { file_NowPlayingInfo } from "./NowPlayingInfo_pb";
import type { PlaybackQueue } from "./PlaybackQueue_pb";
import { file_PlaybackQueue } from "./PlaybackQueue_pb";
import type { SupportedCommands } from "./SupportedCommands_pb";
import { file_SupportedCommands } from "./SupportedCommands_pb";
import type { PlaybackQueueCapabilities } from "./PlaybackQueueCapabilities_pb";
import { file_PlaybackQueueCapabilities } from "./PlaybackQueueCapabilities_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { PlaybackQueueRequestMessage } from "./PlaybackQueueRequestMessage_pb";
import { file_PlaybackQueueRequestMessage } from "./PlaybackQueueRequestMessage_pb";
import type { PlaybackState_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetStateMessage.proto.
 */
export const file_SetStateMessage: GenFile = /*@__PURE__*/
  fileDesc("ChVTZXRTdGF0ZU1lc3NhZ2UucHJvdG8ikwMKD1NldFN0YXRlTWVzc2FnZRInCg5ub3dQbGF5aW5nSW5mbxgBIAEoCzIPLk5vd1BsYXlpbmdJbmZvEi0KEXN1cHBvcnRlZENvbW1hbmRzGAIgASgLMhIuU3VwcG9ydGVkQ29tbWFuZHMSJQoNcGxheWJhY2tRdWV1ZRgDIAEoCzIOLlBsYXliYWNrUXVldWUSEQoJZGlzcGxheUlEGAQgASgJEhMKC2Rpc3BsYXlOYW1lGAUgASgJEioKDXBsYXliYWNrU3RhdGUYBiABKA4yEy5QbGF5YmFja1N0YXRlLkVudW0SPQoZcGxheWJhY2tRdWV1ZUNhcGFiaWxpdGllcxgIIAEoCzIaLlBsYXliYWNrUXVldWVDYXBhYmlsaXRpZXMSHwoKcGxheWVyUGF0aBgJIAEoCzILLlBsYXllclBhdGgSLQoHcmVxdWVzdBgKIAEoCzIcLlBsYXliYWNrUXVldWVSZXF1ZXN0TWVzc2FnZRIeChZwbGF5YmFja1N0YXRlVGltZXN0YW1wGAsgASgBOkwKD3NldFN0YXRlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgJIAEoCzIQLlNldFN0YXRlTWVzc2FnZVIPc2V0U3RhdGVNZXNzYWdl", [file_ProtocolMessage, file_NowPlayingInfo, file_PlaybackQueue, file_SupportedCommands, file_PlaybackQueueCapabilities, file_PlayerPath, file_PlaybackQueueRequestMessage, file_Common]);

/**
 * @generated from message SetStateMessage
 */
export type SetStateMessage = Message<"SetStateMessage"> & {
  /**
   * @generated from field: optional NowPlayingInfo nowPlayingInfo = 1;
   */
  nowPlayingInfo?: NowPlayingInfo;

  /**
   * @generated from field: optional SupportedCommands supportedCommands = 2;
   */
  supportedCommands?: SupportedCommands;

  /**
   * @generated from field: optional PlaybackQueue playbackQueue = 3;
   */
  playbackQueue?: PlaybackQueue;

  /**
   * @generated from field: optional string displayID = 4;
   */
  displayID: string;

  /**
   * @generated from field: optional string displayName = 5;
   */
  displayName: string;

  /**
   * @generated from field: optional PlaybackState.Enum playbackState = 6;
   */
  playbackState: PlaybackState_Enum;

  /**
   * @generated from field: optional PlaybackQueueCapabilities playbackQueueCapabilities = 8;
   */
  playbackQueueCapabilities?: PlaybackQueueCapabilities;

  /**
   * @generated from field: optional PlayerPath playerPath = 9;
   */
  playerPath?: PlayerPath;

  /**
   * @generated from field: optional PlaybackQueueRequestMessage request = 10;
   */
  request?: PlaybackQueueRequestMessage;

  /**
   * @generated from field: optional double playbackStateTimestamp = 11;
   */
  playbackStateTimestamp: number;
};

/**
 * Describes the message SetStateMessage.
 * Use `create(SetStateMessageSchema)` to create a new message.
 */
export const SetStateMessageSchema: GenMessage<SetStateMessage> = /*@__PURE__*/
  messageDesc(file_SetStateMessage, 0);

/**
 * @generated from extension: optional SetStateMessage setStateMessage = 9;
 */
export const setStateMessage: GenExtension<ProtocolMessage, SetStateMessage> = /*@__PURE__*/
  extDesc(file_SetStateMessage, 0);

