// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file SetVolumeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SetVolumeMessage.proto.
 */
export const file_SetVolumeMessage: GenFile = /*@__PURE__*/
  fileDesc("ChZTZXRWb2x1bWVNZXNzYWdlLnByb3RvIjsKEFNldFZvbHVtZU1lc3NhZ2USDgoGdm9sdW1lGAEgASgCEhcKD291dHB1dERldmljZVVJRBgCIAEoCTpPChBzZXRWb2x1bWVNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGDcgASgLMhEuU2V0Vm9sdW1lTWVzc2FnZVIQc2V0Vm9sdW1lTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message SetVolumeMessage
 */
export type SetVolumeMessage = Message<"SetVolumeMessage"> & {
  /**
   * @generated from field: optional float volume = 1;
   */
  volume: number;

  /**
   * @generated from field: optional string outputDeviceUID = 2;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message SetVolumeMessage.
 * Use `create(SetVolumeMessageSchema)` to create a new message.
 */
export const SetVolumeMessageSchema: GenMessage<SetVolumeMessage> = /*@__PURE__*/
  messageDesc(file_SetVolumeMessage, 0);

/**
 * @generated from extension: optional SetVolumeMessage setVolumeMessage = 55;
 */
export const setVolumeMessage: GenExtension<ProtocolMessage, SetVolumeMessage> = /*@__PURE__*/
  extDesc(file_SetVolumeMessage, 0);

