// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file SupportedCommands.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CommandInfo } from "./CommandInfo_pb";
import { file_CommandInfo } from "./CommandInfo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SupportedCommands.proto.
 */
export const file_SupportedCommands: GenFile = /*@__PURE__*/
  fileDesc("ChdTdXBwb3J0ZWRDb21tYW5kcy5wcm90byI8ChFTdXBwb3J0ZWRDb21tYW5kcxInChFzdXBwb3J0ZWRDb21tYW5kcxgBIAMoCzIMLkNvbW1hbmRJbmZv", [file_CommandInfo]);

/**
 * @generated from message SupportedCommands
 */
export type SupportedCommands = Message<"SupportedCommands"> & {
  /**
   * @generated from field: repeated CommandInfo supportedCommands = 1;
   */
  supportedCommands: CommandInfo[];
};

/**
 * Describes the message SupportedCommands.
 * Use `create(SupportedCommandsSchema)` to create a new message.
 */
export const SupportedCommandsSchema: GenMessage<SupportedCommands> = /*@__PURE__*/
  messageDesc(file_SupportedCommands, 0);

