// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file SystemPlaybackQueue.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SystemPlaybackQueue.proto.
 */
export const file_SystemPlaybackQueue: GenFile = /*@__PURE__*/
  fileDesc("ChlTeXN0ZW1QbGF5YmFja1F1ZXVlLnByb3RvIoECChNTeXN0ZW1QbGF5YmFja1F1ZXVlEgwKBHR5cGUYASABKAUSFQoNcmVwbGFjZUludGVudBgCIAEoBRIlCh1pc1JlcXVlc3RpbmdJbW1lZGlhdGVQbGF5YmFjaxgDIAEoCBITCgtmZWF0dXJlTmFtZRgEIAEoCRItCgpjdXN0b21EYXRhGAYgASgLMhkuU3lzdGVtUGxheWJhY2tDdXN0b21EYXRhEjcKCXRyYWNrbGlzdBgHIAEoCzIkLlN5c3RlbVBsYXliYWNrR2VuZXJpY1RyYWNrbGlzdFF1ZXVlEhAKCHVzZXJJbmZvGAggASgMEg8KB21ldHJpY3MYCSABKAwiPAoYU3lzdGVtUGxheWJhY2tDdXN0b21EYXRhEhIKCmlkZW50aWZpZXIYASABKAkSDAoEZGF0YRgCIAEoDCKnAQojU3lzdGVtUGxheWJhY2tHZW5lcmljVHJhY2tsaXN0UXVldWUSHAoUZmlyc3RUcmFja0lkZW50aWZpZXIYASABKAkSGAoQdHJhY2tJZGVudGlmaWVycxgCIAEoCRIfChdjb2xsZWN0aW9uSWRlbnRpZmllclNldBgDIAEoDBITCgtzaHVmZmxlTW9kZRgEIAEoDRISCgpyZXBlYXRNb2RlGAUgASgN");

/**
 * @generated from message SystemPlaybackQueue
 */
export type SystemPlaybackQueue = Message<"SystemPlaybackQueue"> & {
  /**
   * @generated from field: optional int32 type = 1;
   */
  type: number;

  /**
   * @generated from field: optional int32 replaceIntent = 2;
   */
  replaceIntent: number;

  /**
   * @generated from field: optional bool isRequestingImmediatePlayback = 3;
   */
  isRequestingImmediatePlayback: boolean;

  /**
   * @generated from field: optional string featureName = 4;
   */
  featureName: string;

  /**
   * @generated from field: optional SystemPlaybackCustomData customData = 6;
   */
  customData?: SystemPlaybackCustomData;

  /**
   * @generated from field: optional SystemPlaybackGenericTracklistQueue tracklist = 7;
   */
  tracklist?: SystemPlaybackGenericTracklistQueue;

  /**
   * @generated from field: optional bytes userInfo = 8;
   */
  userInfo: Uint8Array;

  /**
   * @generated from field: optional bytes metrics = 9;
   */
  metrics: Uint8Array;
};

/**
 * Describes the message SystemPlaybackQueue.
 * Use `create(SystemPlaybackQueueSchema)` to create a new message.
 */
export const SystemPlaybackQueueSchema: GenMessage<SystemPlaybackQueue> = /*@__PURE__*/
  messageDesc(file_SystemPlaybackQueue, 0);

/**
 * @generated from message SystemPlaybackCustomData
 */
export type SystemPlaybackCustomData = Message<"SystemPlaybackCustomData"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message SystemPlaybackCustomData.
 * Use `create(SystemPlaybackCustomDataSchema)` to create a new message.
 */
export const SystemPlaybackCustomDataSchema: GenMessage<SystemPlaybackCustomData> = /*@__PURE__*/
  messageDesc(file_SystemPlaybackQueue, 1);

/**
 * @generated from message SystemPlaybackGenericTracklistQueue
 */
export type SystemPlaybackGenericTracklistQueue = Message<"SystemPlaybackGenericTracklistQueue"> & {
  /**
   * @generated from field: optional string firstTrackIdentifier = 1;
   */
  firstTrackIdentifier: string;

  /**
   * @generated from field: optional string trackIdentifiers = 2;
   */
  trackIdentifiers: string;

  /**
   * @generated from field: optional bytes collectionIdentifierSet = 3;
   */
  collectionIdentifierSet: Uint8Array;

  /**
   * @generated from field: optional uint32 shuffleMode = 4;
   */
  shuffleMode: number;

  /**
   * @generated from field: optional uint32 repeatMode = 5;
   */
  repeatMode: number;
};

/**
 * Describes the message SystemPlaybackGenericTracklistQueue.
 * Use `create(SystemPlaybackGenericTracklistQueueSchema)` to create a new message.
 */
export const SystemPlaybackGenericTracklistQueueSchema: GenMessage<SystemPlaybackGenericTracklistQueue> = /*@__PURE__*/
  messageDesc(file_SystemPlaybackQueue, 2);

