// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file TextInputMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file TextInputMessage.proto.
 */
export const file_TextInputMessage: GenFile = /*@__PURE__*/
  fileDesc("ChZUZXh0SW5wdXRNZXNzYWdlLnByb3RvIlMKCkFjdGlvblR5cGUiRQoERW51bRILCgdVbmtub3duEAASCgoGSW5zZXJ0EAESBwoDU2V0EAISCgoGRGVsZXRlEAMSDwoLQ2xlYXJBY3Rpb24QBCJZChBUZXh0SW5wdXRNZXNzYWdlEhEKCXRpbWVzdGFtcBgBIAEoARIMCgR0ZXh0GAIgASgJEiQKCmFjdGlvblR5cGUYAyABKA4yEC5BY3Rpb25UeXBlLkVudW06TwoQdGV4dElucHV0TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgeIAEoCzIRLlRleHRJbnB1dE1lc3NhZ2VSEHRleHRJbnB1dE1lc3NhZ2U", [file_ProtocolMessage]);

/**
 * @generated from message ActionType
 */
export type ActionType = Message<"ActionType"> & {
};

/**
 * Describes the message ActionType.
 * Use `create(ActionTypeSchema)` to create a new message.
 */
export const ActionTypeSchema: GenMessage<ActionType> = /*@__PURE__*/
  messageDesc(file_TextInputMessage, 0);

/**
 * @generated from enum ActionType.Enum
 */
export enum ActionType_Enum {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Insert = 1;
   */
  Insert = 1,

  /**
   * @generated from enum value: Set = 2;
   */
  Set = 2,

  /**
   * @generated from enum value: Delete = 3;
   */
  Delete = 3,

  /**
   * "Clear" clashes with something, making mypy unhappy
   *
   * @generated from enum value: ClearAction = 4;
   */
  ClearAction = 4,
}

/**
 * Describes the enum ActionType.Enum.
 */
export const ActionType_EnumSchema: GenEnum<ActionType_Enum> = /*@__PURE__*/
  enumDesc(file_TextInputMessage, 0, 0);

/**
 * @generated from message TextInputMessage
 */
export type TextInputMessage = Message<"TextInputMessage"> & {
  /**
   * @generated from field: optional double timestamp = 1;
   */
  timestamp: number;

  /**
   * @generated from field: optional string text = 2;
   */
  text: string;

  /**
   * @generated from field: optional ActionType.Enum actionType = 3;
   */
  actionType: ActionType_Enum;
};

/**
 * Describes the message TextInputMessage.
 * Use `create(TextInputMessageSchema)` to create a new message.
 */
export const TextInputMessageSchema: GenMessage<TextInputMessage> = /*@__PURE__*/
  messageDesc(file_TextInputMessage, 1);

/**
 * @generated from extension: optional TextInputMessage textInputMessage = 30;
 */
export const textInputMessage: GenExtension<ProtocolMessage, TextInputMessage> = /*@__PURE__*/
  extDesc(file_TextInputMessage, 0);

