// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file Transcript.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Transcript.proto.
 */
export const file_Transcript: GenFile = /*@__PURE__*/
  fileDesc("ChBUcmFuc2NyaXB0LnByb3RvIqkBChNUcmFuc2NyaXB0QWxpZ25tZW50EhcKD3BsYXllclN0YXJ0VGltZRgBIAEoBhIVCg1wbGF5ZXJFbmRUaW1lGAIgASgGEhoKEnJlZmVyZW5jZVN0YXJ0VGltZRgDIAEoBhIYChByZWZlcmVuY2VFbmRUaW1lGAQgASgGEhgKEG1hdGNoZWRCZWdpbm5pbmcYBSABKAgSEgoKbWF0Y2hlZEVuZBgGIAEoCA");

/**
 * @generated from message TranscriptAlignment
 */
export type TranscriptAlignment = Message<"TranscriptAlignment"> & {
  /**
   * @generated from field: optional fixed64 playerStartTime = 1;
   */
  playerStartTime: bigint;

  /**
   * @generated from field: optional fixed64 playerEndTime = 2;
   */
  playerEndTime: bigint;

  /**
   * @generated from field: optional fixed64 referenceStartTime = 3;
   */
  referenceStartTime: bigint;

  /**
   * @generated from field: optional fixed64 referenceEndTime = 4;
   */
  referenceEndTime: bigint;

  /**
   * @generated from field: optional bool matchedBeginning = 5;
   */
  matchedBeginning: boolean;

  /**
   * @generated from field: optional bool matchedEnd = 6;
   */
  matchedEnd: boolean;
};

/**
 * Describes the message TranscriptAlignment.
 * Use `create(TranscriptAlignmentSchema)` to create a new message.
 */
export const TranscriptAlignmentSchema: GenMessage<TranscriptAlignment> = /*@__PURE__*/
  messageDesc(file_Transcript, 0);

