// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file TransactionMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TransactionPackets } from "./TransactionPackets_pb";
import { file_TransactionPackets } from "./TransactionPackets_pb";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file TransactionMessage.proto.
 */
export const file_TransactionMessage: GenFile = /*@__PURE__*/
  fileDesc("ChhUcmFuc2FjdGlvbk1lc3NhZ2UucHJvdG8iaQoSVHJhbnNhY3Rpb25NZXNzYWdlEgwKBG5hbWUYASABKAQSJAoHcGFja2V0cxgCIAEoCzITLlRyYW5zYWN0aW9uUGFja2V0cxIfCgpwbGF5ZXJQYXRoGAMgASgLMgsuUGxheWVyUGF0aDpVChJ0cmFuc2FjdGlvbk1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYJiABKAsyEy5UcmFuc2FjdGlvbk1lc3NhZ2VSEnRyYW5zYWN0aW9uTWVzc2FnZQ", [file_TransactionPackets, file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message TransactionMessage
 */
export type TransactionMessage = Message<"TransactionMessage"> & {
  /**
   * @generated from field: optional uint64 name = 1;
   */
  name: bigint;

  /**
   * @generated from field: optional TransactionPackets packets = 2;
   */
  packets?: TransactionPackets;

  /**
   * @generated from field: optional PlayerPath playerPath = 3;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message TransactionMessage.
 * Use `create(TransactionMessageSchema)` to create a new message.
 */
export const TransactionMessageSchema: GenMessage<TransactionMessage> = /*@__PURE__*/
  messageDesc(file_TransactionMessage, 0);

/**
 * @generated from extension: optional TransactionMessage transactionMessage = 38;
 */
export const transactionMessage: GenExtension<ProtocolMessage, TransactionMessage> = /*@__PURE__*/
  extDesc(file_TransactionMessage, 0);

