// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file TransactionPacket.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TransactionKey } from "./TransactionKey_pb";
import { file_TransactionKey } from "./TransactionKey_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file TransactionPacket.proto.
 */
export const file_TransactionPacket: GenFile = /*@__PURE__*/
  fileDesc("ChdUcmFuc2FjdGlvblBhY2tldC5wcm90byKKAQoRVHJhbnNhY3Rpb25QYWNrZXQSHAoDa2V5GAEgASgLMg8uVHJhbnNhY3Rpb25LZXkSEgoKcGFja2V0RGF0YRgCIAEoDBISCgppZGVudGlmaWVyGAMgASgJEhMKC3RvdGFsTGVuZ3RoGAQgASgEEhoKEnRvdGFsV3JpdGVQb3NpdGlvbhgFIAEoBA", [file_TransactionKey]);

/**
 * @generated from message TransactionPacket
 */
export type TransactionPacket = Message<"TransactionPacket"> & {
  /**
   * @generated from field: optional TransactionKey key = 1;
   */
  key?: TransactionKey;

  /**
   * @generated from field: optional bytes packetData = 2;
   */
  packetData: Uint8Array;

  /**
   * @generated from field: optional string identifier = 3;
   */
  identifier: string;

  /**
   * @generated from field: optional uint64 totalLength = 4;
   */
  totalLength: bigint;

  /**
   * @generated from field: optional uint64 totalWritePosition = 5;
   */
  totalWritePosition: bigint;
};

/**
 * Describes the message TransactionPacket.
 * Use `create(TransactionPacketSchema)` to create a new message.
 */
export const TransactionPacketSchema: GenMessage<TransactionPacket> = /*@__PURE__*/
  messageDesc(file_TransactionPacket, 0);

