// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file TransactionPackets.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TransactionPacket } from "./TransactionPacket_pb";
import { file_TransactionPacket } from "./TransactionPacket_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file TransactionPackets.proto.
 */
export const file_TransactionPackets: GenFile = /*@__PURE__*/
  fileDesc("ChhUcmFuc2FjdGlvblBhY2tldHMucHJvdG8iOQoSVHJhbnNhY3Rpb25QYWNrZXRzEiMKB3BhY2tldHMYASADKAsyEi5UcmFuc2FjdGlvblBhY2tldA", [file_TransactionPacket]);

/**
 * @generated from message TransactionPackets
 */
export type TransactionPackets = Message<"TransactionPackets"> & {
  /**
   * @generated from field: repeated TransactionPacket packets = 1;
   */
  packets: TransactionPacket[];
};

/**
 * Describes the message TransactionPackets.
 * Use `create(TransactionPacketsSchema)` to create a new message.
 */
export const TransactionPacketsSchema: GenMessage<TransactionPackets> = /*@__PURE__*/
  messageDesc(file_TransactionPackets, 0);

