// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file TransactionKey.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file TransactionKey.proto.
 */
export const file_TransactionKey: GenFile = /*@__PURE__*/
  fileDesc("ChRUcmFuc2FjdGlvbktleS5wcm90byI2Cg5UcmFuc2FjdGlvbktleRISCgppZGVudGlmaWVyGAEgASgJEhAKCHVzZXJEYXRhGAIgASgM");

/**
 * @generated from message TransactionKey
 */
export type TransactionKey = Message<"TransactionKey"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional bytes userData = 2;
   */
  userData: Uint8Array;
};

/**
 * Describes the message TransactionKey.
 * Use `create(TransactionKeySchema)` to create a new message.
 */
export const TransactionKeySchema: GenMessage<TransactionKey> = /*@__PURE__*/
  messageDesc(file_TransactionKey, 0);

