// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UnregisterGameControllerMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UnregisterGameControllerMessage.proto.
 */
export const file_UnregisterGameControllerMessage: GenFile = /*@__PURE__*/
  fileDesc("CiVVbnJlZ2lzdGVyR2FtZUNvbnRyb2xsZXJNZXNzYWdlLnByb3RvIjcKH1VucmVnaXN0ZXJHYW1lQ29udHJvbGxlck1lc3NhZ2USFAoMY29udHJvbGxlcklEGAEgASgEOnwKH3VucmVnaXN0ZXJHYW1lQ29udHJvbGxlck1lc3NhZ2USEC5Qcm90b2NvbE1lc3NhZ2UYGiABKAsyIC5VbnJlZ2lzdGVyR2FtZUNvbnRyb2xsZXJNZXNzYWdlUh91bnJlZ2lzdGVyR2FtZUNvbnRyb2xsZXJNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message UnregisterGameControllerMessage
 */
export type UnregisterGameControllerMessage = Message<"UnregisterGameControllerMessage"> & {
  /**
   * @generated from field: optional uint64 controllerID = 1;
   */
  controllerID: bigint;
};

/**
 * Describes the message UnregisterGameControllerMessage.
 * Use `create(UnregisterGameControllerMessageSchema)` to create a new message.
 */
export const UnregisterGameControllerMessageSchema: GenMessage<UnregisterGameControllerMessage> = /*@__PURE__*/
  messageDesc(file_UnregisterGameControllerMessage, 0);

/**
 * @generated from extension: optional UnregisterGameControllerMessage unregisterGameControllerMessage = 26;
 */
export const unregisterGameControllerMessage: GenExtension<ProtocolMessage, UnregisterGameControllerMessage> = /*@__PURE__*/
  extDesc(file_UnregisterGameControllerMessage, 0);

