// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file UpdateContentItemArtworkMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { ContentItem } from "./ContentItem_pb";
import { file_ContentItem } from "./ContentItem_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdateContentItemArtworkMessage.proto.
 */
export const file_UpdateContentItemArtworkMessage: GenFile = /*@__PURE__*/
  fileDesc("CiVVcGRhdGVDb250ZW50SXRlbUFydHdvcmtNZXNzYWdlLnByb3RvImYKH1VwZGF0ZUNvbnRlbnRJdGVtQXJ0d29ya01lc3NhZ2USIgoMY29udGVudEl0ZW1zGAEgAygLMgwuQ29udGVudEl0ZW0SHwoKcGxheWVyUGF0aBgCIAEoCzILLlBsYXllclBhdGg6fAofdXBkYXRlQ29udGVudEl0ZW1BcnR3b3JrTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRg9IAEoCzIgLlVwZGF0ZUNvbnRlbnRJdGVtQXJ0d29ya01lc3NhZ2VSH3VwZGF0ZUNvbnRlbnRJdGVtQXJ0d29ya01lc3NhZ2U", [file_ProtocolMessage, file_ContentItem, file_PlayerPath]);

/**
 * @generated from message UpdateContentItemArtworkMessage
 */
export type UpdateContentItemArtworkMessage = Message<"UpdateContentItemArtworkMessage"> & {
  /**
   * @generated from field: repeated ContentItem contentItems = 1;
   */
  contentItems: ContentItem[];

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message UpdateContentItemArtworkMessage.
 * Use `create(UpdateContentItemArtworkMessageSchema)` to create a new message.
 */
export const UpdateContentItemArtworkMessageSchema: GenMessage<UpdateContentItemArtworkMessage> = /*@__PURE__*/
  messageDesc(file_UpdateContentItemArtworkMessage, 0);

/**
 * @generated from extension: optional UpdateContentItemArtworkMessage updateContentItemArtworkMessage = 61;
 */
export const updateContentItemArtworkMessage: GenExtension<ProtocolMessage, UpdateContentItemArtworkMessage> = /*@__PURE__*/
  extDesc(file_UpdateContentItemArtworkMessage, 0);

