// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UpdateActiveSystemEndpointRequest.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ChangeType_Enum } from "./Common_pb";
import { file_Common } from "./Common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdateActiveSystemEndpointRequest.proto.
 */
export const file_UpdateActiveSystemEndpointRequest: GenFile = /*@__PURE__*/
  fileDesc("CidVcGRhdGVBY3RpdmVTeXN0ZW1FbmRwb2ludFJlcXVlc3QucHJvdG8i+gEKIVVwZGF0ZUFjdGl2ZVN5c3RlbUVuZHBvaW50UmVxdWVzdBIXCg9vdXRwdXREZXZpY2VVaWQYASABKAkSJAoKY2hhbmdlVHlwZRgCIAEoDjIQLkNoYW5nZVR5cGUuRW51bRIOCgZyZWFzb24YAyABKAkSGAoQcGFpcmVkRGV2aWNlU3luYxgEIAEoCBIMCgR0eXBlGAUgASgEEhcKD2Rpc2FibGVEdXJhdGlvbhgGIAEoARIkChxkZW1vdGVXaGVuU3luY2luZ1RvQ29tcGFuaW9uGAcgASgIEh8KF3ByZXZpb3VzT3V0cHV0RGV2aWNlVWlkGAggASgJ", [file_Common]);

/**
 * @generated from message UpdateActiveSystemEndpointRequest
 */
export type UpdateActiveSystemEndpointRequest = Message<"UpdateActiveSystemEndpointRequest"> & {
  /**
   * @generated from field: optional string outputDeviceUid = 1;
   */
  outputDeviceUid: string;

  /**
   * @generated from field: optional ChangeType.Enum changeType = 2;
   */
  changeType: ChangeType_Enum;

  /**
   * @generated from field: optional string reason = 3;
   */
  reason: string;

  /**
   * @generated from field: optional bool pairedDeviceSync = 4;
   */
  pairedDeviceSync: boolean;

  /**
   * @generated from field: optional uint64 type = 5;
   */
  type: bigint;

  /**
   * @generated from field: optional double disableDuration = 6;
   */
  disableDuration: number;

  /**
   * @generated from field: optional bool demoteWhenSyncingToCompanion = 7;
   */
  demoteWhenSyncingToCompanion: boolean;

  /**
   * @generated from field: optional string previousOutputDeviceUid = 8;
   */
  previousOutputDeviceUid: string;
};

/**
 * Describes the message UpdateActiveSystemEndpointRequest.
 * Use `create(UpdateActiveSystemEndpointRequestSchema)` to create a new message.
 */
export const UpdateActiveSystemEndpointRequestSchema: GenMessage<UpdateActiveSystemEndpointRequest> = /*@__PURE__*/
  messageDesc(file_UpdateActiveSystemEndpointRequest, 0);

