// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UpdatePlayerPath.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdatePlayerPath.proto.
 */
export const file_UpdatePlayerPath: GenFile = /*@__PURE__*/
  fileDesc("ChZVcGRhdGVQbGF5ZXJQYXRoLnByb3RvIjYKE1VwZGF0ZVBsYXllck1lc3NhZ2USHwoKcGxheWVyUGF0aBgBIAEoCzILLlBsYXllclBhdGg6WAoTdXBkYXRlUGxheWVyTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRg+IAEoCzIULlVwZGF0ZVBsYXllck1lc3NhZ2VSE3VwZGF0ZVBsYXllck1lc3NhZ2U", [file_ProtocolMessage, file_PlayerPath]);

/**
 * @generated from message UpdatePlayerMessage
 */
export type UpdatePlayerMessage = Message<"UpdatePlayerMessage"> & {
  /**
   * @generated from field: optional PlayerPath playerPath = 1;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message UpdatePlayerMessage.
 * Use `create(UpdatePlayerMessageSchema)` to create a new message.
 */
export const UpdatePlayerMessageSchema: GenMessage<UpdatePlayerMessage> = /*@__PURE__*/
  messageDesc(file_UpdatePlayerPath, 0);

/**
 * @generated from extension: optional UpdatePlayerMessage updatePlayerMessage = 62;
 */
export const updatePlayerMessage: GenExtension<ProtocolMessage, UpdatePlayerMessage> = /*@__PURE__*/
  extDesc(file_UpdatePlayerPath, 0);

