// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UpdateEndPointsMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdateEndPointsMessage.proto.
 */
export const file_UpdateEndPointsMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxVcGRhdGVFbmRQb2ludHNNZXNzYWdlLnByb3RvIskBChRBVkVuZHBvaW50RGVzY3JpcHRvchIMCgRuYW1lGAEgASgJEhgKEHVuaXF1ZUlkZW50aWZpZXIYAiABKAkSFwoPaXNMb2NhbEVuZHBvaW50GAUgASgIEhoKEmluc3RhbmNlSWRlbnRpZmllchgGIAEoCRIaChJpc1Byb3h5R3JvdXBQbGF5ZXIYByABKAgSFgoOY29ubmVjdGlvblR5cGUYCCABKAUSIAoYY2FuTW9kaWZ5R3JvdXBNZW1iZXJzaGlwGAkgASgIIlwKFlVwZGF0ZUVuZFBvaW50c01lc3NhZ2USKAoJZW5kcG9pbnRzGAEgASgLMhUuQVZFbmRwb2ludERlc2NyaXB0b3ISGAoQZW5kcG9pbnRGZWF0dXJlcxgCIAEoBTphChZ1cGRhdGVFbmRQb2ludHNNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGFMgASgLMhcuVXBkYXRlRW5kUG9pbnRzTWVzc2FnZVIWdXBkYXRlRW5kUG9pbnRzTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message AVEndpointDescriptor
 */
export type AVEndpointDescriptor = Message<"AVEndpointDescriptor"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional string uniqueIdentifier = 2;
   */
  uniqueIdentifier: string;

  /**
   * repeated ... outputDevices = 3;
   * optional ... designatedGroupLeader = 4;
   *
   * @generated from field: optional bool isLocalEndpoint = 5;
   */
  isLocalEndpoint: boolean;

  /**
   * @generated from field: optional string instanceIdentifier = 6;
   */
  instanceIdentifier: string;

  /**
   * @generated from field: optional bool isProxyGroupPlayer = 7;
   */
  isProxyGroupPlayer: boolean;

  /**
   * @generated from field: optional int32 connectionType = 8;
   */
  connectionType: number;

  /**
   * repeated ... _personalOutputDevices = 10;
   *
   * @generated from field: optional bool canModifyGroupMembership = 9;
   */
  canModifyGroupMembership: boolean;
};

/**
 * Describes the message AVEndpointDescriptor.
 * Use `create(AVEndpointDescriptorSchema)` to create a new message.
 */
export const AVEndpointDescriptorSchema: GenMessage<AVEndpointDescriptor> = /*@__PURE__*/
  messageDesc(file_UpdateEndPointsMessage, 0);

/**
 * @generated from message UpdateEndPointsMessage
 */
export type UpdateEndPointsMessage = Message<"UpdateEndPointsMessage"> & {
  /**
   * @generated from field: optional AVEndpointDescriptor endpoints = 1;
   */
  endpoints?: AVEndpointDescriptor;

  /**
   * @generated from field: optional int32 endpointFeatures = 2;
   */
  endpointFeatures: number;
};

/**
 * Describes the message UpdateEndPointsMessage.
 * Use `create(UpdateEndPointsMessageSchema)` to create a new message.
 */
export const UpdateEndPointsMessageSchema: GenMessage<UpdateEndPointsMessage> = /*@__PURE__*/
  messageDesc(file_UpdateEndPointsMessage, 1);

/**
 * @generated from extension: optional UpdateEndPointsMessage updateEndPointsMessage = 83;
 */
export const updateEndPointsMessage: GenExtension<ProtocolMessage, UpdateEndPointsMessage> = /*@__PURE__*/
  extDesc(file_UpdateEndPointsMessage, 0);

