// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UpdateContentItemMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { ContentItem } from "./ContentItem_pb";
import { file_ContentItem } from "./ContentItem_pb";
import type { PlayerPath } from "./PlayerPath_pb";
import { file_PlayerPath } from "./PlayerPath_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdateContentItemMessage.proto.
 */
export const file_UpdateContentItemMessage: GenFile = /*@__PURE__*/
  fileDesc("Ch5VcGRhdGVDb250ZW50SXRlbU1lc3NhZ2UucHJvdG8iXwoYVXBkYXRlQ29udGVudEl0ZW1NZXNzYWdlEiIKDGNvbnRlbnRJdGVtcxgBIAMoCzIMLkNvbnRlbnRJdGVtEh8KCnBsYXllclBhdGgYAiABKAsyCy5QbGF5ZXJQYXRoOmcKGHVwZGF0ZUNvbnRlbnRJdGVtTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRg8IAEoCzIZLlVwZGF0ZUNvbnRlbnRJdGVtTWVzc2FnZVIYdXBkYXRlQ29udGVudEl0ZW1NZXNzYWdl", [file_ProtocolMessage, file_ContentItem, file_PlayerPath]);

/**
 * @generated from message UpdateContentItemMessage
 */
export type UpdateContentItemMessage = Message<"UpdateContentItemMessage"> & {
  /**
   * @generated from field: repeated ContentItem contentItems = 1;
   */
  contentItems: ContentItem[];

  /**
   * @generated from field: optional PlayerPath playerPath = 2;
   */
  playerPath?: PlayerPath;
};

/**
 * Describes the message UpdateContentItemMessage.
 * Use `create(UpdateContentItemMessageSchema)` to create a new message.
 */
export const UpdateContentItemMessageSchema: GenMessage<UpdateContentItemMessage> = /*@__PURE__*/
  messageDesc(file_UpdateContentItemMessage, 0);

/**
 * @generated from extension: optional UpdateContentItemMessage updateContentItemMessage = 60;
 */
export const updateContentItemMessage: GenExtension<ProtocolMessage, UpdateContentItemMessage> = /*@__PURE__*/
  extDesc(file_UpdateContentItemMessage, 0);

