// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UpdateActiveSystemEndpointMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { UpdateActiveSystemEndpointRequest } from "./UpdateActiveSystemEndpointRequest_pb";
import { file_UpdateActiveSystemEndpointRequest } from "./UpdateActiveSystemEndpointRequest_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UpdateActiveSystemEndpointMessage.proto.
 */
export const file_UpdateActiveSystemEndpointMessage: GenFile = /*@__PURE__*/
  fileDesc("CidVcGRhdGVBY3RpdmVTeXN0ZW1FbmRwb2ludE1lc3NhZ2UucHJvdG8iWAohVXBkYXRlQWN0aXZlU3lzdGVtRW5kcG9pbnRNZXNzYWdlEjMKB3JlcXVlc3QYASABKAsyIi5VcGRhdGVBY3RpdmVTeXN0ZW1FbmRwb2ludFJlcXVlc3Q6ggEKIXVwZGF0ZUFjdGl2ZVN5c3RlbUVuZHBvaW50TWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhRIAEoCzIiLlVwZGF0ZUFjdGl2ZVN5c3RlbUVuZHBvaW50TWVzc2FnZVIhdXBkYXRlQWN0aXZlU3lzdGVtRW5kcG9pbnRNZXNzYWdl", [file_ProtocolMessage, file_UpdateActiveSystemEndpointRequest]);

/**
 * @generated from message UpdateActiveSystemEndpointMessage
 */
export type UpdateActiveSystemEndpointMessage = Message<"UpdateActiveSystemEndpointMessage"> & {
  /**
   * @generated from field: optional UpdateActiveSystemEndpointRequest request = 1;
   */
  request?: UpdateActiveSystemEndpointRequest;
};

/**
 * Describes the message UpdateActiveSystemEndpointMessage.
 * Use `create(UpdateActiveSystemEndpointMessageSchema)` to create a new message.
 */
export const UpdateActiveSystemEndpointMessageSchema: GenMessage<UpdateActiveSystemEndpointMessage> = /*@__PURE__*/
  messageDesc(file_UpdateActiveSystemEndpointMessage, 0);

/**
 * @generated from extension: optional UpdateActiveSystemEndpointMessage updateActiveSystemEndpointMessage = 81;
 */
export const updateActiveSystemEndpointMessage: GenExtension<ProtocolMessage, UpdateActiveSystemEndpointMessage> = /*@__PURE__*/
  extDesc(file_UpdateActiveSystemEndpointMessage, 0);

