// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file UserIdentity.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file UserIdentity.proto.
 */
export const file_UserIdentity: GenFile = /*@__PURE__*/
  fileDesc("ChJVc2VySWRlbnRpdHkucHJvdG8ijAEKDFVzZXJJZGVudGl0eRISCgppZGVudGlmaWVyGAEgASgJEhMKC2Rpc3BsYXlOYW1lGAIgASgJEiAKBHR5cGUYAyABKA4yEi5Vc2VySWRlbnRpdHkuVHlwZSIxCgRUeXBlEgsKB1Vua25vd24QABILCgdBcHBsZUlEEAESDwoLRGV2aWNlTG9jYWwQAg");

/**
 * @generated from message UserIdentity
 */
export type UserIdentity = Message<"UserIdentity"> & {
  /**
   * @generated from field: optional string identifier = 1;
   */
  identifier: string;

  /**
   * @generated from field: optional string displayName = 2;
   */
  displayName: string;

  /**
   * @generated from field: optional UserIdentity.Type type = 3;
   */
  type: UserIdentity_Type;
};

/**
 * Describes the message UserIdentity.
 * Use `create(UserIdentitySchema)` to create a new message.
 */
export const UserIdentitySchema: GenMessage<UserIdentity> = /*@__PURE__*/
  messageDesc(file_UserIdentity, 0);

/**
 * @generated from enum UserIdentity.Type
 */
export enum UserIdentity_Type {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: AppleID = 1;
   */
  AppleID = 1,

  /**
   * @generated from enum value: DeviceLocal = 2;
   */
  DeviceLocal = 2,
}

/**
 * Describes the enum UserIdentity.Type.
 */
export const UserIdentity_TypeSchema: GenEnum<UserIdentity_Type> = /*@__PURE__*/
  enumDesc(file_UserIdentity, 0, 0);

