// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file VideoThumbnail.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VideoThumbnail.proto.
 */
export const file_VideoThumbnail: GenFile = /*@__PURE__*/
  fileDesc("ChRWaWRlb1RodW1ibmFpbC5wcm90byIxCg5WaWRlb1RodW1ibmFpbBIRCglpbWFnZURhdGEYASABKAwSDAoEdGltZRgCIAEoASJhChVWaWRlb1RodW1ibmFpbFJlcXVlc3QSFwoPdGh1bWJuYWlsc1dpZHRoGAEgASgFEhgKEHRodW1ibmFpbHNIZWlnaHQYAiABKAUSFQoNdGltZUludGVydmFscxgDIAMoAQ");

/**
 * @generated from message VideoThumbnail
 */
export type VideoThumbnail = Message<"VideoThumbnail"> & {
  /**
   * @generated from field: optional bytes imageData = 1;
   */
  imageData: Uint8Array;

  /**
   * @generated from field: optional double time = 2;
   */
  time: number;
};

/**
 * Describes the message VideoThumbnail.
 * Use `create(VideoThumbnailSchema)` to create a new message.
 */
export const VideoThumbnailSchema: GenMessage<VideoThumbnail> = /*@__PURE__*/
  messageDesc(file_VideoThumbnail, 0);

/**
 * @generated from message VideoThumbnailRequest
 */
export type VideoThumbnailRequest = Message<"VideoThumbnailRequest"> & {
  /**
   * @generated from field: optional int32 thumbnailsWidth = 1;
   */
  thumbnailsWidth: number;

  /**
   * @generated from field: optional int32 thumbnailsHeight = 2;
   */
  thumbnailsHeight: number;

  /**
   * @generated from field: repeated double timeIntervals = 3;
   */
  timeIntervals: number[];
};

/**
 * Describes the message VideoThumbnailRequest.
 * Use `create(VideoThumbnailRequestSchema)` to create a new message.
 */
export const VideoThumbnailRequestSchema: GenMessage<VideoThumbnailRequest> = /*@__PURE__*/
  messageDesc(file_VideoThumbnail, 1);

