// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file VirtualTouchDeviceDescriptorMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VirtualTouchDeviceDescriptorMessage.proto.
 */
export const file_VirtualTouchDeviceDescriptorMessage: GenFile = /*@__PURE__*/
  fileDesc("CilWaXJ0dWFsVG91Y2hEZXZpY2VEZXNjcmlwdG9yTWVzc2FnZS5wcm90byJ+ChxWaXJ0dWFsVG91Y2hEZXZpY2VEZXNjcmlwdG9yEhAKCGFic29sdXRlGAEgASgIEhkKEWludGVncmF0ZWREaXNwbGF5GAIgASgIEhcKD3NjcmVlblNpemVXaWR0aBgDIAEoAhIYChBzY3JlZW5TaXplSGVpZ2h0GAQgASgC");

/**
 * @generated from message VirtualTouchDeviceDescriptor
 */
export type VirtualTouchDeviceDescriptor = Message<"VirtualTouchDeviceDescriptor"> & {
  /**
   * @generated from field: optional bool absolute = 1;
   */
  absolute: boolean;

  /**
   * @generated from field: optional bool integratedDisplay = 2;
   */
  integratedDisplay: boolean;

  /**
   * @generated from field: optional float screenSizeWidth = 3;
   */
  screenSizeWidth: number;

  /**
   * @generated from field: optional float screenSizeHeight = 4;
   */
  screenSizeHeight: number;
};

/**
 * Describes the message VirtualTouchDeviceDescriptor.
 * Use `create(VirtualTouchDeviceDescriptorSchema)` to create a new message.
 */
export const VirtualTouchDeviceDescriptorSchema: GenMessage<VirtualTouchDeviceDescriptor> = /*@__PURE__*/
  messageDesc(file_VirtualTouchDeviceDescriptorMessage, 0);

