// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file VoiceInputDeviceDescriptorMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AudioFormatSettings } from "./AudioFormatSettingsMessage_pb";
import { file_AudioFormatSettingsMessage } from "./AudioFormatSettingsMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VoiceInputDeviceDescriptorMessage.proto.
 */
export const file_VoiceInputDeviceDescriptorMessage: GenFile = /*@__PURE__*/
  fileDesc("CidWb2ljZUlucHV0RGV2aWNlRGVzY3JpcHRvck1lc3NhZ2UucHJvdG8ieQoaVm9pY2VJbnB1dERldmljZURlc2NyaXB0b3ISKwoNZGVmYXVsdEZvcm1hdBgBIAEoCzIULkF1ZGlvRm9ybWF0U2V0dGluZ3MSLgoQc3VwcG9ydGVkRm9ybWF0cxgCIAMoCzIULkF1ZGlvRm9ybWF0U2V0dGluZ3M", [file_AudioFormatSettingsMessage]);

/**
 * @generated from message VoiceInputDeviceDescriptor
 */
export type VoiceInputDeviceDescriptor = Message<"VoiceInputDeviceDescriptor"> & {
  /**
   * @generated from field: optional AudioFormatSettings defaultFormat = 1;
   */
  defaultFormat?: AudioFormatSettings;

  /**
   * @generated from field: repeated AudioFormatSettings supportedFormats = 2;
   */
  supportedFormats: AudioFormatSettings[];
};

/**
 * Describes the message VoiceInputDeviceDescriptor.
 * Use `create(VoiceInputDeviceDescriptorSchema)` to create a new message.
 */
export const VoiceInputDeviceDescriptorSchema: GenMessage<VoiceInputDeviceDescriptor> = /*@__PURE__*/
  messageDesc(file_VoiceInputDeviceDescriptorMessage, 0);

