// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file VolumeControlCapabilitiesDidChangeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { VolumeControlAvailabilityMessage } from "./VolumeControlAvailabilityMessage_pb";
import { file_VolumeControlAvailabilityMessage } from "./VolumeControlAvailabilityMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VolumeControlCapabilitiesDidChangeMessage.proto.
 */
export const file_VolumeControlCapabilitiesDidChangeMessage: GenFile = /*@__PURE__*/
  fileDesc("Ci9Wb2x1bWVDb250cm9sQ2FwYWJpbGl0aWVzRGlkQ2hhbmdlTWVzc2FnZS5wcm90byKSAQopVm9sdW1lQ29udHJvbENhcGFiaWxpdGllc0RpZENoYW5nZU1lc3NhZ2USNwoMY2FwYWJpbGl0aWVzGAEgASgLMiEuVm9sdW1lQ29udHJvbEF2YWlsYWJpbGl0eU1lc3NhZ2USEwoLZW5kcG9pbnRVSUQYAyABKAkSFwoPb3V0cHV0RGV2aWNlVUlEGAQgASgJOpoBCil2b2x1bWVDb250cm9sQ2FwYWJpbGl0aWVzRGlkQ2hhbmdlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRhEIAEoCzIqLlZvbHVtZUNvbnRyb2xDYXBhYmlsaXRpZXNEaWRDaGFuZ2VNZXNzYWdlUil2b2x1bWVDb250cm9sQ2FwYWJpbGl0aWVzRGlkQ2hhbmdlTWVzc2FnZQ", [file_ProtocolMessage, file_VolumeControlAvailabilityMessage]);

/**
 * @generated from message VolumeControlCapabilitiesDidChangeMessage
 */
export type VolumeControlCapabilitiesDidChangeMessage = Message<"VolumeControlCapabilitiesDidChangeMessage"> & {
  /**
   * @generated from field: optional VolumeControlAvailabilityMessage capabilities = 1;
   */
  capabilities?: VolumeControlAvailabilityMessage;

  /**
   * @generated from field: optional string endpointUID = 3;
   */
  endpointUID: string;

  /**
   * @generated from field: optional string outputDeviceUID = 4;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message VolumeControlCapabilitiesDidChangeMessage.
 * Use `create(VolumeControlCapabilitiesDidChangeMessageSchema)` to create a new message.
 */
export const VolumeControlCapabilitiesDidChangeMessageSchema: GenMessage<VolumeControlCapabilitiesDidChangeMessage> = /*@__PURE__*/
  messageDesc(file_VolumeControlCapabilitiesDidChangeMessage, 0);

/**
 * @generated from extension: optional VolumeControlCapabilitiesDidChangeMessage volumeControlCapabilitiesDidChangeMessage = 68;
 */
export const volumeControlCapabilitiesDidChangeMessage: GenExtension<ProtocolMessage, VolumeControlCapabilitiesDidChangeMessage> = /*@__PURE__*/
  extDesc(file_VolumeControlCapabilitiesDidChangeMessage, 0);

