// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file VolumeControlAvailabilityMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VolumeControlAvailabilityMessage.proto.
 */
export const file_VolumeControlAvailabilityMessage: GenFile = /*@__PURE__*/
  fileDesc("CiZWb2x1bWVDb250cm9sQXZhaWxhYmlsaXR5TWVzc2FnZS5wcm90byJMChJWb2x1bWVDYXBhYmlsaXRpZXMiNgoERW51bRIICgROb25lEAASDAoIUmVsYXRpdmUQARIMCghBYnNvbHV0ZRACEggKBEJvdGgQAyJ4CiBWb2x1bWVDb250cm9sQXZhaWxhYmlsaXR5TWVzc2FnZRIeChZ2b2x1bWVDb250cm9sQXZhaWxhYmxlGAEgASgIEjQKEnZvbHVtZUNhcGFiaWxpdGllcxgCIAEoDjIYLlZvbHVtZUNhcGFiaWxpdGllcy5FbnVtOn8KIHZvbHVtZUNvbnRyb2xBdmFpbGFiaWxpdHlNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGBYgASgLMiEuVm9sdW1lQ29udHJvbEF2YWlsYWJpbGl0eU1lc3NhZ2VSIHZvbHVtZUNvbnRyb2xBdmFpbGFiaWxpdHlNZXNzYWdl", [file_ProtocolMessage]);

/**
 * @generated from message VolumeCapabilities
 */
export type VolumeCapabilities = Message<"VolumeCapabilities"> & {
};

/**
 * Describes the message VolumeCapabilities.
 * Use `create(VolumeCapabilitiesSchema)` to create a new message.
 */
export const VolumeCapabilitiesSchema: GenMessage<VolumeCapabilities> = /*@__PURE__*/
  messageDesc(file_VolumeControlAvailabilityMessage, 0);

/**
 * This is really a bitmap but protobuf has no type for that, so lets just add a "Both"
 * option since only two values exist anyway
 *
 * @generated from enum VolumeCapabilities.Enum
 */
export enum VolumeCapabilities_Enum {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Relative = 1;
   */
  Relative = 1,

  /**
   * @generated from enum value: Absolute = 2;
   */
  Absolute = 2,

  /**
   * @generated from enum value: Both = 3;
   */
  Both = 3,
}

/**
 * Describes the enum VolumeCapabilities.Enum.
 */
export const VolumeCapabilities_EnumSchema: GenEnum<VolumeCapabilities_Enum> = /*@__PURE__*/
  enumDesc(file_VolumeControlAvailabilityMessage, 0, 0);

/**
 * @generated from message VolumeControlAvailabilityMessage
 */
export type VolumeControlAvailabilityMessage = Message<"VolumeControlAvailabilityMessage"> & {
  /**
   * @generated from field: optional bool volumeControlAvailable = 1;
   */
  volumeControlAvailable: boolean;

  /**
   * @generated from field: optional VolumeCapabilities.Enum volumeCapabilities = 2;
   */
  volumeCapabilities: VolumeCapabilities_Enum;
};

/**
 * Describes the message VolumeControlAvailabilityMessage.
 * Use `create(VolumeControlAvailabilityMessageSchema)` to create a new message.
 */
export const VolumeControlAvailabilityMessageSchema: GenMessage<VolumeControlAvailabilityMessage> = /*@__PURE__*/
  messageDesc(file_VolumeControlAvailabilityMessage, 1);

/**
 * @generated from extension: optional VolumeControlAvailabilityMessage volumeControlAvailabilityMessage = 22;
 */
export const volumeControlAvailabilityMessage: GenExtension<ProtocolMessage, VolumeControlAvailabilityMessage> = /*@__PURE__*/
  extDesc(file_VolumeControlAvailabilityMessage, 0);

