// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file VolumeDidChangeMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file VolumeDidChangeMessage.proto.
 */
export const file_VolumeDidChangeMessage: GenFile = /*@__PURE__*/
  fileDesc("ChxWb2x1bWVEaWRDaGFuZ2VNZXNzYWdlLnByb3RvIlYKFlZvbHVtZURpZENoYW5nZU1lc3NhZ2USDgoGdm9sdW1lGAEgASgCEhMKC2VuZHBvaW50VUlEGAIgASgJEhcKD291dHB1dERldmljZVVJRBgDIAEoCTphChZ2b2x1bWVEaWRDaGFuZ2VNZXNzYWdlEhAuUHJvdG9jb2xNZXNzYWdlGDggASgLMhcuVm9sdW1lRGlkQ2hhbmdlTWVzc2FnZVIWdm9sdW1lRGlkQ2hhbmdlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message VolumeDidChangeMessage
 */
export type VolumeDidChangeMessage = Message<"VolumeDidChangeMessage"> & {
  /**
   * @generated from field: optional float volume = 1;
   */
  volume: number;

  /**
   * @generated from field: optional string endpointUID = 2;
   */
  endpointUID: string;

  /**
   * @generated from field: optional string outputDeviceUID = 3;
   */
  outputDeviceUID: string;
};

/**
 * Describes the message VolumeDidChangeMessage.
 * Use `create(VolumeDidChangeMessageSchema)` to create a new message.
 */
export const VolumeDidChangeMessageSchema: GenMessage<VolumeDidChangeMessage> = /*@__PURE__*/
  messageDesc(file_VolumeDidChangeMessage, 0);

/**
 * @generated from extension: optional VolumeDidChangeMessage volumeDidChangeMessage = 56;
 */
export const volumeDidChangeMessage: GenExtension<ProtocolMessage, VolumeDidChangeMessage> = /*@__PURE__*/
  extDesc(file_VolumeDidChangeMessage, 0);

