// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file WakeDeviceMessage.proto (syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProtocolMessage } from "./ProtocolMessage_pb";
import { file_ProtocolMessage } from "./ProtocolMessage_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file WakeDeviceMessage.proto.
 */
export const file_WakeDeviceMessage: GenFile = /*@__PURE__*/
  fileDesc("ChdXYWtlRGV2aWNlTWVzc2FnZS5wcm90byITChFXYWtlRGV2aWNlTWVzc2FnZTpSChF3YWtlRGV2aWNlTWVzc2FnZRIQLlByb3RvY29sTWVzc2FnZRgtIAEoCzISLldha2VEZXZpY2VNZXNzYWdlUhF3YWtlRGV2aWNlTWVzc2FnZQ", [file_ProtocolMessage]);

/**
 * @generated from message WakeDeviceMessage
 */
export type WakeDeviceMessage = Message<"WakeDeviceMessage"> & {
};

/**
 * Describes the message WakeDeviceMessage.
 * Use `create(WakeDeviceMessageSchema)` to create a new message.
 */
export const WakeDeviceMessageSchema: GenMessage<WakeDeviceMessage> = /*@__PURE__*/
  messageDesc(file_WakeDeviceMessage, 0);

/**
 * @generated from extension: optional WakeDeviceMessage wakeDeviceMessage = 45;
 */
export const wakeDeviceMessage: GenExtension<ProtocolMessage, WakeDeviceMessage> = /*@__PURE__*/
  extDesc(file_WakeDeviceMessage, 0);

