import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import { build, clean, dts } from '@basmilius/tools';
import type { Build } from 'bun';

type Target = [outfile: string, target: Build.CompileTarget];

const targets: Target[] = [
    ['ap-diagnostics-linux-arm64', 'bun-linux-arm64'],
    ['ap-diagnostics-linux-x64', 'bun-linux-x64'],
    ['ap-diagnostics-macos-arm64', 'bun-darwin-arm64'],
    ['ap-diagnostics-macos-x64', 'bun-darwin-x64'],
    ['ap-diagnostics-windows-x64.exe', 'bun-windows-x64']
];

function collectFiles(dir: string, base: string = dir): Record<string, string> {
    const result: Record<string, string> = {};

    for (const entry of readdirSync(dir, {withFileTypes: true})) {
        const fullPath = resolve(dir, entry.name);

        if (entry.isDirectory()) {
            Object.assign(result, collectFiles(fullPath, base));
        } else {
            const key = '/' + relative(base, fullPath);
            result[key] = readFileSync(fullPath, 'utf-8');
        }
    }

    return result;
}

// Generate embedded web assets module
const distWebDir = resolve(import.meta.dir, 'dist-web');
let hasWebAssets = false;

try {
    const assets = collectFiles(distWebDir);
    const lines = Object.entries(assets).map(([path, content]) =>
        `    ${JSON.stringify(path)}: ${JSON.stringify(content)}`
    );
    const module = `// Auto-generated by build.ts — do not edit\nexport default {\n${lines.join(',\n')}\n} as Record<string, string>;\n`;
    writeFileSync(resolve(import.meta.dir, 'src/web/embeddedAssets.ts'), module);
    hasWebAssets = true;
    console.log(`Embedded ${Object.keys(assets).length} web assets.`);
} catch {
    console.warn('No dist-web/ found, skipping web asset embedding.');
    writeFileSync(resolve(import.meta.dir, 'src/web/embeddedAssets.ts'), 'export default {} as Record<string, string>;\n');
}

const cleaner = clean('dist');
await cleaner.setup(undefined);

for (const [outfile, target] of targets) {
    console.log(`Building ${outfile}...`);

    await build({
        entrypoints: ['src/index.ts'],
        bytecode: true,
        minify: false,
        sourcemap: 'none',
        target: 'bun',
        plugins: [
            dts()
        ],
        external: [],
        compile: {outfile, target}
    });
}
