import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, relative } from 'node:path';

function collectFiles(dir: string, base: string = dir): Record<string, string> {
    const result: Record<string, string> = {};

    for (const entry of readdirSync(dir, {withFileTypes: true})) {
        const fullPath = resolve(dir, entry.name);

        if (entry.isDirectory()) {
            Object.assign(result, collectFiles(fullPath, base));
        } else {
            const key = '/' + relative(base, fullPath);
            result[key] = readFileSync(fullPath, 'utf-8');
        }
    }

    return result;
}

// Generate embedded web assets module from dist-web/. Must run before tsgo and
// build.ts, since src/web/server.ts imports the generated embeddedAssets.ts.
export function embedWebAssets(): void {
    const distWebDir = resolve(import.meta.dir, 'dist-web');
    const outFile = resolve(import.meta.dir, 'src/web/embeddedAssets.ts');

    try {
        const assets = collectFiles(distWebDir);
        const lines = Object.entries(assets).map(([path, content]) =>
            `    ${JSON.stringify(path)}: ${JSON.stringify(content)}`
        );
        const module = `// Auto-generated by embedWebAssets.ts — do not edit\nexport const embeddedAssets: Record<string, string> = {\n${lines.join(',\n')}\n};\n`;
        writeFileSync(outFile, module);
        console.log(`Embedded ${Object.keys(assets).length} web assets.`);
    } catch {
        console.warn('No dist-web/ found, skipping web asset embedding.');
        writeFileSync(outFile, 'export const embeddedAssets: Record<string, string> = {};\n');
    }
}

if (import.meta.main) {
    embedWebAssets();
}
