name: 🚀 Release packages

on:
    release:
        types: [ released ]

env:
    RELEASE_VERSION: ${{ github.event.release.tag_name }}

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        name: 🚀 Publish to Registry
        steps:
            -   name: 👀 Checkout
                uses: actions/checkout@v4

            -   name: 🍞 Setup Bun
                uses: oven-sh/setup-bun@v2

            -   name: ✏️ Tag v${{ env.RELEASE_VERSION }}
                run: |
                    # Temporary solution for the commented out lines below.
                    sed -i 's/0.0.0/${{ env.RELEASE_VERSION }}/g' packages/*/package.json
                    sed -i 's/workspace:\*/${{ env.RELEASE_VERSION }}/g' packages/*/package.json

            -   name: 📦️ Install dependencies
                run: bun install --frozen-lockfile

            -   name: 🔨 Build
                run: |
                    export NOMINIFY=1
                    
                    bun --cwd packages/encoding build
                    bun --cwd packages/encryption build
                    bun --cwd packages/common build
                    bun --cwd packages/audio-source build
                    bun --cwd packages/airplay build
                    bun --cwd packages/companion-link build
                    bun --cwd packages/devices build

            -   name: 🚀 Publish v${{ env.RELEASE_VERSION }}
                run: |
                    bun publish --cwd packages/encoding --access public
                    bun publish --cwd packages/encryption --access public
                    bun publish --cwd packages/common --access public
                    bun publish --cwd packages/audio-source --access public
                    bun publish --cwd packages/airplay --access public
                    bun publish --cwd packages/companion-link --access public
                    bun publish --cwd packages/devices --access public
                env:
                    NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
